conda-forge/conda-smithy

.gitignore
conda_smithy/configure_circle_ci.py
conda_smithy/configure_feedstock.py
conda_smithy/tests/test_configure_feedstock.py

print functions

---

conda_smithy/configure_circle_ci.py
scripts/conda-smithy

This does not really do what #2 suggests but it prevents import fails.

Temporary workaround for no tokens

---

MANIFEST.in
requirements.txt
setup.py

Used MANIFEST for setup.py resource management.

---

README
README.md

Also change it to a markdown file so that it looks nicer.

Add more extensive instructions to the README

---

conda_smithy/conda_smithy.py

Change initialization of user_or_org for user

---

conda_smithy/conda_smithy.py
conda_smithy/configure_feedstock.py
conda_smithy/feedstock_content/circle.yml
conda_smithy/templates/travis.yml.tmpl

These are the changes that I needed to make to get repos correctly configured to build linux and osx conda binaries.  Thoughts?

ENH: Make more use of conda-forge.yml

---

conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/run_docker_build.tmpl
conda_smithy/templates/run_docker_build_matrix.tmpl
conda_smithy/templates/travis.yml.tmpl

MNT: Sort loops in jinja-templates

---

conda_smithy/templates/travis.yml.tmpl

Also sort the dict because deterministic jinja output is good

Remove items() from jinja2 dict so that it can be sorted

---

conda_smithy/configure_feedstock.py

fix feedstock image

---

conda_smithy/configure_feedstock.py
conda_smithy/feedstock_content/ci_support/upload_or_check_non_existence.py
conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/run_docker_build.tmpl
conda_smithy/templates/run_docker_build_matrix.tmpl
conda_smithy/templates/travis.yml.tmpl

Note: Breaks use of channels/target in favour of the more flexible channels/targets.

Made tweaks to the templating system to allow some more flexibility with channels.

---

conda_smithy/feedstock_content/ci_support/upload_or_check_non_existence.py

Sorry @danielballan - I knew about this 24 hours ago and should have fixed then. Hopefully it didn't take too long to solve.

Fixed anaconda-client usage.

---

conda_smithy/ci_register.py
conda_smithy/cli.py
conda_smithy/github.py

A PR of https://github.com/JanSchulz/conda-smithy/commit/f29fa91cdfbe197779408cca74fa541aee9b845b.

Do not use sys.exit() in submodules

---

conda_smithy/feedstocks.py

This was the minimum change to make the automated PR script from https://github.com/conda-forge/conda-forge.github.io/pull/31 viable. There are other cases where parallelism will help massively.

Added parallelism to the fetch_feedstocks capability.

---

conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/travis.yml.tmpl

Make the secure variables configurable for AppVeyor.

---

README.md

Fix readme CLI reference

---

README.md

See https://github.com/conda-forge/conda-smithy/pull/69/files#r55704236
Thanks @JanSchulz!

Fix the fix for the readme

---

conda_smithy/templates/README.md.tmpl

Fixes https://github.com/conda-forge/conda-smithy/issues/76
Shows info like the latest version on Anaconda and how many downloads have occurred.

Add anaconda badges

---

conda_smithy/feedstocks.py

Realised that I missed this CLI out with a refactor.
Some more tests are certainly needed on this repo.

Fixed feedstocks apply-cloned CLI.

---

conda_smithy/cli.py
conda_smithy/configure_feedstock.py
conda_smithy/templates/travis.yml.tmpl

Also fixes some whitespace to look better on travis.yml.

Moved the location of the CONDA_NPY fudge so that non CLI users benefit.

---

conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/run_docker_build.tmpl
conda_smithy/templates/travis.yml.tmpl

Makes sure the option to show conda channel URLs is enabled on all CIs.

Show conda channels on all CIs

---

conda_smithy/lint_recipe.py
conda_smithy/tests/test_lint_recipe.py

Added some more resilience on some section fetches.

---

conda_smithy/lint_recipe.py
conda_smithy/tests/test_lint_recipe.py

Completes https://github.com/conda-forge/conda-smithy/pull/138.

Selector msg

---

conda_smithy/lint_recipe.py

Explicitly spell out the numbers of spaces since it's just not clear in
the messages.

Try to clarify selector message (Fixes #136)

---

conda_smithy/configure_feedstock.py

This is consistent with previous versions of conda-smithy, and makes some sense.

Ordered Circle and Travis by python group

---

conda_smithy/configure_feedstock.py

Closes https://github.com/conda-forge/staged-recipes/issues/594.

Fixed the case where conda-forge.yml wasn't defined correctly 

---

conda_smithy/github.py

Feedstocks were being named badly 😢

Fix the name of the feedstock.

---

conda_smithy/lint_recipe.py

Fixes the bug that @kalefranz encountered in conda-forge/staged-recipes#560

Patch over unicode differences between py2 and py3

---

conda_smithy/ci_register.py

It still falls back to getting the value from the BINSTAR_TOKEN environment variable.
Fixes https://github.com/conda-forge/conda-smithy/issues/50

Add ability to put BINSTAR token into ~/conda-smith/anaconda.token

---

conda_smithy/cli.py

Added the ability to `conda smithy --version`

---

conda_smithy/ci_register.py
conda_smithy/cli.py
conda_smithy/templates/README.md.tmpl

V0.10.x into master

---

conda_smithy/templates/README.md.tmpl
conda_smithy/templates/run_docker_build.tmpl
conda_smithy/templates/travis.yml.tmpl

Saw these in one feedstock, and wanted to propagate the improvement. I'll hold this back until we have a coherent set of changes for the feedstocks (including conda-forge-build-setup).

Whitespace improvements in the feedstock.

---

conda_smithy/configure_feedstock.py

Errata from PR ( https://github.com/conda-forge/conda-smithy/pull/207 ).

Fix comment to refer to `.travis.yml`

---

conda_smithy/ci_register.py

@jakirkham - I have no idea how long a token lasts, but it seems that this will at least allow us to have some more reliability with our authentication.

Cache the travis token accross sessions.

---

conda_smithy/configure_feedstock.py

fix reference to cc to be more compatible across cb versions

---

conda_smithy/feedstocks.py

Will generalise some of the conda-forge.github.io/scripts capabilities so that we can fix them in one place rather than several.

New feedstocks functions

---

README.md

I thought it would be quite useful to have these instructions. I had to figure them out by looking at the code and doing trial--and-error. Let me know if I need to update anything if you are interested in the PR.

add instructions on how to specify target channels to upload

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/README.md.tmpl

1. Added a one-liner for installation command
1. Replaced `conda-forge` with `{{github.user_or_org}}`, so the user can add this to `conda-forge.yml`
```
github:
user_or_org: github_organization
repo_name: github_repo
```

Update README template 

---

conda_smithy/cli.py

Tweak suggested re-rendering commit message slightly.

Slight adjustment to commit message

---

bootstrap-obvious-ci-and-miniconda.py
conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/travis.yml.tmpl

Same as @hadim's https://github.com/pelson/Obvious-CI/pull/67

Vendorize obvious-ci bootstrap

---

setup.py

Make use of the `unittest` test collector so as to allow `python setup.py test` to work.

Use test collector

---

conda_smithy.recipe/meta.yaml

Cleans up the recipe to look more like the [one]( https://github.com/conda-forge/conda-smithy-feedstock/blob/2ddac63ca6d6d1edfa599e4219b164f7d70a4d74/recipe/meta.yaml ) in the feedstock.

Cleanup recipe

---

conda_smithy/feedstock_io.py

Fixes https://github.com/conda-forge/conda-smithy/issues/350 (?)
Closes https://github.com/conda-forge/conda-smithy/pull/358
Came across the second problem described by the OP in issue ( https://github.com/conda-forge/conda-smithy/issues/350 ) when writing some unit tests. Demonstration of its recreation can be seen in PR ( https://github.com/conda-forge/conda-smithy/pull/358 ).
Cannot confirm that this fixes that issue as I don't have enough details to determine whether they are the same problem or two different problems with the same error. In any event, fixing this problem is helpful in either event.
cc @janschulz

Fix get_file_blob bug

---

conda_smithy/feedstock_io.py

Better handle the case of an empty directory name.

Handle empty root directory

---

.travis.yml

Use the `unittest` test runner on Travis CI.

Use test runner on CI

---

.travis.yml
conda_smithy.recipe/meta.yaml

Drop `nose` as a test requirement as it is no longer required.

Drop nose requirement

---

README.md

Add documentation on re-renders new commit option to the README.

Note re-render commit option

---

conda_smithy/templates/appveyor.yml.tmpl

Reverts conda-forge/conda-smithy#405
READ https://github.com/appveyor/ci/issues/1222#issuecomment-269885042

Revert "Revert PR 404"

---

conda_smithy/ci_register.py

Fixes https://github.com/conda-forge/status/issues/30

Enable building PRs from forks in circle

---

conda_smithy/feedstocks.py

Fix help message to match actual flag name.

feedstocks list: organisation -> organization

---

conda_smithy/configure_feedstock.py

@pelson I appreciate if you could take a look. Not sure if this is all we need to unlock the creation of `R` feedstocks.

add r-base

---

conda_smithy/cli.py

As we already stage changes to a feedstock's git repo (should it exist), it makes sense that we actually create a git repo if we will need one before we add content to the feedstock. By doing this, we can simplify and cut redundant code from `conda_smithy.cli` that is already handled effectively in `conda_smithy.configure_feedstock`. Thus reducing our chances of code rot and also avoiding contaminating any other repo.

Simplify feedstock repo initialization

---

conda_smithy/github.py

Minor cleanup inside of the `conda_smithy.github` module. Changes include...
* Use future `print`.
* Move `import` statements out of function. (dependencies already required)
* Assign a variable before entering a branch.

Minor cleanup of GitHub registration

---

conda_smithy/configure_feedstock.py

Closes https://github.com/conda-forge/setuptools-feedstock/pull/63 (used for testing)
xref: https://github.com/appveyor/ci/issues/1365
xref: https://github.com/conda-forge/staged-recipes/pull/2572

Use AppVeyor's Miniconda 3.6 with Python 3.6

---

conda_smithy/ci_register.py

Also print out what the response actually is.
Maybe addresses #233.
Any idea how one would go about testing this?

Let the travis-ci response fail to be json.

---

conda_smithy/ci_register.py

check for error codes with `response.raise_for_status()` before assuming responses are valid JSON, etc.
related to #498 where there's a pretty good chance that travis is responding with an error.

check http response codes in more places

---

conda_smithy/cli.py

"enabled enabled"; "regnerate".

Correct typos in RegisterCI summary message.

---

conda_smithy/ci_register.py

Remove redundant synching.

---

conda_smithy/cli.py

Backports pull request #510 for 2.3.x.
cc @pkgw

Backport pull request #510 for 2.3.x

---

conda_smithy/ci_register.py

Backports pull request #508 for 2.3.x.
cc @isuruf

Backport pull request #508 for 2.3.x

---

.travis.yml
conda_smithy/cli.py

Backports pull request #523 for 2.3.x

Backport pull request #523 for 2.3.x

---

conda_smithy/cli.py

Will help debug things like https://github.com/conda-forge/staged-recipes/issues/3152

List problematic file

---

conda_smithy/feedstock_content/.gitattributes

This is so that patch files are not messed up by git

Mark patch files as binary

---

conda_smithy/ci_register.py
conda_smithy/cli.py

Needed for https://github.com/conda-forge/conda-forge-webservices/pull/96

Add hook for updating teams

---

CHANGELOG.md

Add a CHANGELOG file which points to the releases page

---

.travis.yml
conda_smithy/ci_register.py

Just refactors out a common function for getting the webhook paylod.

Refactor hooks

---

conda_smithy/templates/README.md.tmpl

Our docs have a low visibility and this is a small step to try to change that.
@isuruf can you take a quick look?
Ping @choldgraf who brought this up.

add docs link

---

conda_smithy/lint_recipe.py

Added a linter check for numpy x.x requirements.

---

conda_smithy/ci_register.py

Needed for https://github.com/conda-forge/conda-forge-webservices/pull/102

Add hook for PR comments

---

conda_smithy/templates/README.md.tmpl

Fixes https://github.com/conda-forge/conda-smithy/issues/562

Add instructions to update conda

---

conda_smithy/ci_register.py

I added `issue` after the other 4 and forgot to test. Sorry about that.

Fix event type

---

conda_smithy/templates/appveyor.yml.tmpl

See https://github.com/conda/conda/issues/6527
and https://github.com/conda/conda/issues/6553
cc @conda-forge/core

Use conda.exe to avoid issues with the new conda.bat

---

conda_smithy/github.py

This API is provided for use in conda-forge-webservices

API for github team updates

---

conda_smithy/templates/README.md.tmpl

Need to test this manually yet (see how it looks)

Use shields.io badges

---

conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/run_docker_build.tmpl
conda_smithy/templates/travis.yml.tmpl

Fix config file location

---

conda_smithy/configure_feedstock.py
requirements.txt
tests/conftest.py
tests/test_cli.py
tests/test_configure_feedstock.py

fixes #658 
fixes #650 
fixes #653
fixes #651 
CC @jakirkham @isuruf

Fix sublevel looping

---

conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/run_docker_build.tmpl
conda_smithy/templates/travis.yml.tmpl

Use conda-forge-ci-setup and cleanup templates

---

conda_smithy/ci_register.py

Should this go in a new maintenance branch 2.x, so that we can release this quickly?
Staged-recipes is broken atm.

Use travis-ci API 3

---

conda_smithy/lint_recipe.py
tests/test_lint_recipe.py

Re: https://github.com/bioconda/bioconda-recipes/issues/7574.
@bgruening, maybe you can suggest a more reliable will-always-be-in-bioconda recipe for the test? I picked `abawaca` just because it's near the top and the name looked fun. :)

linter: check if bioconda recipe exists

---

conda_smithy/lint_recipe.py
tests/test_lint_recipe.py

lint in examples folder

---

conda_smithy/configure_feedstock.py

Drop CONDA_BUILD_SYSROOT

---

conda_smithy/templates/appveyor.yml.tmpl

conda update in appveyor

---

conda_smithy/cli.py
conda_smithy/configure_feedstock.py
tests/test_cli.py

Add exclusive-config-file CLI option

---

conda_smithy/templates/appveyor.yml.tmpl

I checked here, https://ci.appveyor.com/project/isuruf/zlib-feedstock/build/1.0.3 and it works now

Fix appveyor issues again

---

conda_smithy/lint_recipe.py
tests/test_lint_recipe.py

lint jinja2 variables

---

conda_smithy/templates/README.md.tmpl

xref: https://github.com/conda-forge/conda-smithy/pull/583

Fix disabled macOS badge name

---

conda_smithy/templates/appveyor.yml.tmpl

xref: https://github.com/conda/conda/issues/7144

Don't use C:\Miniconda3-x64

---

conda_smithy/feedstock_content/.github/ISSUE_TEMPLATE.md
conda_smithy/feedstock_content/.github/PULL_REQUEST_TEMPLATE.md

Fixes https://github.com/conda-forge/conda-smithy/issues/704

Update github files

---

conda_smithy/lint_recipe.py

fixes issue raised in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/39#issuecomment-380867143
CC @isuruf

add datetime and time to jinja2 stub namespace

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/circle.yml.tmpl
conda_smithy/templates/travis.yml.tmpl

Fixes https://github.com/conda-forge/conda-smithy/issues/734 with a hack. cc @msarahan

Workaround for 32-bit issue

---

.gitignore
README.md
rever.xsh

Adds rever support in order to issue releases.

Initial rever

---

.travis.yml
README.md
conda_smithy.recipe/meta.yaml

After all we should follow our own advice. :)
ref: https://conda-forge.org/docs/meta.html#use-pip

Switch to using pip

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/README.md.tmpl

Fix README for multiple outputs

---

conda_smithy/github.py

fix render in github.py that used removed function

---

news/pkg_badges_table.rst

xref: https://github.com/conda-forge/conda-smithy/pull/746

Note adding package badges in a table

---

conda_smithy/templates/circle.yml.tmpl

Allow linux* as platform rather than just linux.

---

conda_smithy/ci_register.py

Our current `travis_headers` confusingly requests both API V2 and V3.
This changes it to request only V3, except for the auth action which only works on V2 (https://github.com/travis-ci/travis-ci/issues/9273#issuecomment-370474214).
Don't know if this is actually related to https://github.com/conda-forge/staged-recipes/issues/5846, but it could be. :man_shrugging: 
(Note that I haven't gone through all our uses of `travis_headers` to make sure we're actually using the V3 API everywhere. It's very possible this could break something....)

travis API version handling

---

conda_smithy/cli.py

Make `conda smithy recipe-lint` also print out the new hints from #778.
cc @mariusvniekerk

CLI support for hints from #778

---

conda_smithy/templates/run_docker_build.sh.tmpl

Based on [this feedback]( https://github.com/conda-forge/staged-recipes/pull/5869#pullrequestreview-120634878 ).

Use `mkdir -p` to create directory

---

conda_smithy/lint_recipe.py
tests/test_lint_recipe.py

fixes error message for build, host, run order.

---

conda_smithy/configure_feedstock.py

cc @anton-malakhov, @jakirkham

Fix configs when value of a key in zip_keys is repeated

---

conda_smithy/cli.py
conda_smithy/configure_feedstock.py
conda_smithy/feedstocks.py
conda_smithy/lint_recipe.py
conda_smithy/update_cb3.py
conda_smithy/utils.py
news/update_cb3.rst

Add update-cb3

---

conda_smithy/configure_feedstock.py
news/fix-sorting.rst

Fixes https://github.com/conda-forge/conda-smithy/issues/790

Fix sorting of variants with zip_keys

---

conda_smithy/ci_register.py
conda_smithy/github.py

treat empty token files as if they weren't there

---

conda_smithy/lint_recipe.py

@bgruening not sure if you wrote this but you are my point of contact for `bioconda` recipes :smile: 
Can you please review it?

don't fail for bioconda recipes

---

conda_smithy/configure_feedstock.py
news/track_versions.rst

Reverts conda-forge/conda-smithy#822

Revert "track conda-smithy, etc versions in the feedstock"

---

conda_smithy/configure_feedstock.py
news/appveyor_image.rst
news/fix_ordered_dict_dumping.rst

https://github.com/conda-forge/conda-smithy/issues/811

Fix represetation of OrderedDict in dumped yaml files

---

MANIFEST.in
news/package_tst.rst

Package tests

---

conda_smithy/feedstock_content/.github/PULL_REQUEST_TEMPLATE.md
news/rerender.rst

cc @jasongrout, @ocefpaf, @dougalsutherland

Fix rerender text in PR template

---

conda_smithy/lint_recipe.py
news/fix_ruamel.rst

fix linter error with new yaml

---

conda_smithy/lint_recipe.py

Because all the other FIELDS are sets.

Make the extras field contain a set and not a list

---

conda_smithy/update_cb3.py
news/tc3.rst

see https://github.com/regro/cf-scripts/issues/363

Toolchain3 for update-cb3

---

conda_smithy/templates/README.md.tmpl

It would look like this:
@scopatz what do you think?

add numfocus badge

---

.travis.yml

If this works I don't know why it works

use channel matrix?

---

conda_smithy/lint_recipe.py
news/lint_toolchain.rst

fixes https://github.com/conda-forge/conda-smithy/issues/907

update toolchain lint to error

---

conda_smithy.recipe/meta.yaml
conda_smithy/azure_ci_utils.py
conda_smithy/ci_register.py
conda_smithy/cli.py
conda_smithy/configure_feedstock.py
conda_smithy/templates/azure-pipelines-linux.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/azure-pipelines.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/run_docker_build.sh.tmpl
requirements.txt
tests/test_cli.py

This probably needs some more pieces.
For now this is configured to just generate for all platforms.

[Ready for review] Initial work on recipes for azure-pipelines

---

conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
tests/recipes/click-test-feedstock/.appveyor.yml

xref: https://github.com/conda-forge/conda-smithy/pull/901#discussion_r228599527
cc @DavidStaheli

Fix Cygwin spelling in comments

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/azure-pipelines-linux.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/run_docker_build.sh.tmpl

Some minor cleanup tweaks needed before we pull the trigger.
cc @willsmythe @DavidStaheli

Azure cleanup.

---

.github/PULL_REQUEST_TEMPLATE.md
news/pr_template.rst

add PR template asking for news

---

news/azure-v0.rst

Forgot adding this when the azure features were merged in.

Added news file for azure feaures

---

conda_smithy/templates/azure-pipelines-win.yml.tmpl
news/azure-win-build-setup.rst

Azure: improve build setup on windows

---

conda_smithy/github.py
conda_smithy/lint_recipe.py
news/teams.rst

Checklist
cc @conda-forge/core

Add support for teams as recipe maintainers

---

conda_smithy/configure_feedstock.py
news/create_feedstocks.rst

Fixed creating feedstocks with conda-build 3.17.x

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/circle.yml.tmpl
conda_smithy/templates/travis.yml.tmpl
news/configurable-timeout.rst

Continuation of #942 - Make idle timeout configurable

---

conda_smithy/utils.py
news/add-sep-to-mockos.rst
tests/test_lint_recipe.py

Add os.sep to MockOS

---

conda_smithy/configure_feedstock.py
news/rmb2.rst

branch2.0 -> master

---

README.md

Document setting custom target channel

---

conda_smithy/configure_feedstock.py
news/comp7.rst

gcc7 -> comp7

---

conda_smithy/templates/run_docker_build.sh.tmpl

upload packages fix

---

conda_smithy/cli.py

Update max version to 4.7

---

conda_smithy/templates/azure-pipelines-linux.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl

just removed some --quiet flags

minor azure tweaks

---

conda_smithy/azure_ci_utils.py
conda_smithy/configure_feedstock.py
conda_smithy/templates/azure-pipelines-win.yml.tmpl
news/minor-tweaks.rst

Some minor tweaks around azure and appveyor

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
news/yum-azure.rst

Add support for yum_requirements to azure builds

---

conda_smithy/templates/azure-pipelines-linux.yml.tmpl
news/qemu-activate-fix.rst

Simplification of #1019
Checklist

Minimal changeset to get sudo working on qemu

---

LICENSE.txt
conda_smithy/feedstock_content/LICENSE.txt
news/license_2019.rst

Bump the license year for 2019

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/azure-pipelines-linux.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
news/azure-build-duration.rst

Azure allows 6 hour long builds.  Lets use those
Checklist

Update maximum build time for azure

---

conda_smithy/feedstock_content/.github/PULL_REQUEST_TEMPLATE.md
conda_smithy/lint_recipe.py
conda_smithy/templates/README.md.tmpl
conda_smithy/update_cb3.py
tests/recipes/click-test-feedstock/README.md

fix broken links to conda-forge docs

---

conda_smithy/azure_ci_utils.py

Enable reporting by default

---

conda_smithy/configure_feedstock.py
news/azure-switch.rst
pytest.ini
tests/conftest.py
tests/test_cli.py
tests/test_configure_feedstock.py
tests/test_feedstock_io.py
tests/test_lint_recipe.py

Lets stop waiting for travis forever.
Checklist

Switched over default provider for osx and linux to azure.

---

conda_smithy/cli.py
conda_smithy/configure_feedstock.py
news/check.rst

@scopatz I think this will help with our rever check
Checklist

add check arg to regenerate

---

conda_smithy/feedstock_content/.github/PULL_REQUEST_TEMPLATE.md
conda_smithy/lint_recipe.py
conda_smithy/templates/README.md.tmpl
conda_smithy/update_cb3.py
tests/recipes/click-test-feedstock/README.md

Reverts conda-forge/conda-smithy#1041

Revert "fix broken links to conda-forge docs"

---

conda_smithy/cli.py
tests/test_cli.py

actually use the check kwarg

---

conda_smithy/azure_ci_utils.py

Fix azure ci utils

---

.gitignore
conda_smithy/templates/README.md.tmpl
news/fix-badge.rst

Previously this would render as circleci- everything disabled`
Checklist

Fixed badges for azure noarch

---

conda_smithy/templates/run_docker_build.sh.tmpl
news/shyaml.rst

Remove use of shyaml and add helpful messages

---

conda_smithy/configure_feedstock.py
news/default_provider.rst

Fix default provider for ppc64le

---

conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/azure-pipelines-linux.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/circle.yml.tmpl
conda_smithy/templates/run_docker_build.sh.tmpl
conda_smithy/templates/travis.yml.tmpl
news/envCI.rst

export env variable CI in CI

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/azure-pipelines-linux.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/azure-pipelines.yml.tmpl
conda_smithy/templates/circle.yml.tmpl
conda_smithy/templates/run_docker_build.sh.tmpl
conda_smithy/templates/travis.yml.tmpl
news/docker.rst
tests/conftest.py
tests/test_cli.py
tests/test_configure_feedstock.py

Introduce DOCKER_IMAGE in CI files and remove shyaml need in CI

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
news/azure_build_setup_override.rst

Checklist
Fixes https://github.com/conda-forge/conda-smithy/issues/1034

Allow overriding build setup script in azure too

---

conda_smithy/github.py
news/print_add_team.rst

print when adding new team to repo

---

conda_smithy/github.py
news/fix_github.rst

Fix the indentation level in github.py

---

conda_smithy/configure_feedstock.py
conda_smithy/feedstock_io.py

Remove already checked in pycache

---

conda_smithy/configure_feedstock.py
news/code_owners.rst

Add codeowners file

---

conda_smithy/templates/run_docker_build.sh.tmpl
news/shyaml-more-versions.rst

Use `shyaml -h` for `shyaml` detection to support newer versions

---

conda_smithy/configure_feedstock.py
news/remove_github.rst

Remove unnecessary github files

---

conda_smithy/configure_feedstock.py
news/codeowners.rst

Fixed issue where only the last maintainer is review requested

---

conda_smithy/lint_recipe.py
news/license.rst
tests/recipes/cb3_jinja2_functions/recipe/meta.yaml
tests/recipes/multiple_sources/meta.yaml
tests/test_lint_recipe.py

Checklist
Fixes https://github.com/conda-forge/conda-smithy/issues/1088

Make license_file required

---

conda_smithy/ci_register.py
news/appveyor_.rst

Fix configuring appveyor on repos starting with an underscore

---

conda_smithy/configure_feedstock.py
news/cfep9-no-system-variants.rst

Avoid using the conda variants whatsoever after our initial render

---

bootstrap-obvious-ci-and-miniconda.py
conda_smithy/ci_register.py
conda_smithy/cli.py
conda_smithy/configure_feedstock.py
conda_smithy/feedstock_io.py
conda_smithy/feedstocks.py
conda_smithy/github.py
conda_smithy/lint_recipe.py
news/remove_py2.rst
tests/test_feedstock_io.py
tests/test_lint_recipe.py
versioneer.py

Checklist
Code clean up: Removed support for python 2

[code cleanup] Remove support for python 2 as meta.yaml supports 3.6+ only

---

conda_smithy/templates/README.md.tmpl
news/readme-badge.rst

Should fix https://github.com/conda-forge/conda-smithy/issues/1087

correct the badge rendering in readme template

---

conda_smithy/configure_feedstock.py
conda_smithy/feedstock_content/.gitignore
news/render-gitignore.rst
tests/conftest.py
tests/test_configure_feedstock.py

Checklist
A solution for https://github.com/conda-forge/conda-smithy/issues/1118. The workflow is to merge .gitignore file in feedstock repo defined by repo author and typical default lines defined by conda-smithy package, such as `*.pyc`.

allow customize on gitignore

---

conda_smithy/configure_feedstock.py
news/verbosity.rst

This can be increased by setting `CONDA_SMITHY_LOGLEVEL=debug`
Checklist

Reduce verbosity of rerendering.

---

conda_smithy.recipe/meta.yaml
news/update-pycrypto-dep.rst
requirements.txt

Checklist
Fixes https://github.com/conda-forge/conda-smithy/issues/1126

Update pycrypto dependence to pycryptodome

---

news/downgrade_test.rst
tests/test_variant_algebra.py

WIP: add test for downgrade

---

conda_smithy/lint_recipe.py
news/single-space.rst
tests/test_lint_recipe.py

Checklist
This has been bothering me for a while.

Single space requirements lint

---

conda_smithy/lint_recipe.py
news/req.rst
tests/test_lint_recipe.py

Checklist
And also allow more than one spacing.

Fix linting requirement build numbers

---

tests/test_lint_recipe.py

Remove debug statement that was committed

---

conda_smithy/utils.py
news/ruamelfix.rst

ruamel v0.16 fix

---

conda_smithy/utils.py

Checklist
Uses path object now, like in example.

YAML used Path

---

conda_smithy/ci_register.py
conda_smithy/cli.py
conda_smithy/configure_feedstock.py
conda_smithy/templates/drone.yml.tmpl
news/drone_registration.rst

This makes use of the drone-cli go binary.
Checklist

Add drone ci registration

---

conda_smithy/ci_register.py
news/drone_register.rst

Checklist
Fixes #1146 
Fixes #1147

Fix drone issues

---

conda_smithy/variant_algebra.py
news/fix_variants.rst
tests/test_variant_algebra.py

This needs a release ASAP once it passes and is merged.
Checklist

Fix the variants rendering for cfep9

---

conda_smithy/configure_feedstock.py
news/switch_to_azure.rst
tests/test_configure_feedstock.py

Switch from appveyor to azure

---

conda_smithy/configure_feedstock.py
news/no-exe-for-skip-render.rst

build-locally might not exist due to skip_render

Do not chmod +x files that have been skipped

---

conda_smithy/feedstock_content/.gitattributes
news/ignore-drone-ci.rst

Hide Drone CI files from GitHub diffs

---

.travis.yml
news/run-black-ci.rst

To make sure the code remains blackified, run `black --check` on CI to verify the code is `black` would expect or error out if not.
Checklist

Run `black --check` on CI

---

.travis.yml
conda_smithy/_version.py
conda_smithy/azure_ci_utils.py
conda_smithy/ci_register.py
conda_smithy/cli.py
conda_smithy/configure_feedstock.py
conda_smithy/feedstock_content/build-locally.py
conda_smithy/feedstocks.py
conda_smithy/github.py
conda_smithy/lint_recipe.py
conda_smithy/variant_algebra.py
news/run-black-ci.rst
tests/conftest.py
tests/test_cli.py
tests/test_configure_feedstock.py
tests/test_feedstock_io.py
tests/test_lint_recipe.py
tests/test_variant_algebra.py
versioneer.py

Fix CI command running `black` and rerun `black` on codebase.
Checklist

Fix code with black

---

.travis.yml
conda_smithy/lint_recipe.py
news/ref_needed_fam2.rst
pyproject.toml

Closes #1169 because I know better than to fight with a code formatting PR
Checklist

refactor needed_families to top level

---

.travis.yml

For some reason black missed the config file, so we're forcing the issue
Checklist

force black to use toml

---

conda_smithy/lint_recipe.py
news/empty-host.rst
tests/test_lint_recipe.py

fixes this crash: https://github.com/conda-forge/nauty-feedstock/pull/7#issuecomment-540670699
Fixes https://github.com/conda-forge/conda-smithy/issues/1153

Do not crash on empty build/host/run sections

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/azure-pipelines-linux.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/azure-pipelines.yml.tmpl
conda_smithy/templates/circle.yml.tmpl
conda_smithy/templates/drone.yml.tmpl
conda_smithy/templates/travis.yml.tmpl
news/drone_name.rst

Shorten drone pipeline names

---

conda_smithy/feedstock_content/.gitattributes
news/scripts_hidden.rst

Hide .scripts in PR diffs

---

conda_smithy/utils.py

Checklist
See https://github.com/conda-forge/conda-forge.github.io/pull/903

Add mpi default value

---

conda_smithy/configure_feedstock.py
news/appveyor.rst

Checklist
Fixes https://github.com/conda-forge/conda-smithy/issues/1191

Fix appveyor.yml

---

conda_smithy/lint_recipe.py
news/python_lint.rst
tests/test_lint_recipe.py

Add python version lints

---

README.md
conda_smithy/ci_register.py
conda_smithy/cli.py
conda_smithy/templates/README.md.tmpl
conda_smithy/templates/travis.yml.tmpl
news/travis-updates.rst
tests/recipes/click-test-feedstock/README.md
versioneer.py

Update all references to travis-ci.org to point to .com instead

---

conda_smithy/lint_recipe.py
news/empty_host.rst
tests/test_lint_recipe.py

Test for empty host

---

.travis.yml
conda_smithy/lint_recipe.py
news/no_lint_output.rst
tests/test_lint_recipe.py

Fix python lint for recipes with outputs

---

README.md

Closes https://github.com/conda-forge/conda-smithy/issues/1207
Checklist

Update Readme with Azure specific instructions.

---

README.md

Add notes pertaining to branding in the README.md

---

conda_smithy/ci_skeleton.py
conda_smithy/templates/meta.yaml.ci-skel.tmpl
news/skel-fix.rst
tests/test_ci_skeleton.py

ci-skeleton fixes and improvements

---

conda_smithy/configure_feedstock.py
news/rendering.rst

BUG fix rendering README for some jinja2 vars

---

conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
news/upload_success_osx_win.rst

Only try to upload if previous steps succeeded on azure (osx + win)

---

conda_smithy/lint_recipe.py
news/linter-r-base-non-noarch-version-constraint.rst
tests/test_lint_recipe.py

Add version check r non noarch

---

conda_smithy/cli.py
news/skip_webservice.rst

Checklist
We can switch to an org wide webhook to save some GH API calls.
cc @beckermr

Option to skip webhooks

---

conda_smithy/configure_feedstock.py
news/fix_config_name.rst

Remove stars and spaces from config file names

---

conda_smithy/feedstock_content/.github/workflows/webservices.yml
conda_smithy/templates/conda-forge.yml.ci-skel.tmpl
news/webservices.rst
tests/conftest.py
tests/test_ci_skeleton.py
tests/test_configure_feedstock.py

This PR adds the config file for the webservices github action.
Checklist

ENH added webservices action

---

conda_smithy/configure_feedstock.py
news/AUTOMERGE.rst
tests/test_configure_feedstock.py

Fixes https://github.com/conda-forge/conda-smithy/issues/1235

Copy automerge action file always

---

conda_smithy/variant_algebra.py
news/space_variant.rst
tests/test_variant_algebra.py

Fixed variant comparisons when the variant has a space

---

conda_smithy/ci_register.py
conda_smithy/cli.py
conda_smithy/templates/travis.yml.tmpl
news/travis.rst

DEP move to the travis env var api for tokens

---

conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/drone.yml.tmpl
news/1254_rerender_missing_recipe_dir_from_config.rst

Checklist
Mentioned this in existing news entry from #1254 
Fixes #1257 
Tested rerendered make-feedstock using CI in https://github.com/conda-forge/make-feedstock/pull/22
I'm confident that the issues I'm seeing on osx in #1258 don't have to do with my changes here.

Fix hardcoded 'recipe' in conda_smithy/templates (#1257)

---

.travis.yml
conda_smithy.recipe/meta.yaml
conda_smithy/azure_ci_utils.py
conda_smithy/cli.py
conda_smithy/feedstock_tokens.py
news/cfep-13.rst
requirements.txt
tests/test_feedstock_tokens.py

This is the first of ~3 PRs for CFEP-13. This PR has the code to hash and register feedstock tokens in the right spots. Future PRs will have the output validation/registration code and CLI utils to rotate the binstar tokens.
Checklist

ENH CFEP-13 implementation #1

---

conda_smithy/ci_register.py
news/travis_ci.rst

BUG check for token on travis

---

MANIFEST.in
news/spdx_bug.rst

BUG wrong file in manifest for SPDX

---

conda_smithy/cli.py

Empty conda-forge.yml should contain empty dict not list FIX #1249

---

conda_smithy/lint_recipe.py
news/licenseref.rst

REF allow licenseref in license section

---

conda_smithy/templates/azure-pipelines-win.yml.tmpl
news/activate_win.rst

Windows conda environment is activated before conda calls

---

conda_smithy/configure_feedstock.py
news/appveyor.rst

ENH bump the appveyor image to vs2017

---

conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
news/homebrew.rst

REF use a faster script for removing homebrew

---

conda_smithy/templates/azure-pipelines-win.yml.tmpl
news/strawberry.rst

Remove deleting strawberry perl

---

conda_smithy/cli.py
news/azure_warn.rst

Import azure_ci_utils only when necessary. Avoids a warning

---

conda_smithy/configure_feedstock.py
news/change_azure_force_default_to_false.rst

Change azure.force default to False in conda-forge.yml (#1252)

---

conda_smithy/feedstocks.py
conda_smithy/lint_recipe.py
conda_smithy/utils.py
news/thread_safe.rst

Make yaml loading thread safe

---

conda_smithy/configure_feedstock.py
news/travis_fast_finish.rst

Removed fast finish script for travis as we now set the setting on travis

---

conda_smithy/templates/README.md.tmpl
news/drone_badge.rst

Fix drone CI badge

---

conda_smithy/lint_recipe.py
news/jinja2.rst
tests/test_lint_recipe.py

ENH added jinja2 variable spacing to lints

---

conda_smithy/lint_recipe.py
news/linter-existing-feedstock-underscore-dash.rst

Add check for existing feedstocks with underscore instead of dash and vv

---

conda_smithy/anaconda_token_rotation.py
conda_smithy/cli.py
conda_smithy/feedstock_tokens.py
news/rotate.rst
tests/test_anaconda_token_rotation.py

This PR is cleaned up version of the token rotation code from #1283. I will rebase that PR on master once this one goes in.
Checklist

ENH added code to rotate anaconda tokens

---

conda_smithy/cli.py
conda_smithy/configure_feedstock.py
conda_smithy/feedstock_tokens.py
conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/azure-pipelines-linux.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/drone.yml.tmpl
conda_smithy/templates/run_docker_build.sh.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
news/token_validation.rst
tests/test_feedstock_tokens.py

This PR has the final bits of code needed for CFEP-13 for conda smithy. It also fixes some bugs in the feedstock outputs testing and refactors that code to not munge repo names in unpredictable ways.
closes #1283 
Checklist

ENH CFEP-13 new CI package

---

conda_smithy/templates/build_steps.sh.tmpl
news/whitespace.rst

Fix whitespace changes

---

conda_smithy/licenses.txt
news/psf.rst

PSF-2.0 is not a deprecated license

---

conda_smithy/lint_recipe.py
tests/test_lint_recipe.py

Error if license_file is empty

---

conda_smithy/feedstock_tokens.py
news/ciskip.rst
tests/test_feedstock_tokens.py

ENH skip ci services during token registration

---

conda_smithy.recipe/meta.yaml
conda_smithy/cli.py
conda_smithy/configure_feedstock.py
news/download_cfp.rst
tests/test_cli.py

Download conda-forge-pinning on the fly

---

conda_smithy/configure_feedstock.py
conda_smithy/feedstock_content/.github/workflows/automerge.yml
news/automerge.rst
tests/test_configure_feedstock.py

This PR moves the automerge action to conda-forge.
Checklist

REF move automerge to conda-forge

---

conda_smithy/cli.py
news/feedstock-name-ci.rst

Get feedstock name from meta in CI registration

---

README.md

Persist the current workflow in the README

Add a note about consulting core for a release

---

conda_smithy/cli.py
conda_smithy/configure_feedstock.py
news/anaconda-api.rst

Use the anaconda API for version checks

---

conda_smithy/templates/meta.yaml.ci-skel.tmpl
news/ci-skel-build-no.rst
tests/test_ci_skeleton.py

Fix ci-skeleton template

---

conda_smithy/cli.py
conda_smithy/github.py
news/private_repo.rst

Fix https://github.com/conda-forge/conda-smithy/issues/1335

Add --private flag to register-github

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
news/private_upload.rst

Following https://github.com/conda-forge/conda-smithy/issues/1333

Private upload

---

conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl

Fix wrong private upload key in templates

---

conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/azure-pipelines-linux.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/circle.yml.tmpl
conda_smithy/templates/drone.yml.tmpl
conda_smithy/templates/run_docker_build.sh.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
conda_smithy/templates/travis.yml.tmpl
news/valname.rst
tests/test_configure_feedstock.py

ENH use proper repo name for CFEP-13

---

conda_smithy/templates/README.md.tmpl
news/ci-skel-build-no.rst
tests/recipes/click-test-feedstock/README.md
tests/recipes/click-test-feedstock/recipe/meta.yaml

For consistency, use SPDX for the feedstock license in READMEs.
See e.g. https://github.com/conda-forge/blosc-feedstock/pull/43
Checklist

SPDX for Feedstock License

---

conda_smithy/configure_feedstock.py

Fix trivial typo

---

conda_smithy/configure_feedstock.py
news/build_id.rst

Use AzureConfig in render_README. Fix #1329

---

conda_smithy/lint_recipe.py
news/link_spdx_license_list.rst
tests/test_lint_recipe.py

Link to SPDX license list in linter message

---

conda_smithy/feedstock_content/LICENSE.txt

Mention that the copyright is conda-forge contributors

---

.travis.yml
conda_smithy/configure_feedstock.py
conda_smithy/templates/README.md.tmpl
conda_smithy/templates/azure-pipelines.yml.tmpl
conda_smithy/templates/drone.yml.tmpl
conda_smithy/templates/travis.yml.tmpl
news/cross.rst
tests/test_cli.py
tests/test_configure_feedstock.py

Add cross compiling

---

conda_smithy/configure_feedstock.py
news/cross.rst

Make target_platform always available

---

conda_smithy/github.py
news/teams.rst

REF list teams by slug and remove members/teams properly

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/travis.yml.tmpl
news/macos_image.rst

Bump macOS images

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/build_steps.sh.tmpl
news/test_on_native_only.rst

Add a test_on_native_only option

---

conda_smithy/configure_feedstock.py
news/sdk_version.rst

Add MACOSX_SDK_VERSION as an always used key

---

conda_smithy/templates/run_osx_build.sh.tmpl
news/no_test_osx.rst

test_on_native_only is now supported on osx too

---

conda_smithy/anaconda_token_rotation.py
conda_smithy/azure_ci_utils.py
conda_smithy/azure_defaults.py
conda_smithy/ci_register.py
conda_smithy/cli.py
conda_smithy/configure_feedstock.py
conda_smithy/feedstock_tokens.py
conda_smithy/lint_recipe.py
news/azure_warning.rst
tests/conftest.py
tests/test_feedstock_tokens.py

Remove the warning for azure token for rerendering

---

conda_smithy/feedstock_content/build-locally.py
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/run_docker_build.sh.tmpl
news/debug_build_locally.rst

I manually patch this regularly in `build-locally.py`.
Checklist

Add support 'conda debug' calls in build-locally

---

conda_smithy/templates/README.md.tmpl
news/add_feedstocklicenseurl.rst
tests/recipes/click-test-feedstock/README.md

Add link to spdx.org for feedstock license

Add link to the feedstock license file

---

conda_smithy/variant_algebra.py
news/add_new_variant_algebra_ops.rst
tests/test_variant_algebra.py

Add new variant maths that can be used to handle the py39 migration

---

conda_smithy/feedstock_content/build-locally.py

See https://github.com/conda-forge/python-tzdata-feedstock/pull/1#pullrequestreview-504326326

Can I haz hacktoberfest t-shirt?

---

conda_smithy/configure_feedstock.py
news/TEMPLATE.rst
news/revcomp.rst

Reverts conda-forge/conda-smithy#1405

Revert "ENH make sure each compiler version gets a CI job"

---

conda_smithy/configure_feedstock.py
news/cb_master.rst

This also works for older conda-build releases as it is the default
Checklist
cc @mingwandroid

Fix for upcoming conda-build release

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/azure-pipelines-win.yml.tmpl
news/choco.rst
tests/conftest.py
tests/test_configure_feedstock.py

Checklist
This is needed to get cudatoolkit working on Windows. https://github.com/conda-forge/cudatoolkit-feedstock/pull/7 CC @conda-forge/cudatoolkit

choco on azure

---

conda_smithy/configure_feedstock.py
news/cb3.20.5.rst
tests/test_configure_feedstock.py
tests/test_lint_recipe.py

No need to use target_platform in our config names unless pseudo-cross

---

conda_smithy/lint_recipe.py
tests/test_lint_recipe.py

lint for noarch python without a bound on python version

---

conda_smithy/lint_recipe.py
tests/test_lint_recipe.py

make python lower bound a hint

---

conda_smithy/configure_feedstock.py
news/manual-migrations-ts.rst

See https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/129#issuecomment-720141482
Checklist

Fix missing timestamp type checks

---

README.md
news/status.rst

DOC add status badge

---

.github/workflows/tests.yml
news/ci.rst

BUG run ci on pull requests from forks too

---

conda_smithy/templates/run_docker_build.sh.tmpl

Checklist
cc @xhochy, @rgommers

try more to find the docker image before using fallback if shyaml is not installed

---

.authors.yml

DOC change my name to avoid changelog duplicates

---

README.md
news/readme.rst

DOC fix formatting in the readme

---

LICENSE.txt
conda_smithy/feedstock_content/LICENSE.txt

Update license year

---

.github/workflows/tests.yml

Fix coveralls

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/run_docker_build.sh.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl

I just wanted to add this for a first review (fixes #1440)
What do you all think?
Going to release boa with the latest two fixes applied today.
cc @beckermr @dhirschfeld

optionally use mambabuild

---

conda_smithy/configure_feedstock.py
conda_smithy/variant_algebra.py
news/ts.rst
tests/conftest.py
tests/test_configure_feedstock.py

cfp recommends migrator_ts, so use that

---

.github/workflows/tests.yml
conda_smithy/lint_recipe.py
news/noarch_python_lowerbound.rst
tests/test_lint_recipe.py

A lower bound on python version for noarch python is now required

---

conda_smithy/configure_feedstock.py
news/use_local.rst

Add use_local option to use the migrator from the feedstock

---

conda_smithy/templates/github-actions.tmpl

check errorlevel on windows for github-actions

---

conda_smithy/feedstock_content/.scripts/logging_utils.sh
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/github-actions.tmpl
conda_smithy/templates/run_docker_build.sh.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
news/fix_log_groups.rst

Checklist
Trying to partially address https://github.com/conda-forge/conda-smithy/pull/1436#issuecomment-791040414, aka this confusing log style:

Log groups: temporarily disable set -x if it was set

---

conda_smithy/configure_feedstock.py
conda_smithy/feedstock_content/build-locally.py
conda_smithy/templates/run_osx_build.sh.tmpl
news/osx-build-locally.rst

Allow osx in build-locally.py

---

conda_smithy/templates/travis.yml.tmpl
news/use-focal-on-travis.rst

As requested [on gitter](https://gitter.im/conda-forge-ppc64le/Lobby?at=6081679806e2e024e86c26ab). I've made a few tests and it seems fine.
Checklist

Use "dist: focal" for Linux builds on Travis

---

conda_smithy/lint_recipe.py

Checklist
Should fix issues like https://github.com/conda-forge/slack-sdk-feedstock/issues/7

Fix try except in checking for existing feedstocks

---

.github/workflows/tests.yml
conda_smithy/lint_recipe.py
news/pypi_lint.rst
tests/test_lint_recipe.py

check for duplicates with pypi name

---

conda_smithy/lint_recipe.py
news/url.rst
tests/test_lint_recipe.py

Fix linting of recipes with backup URLs

---

.pre-commit-config.yaml
conda_smithy/cli.py
conda_smithy/utils.py
news/init-changes.rst
tests/test_cli.py

This allows us to more easily automatically enroll feedstocks in the various bots.
Checklist

Copy conda-forge.yml from the source recipe directory to the feedstock

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/github-actions.tmpl
news/self-hosted-gha.rst

support for self-hosted github actions runners

---

.github/workflows/tests.yml
README.md
conda_smithy/_version.py
news/main.rst
versioneer.py

Checklist
This PR moves conda-smithy itself to main. Additional PRs to move feedstocks will be needed and are out of scope here.

ENH move main to master

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/automerge.yml.tmpl
conda_smithy/templates/webservices.yml.tmpl
news/main_feedstock.rst
tests/test_configure_feedstock.py

Checklist
This PR adds support for master or main as the default branch for the tooling repos.

ENH support master or main for tooling

---

conda_smithy/feedstock_content/build-locally.py
conda_smithy/templates/azure-pipelines-linux.yml.tmpl
conda_smithy/templates/azure-pipelines-osx.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/circle.yml.tmpl
conda_smithy/templates/drone.yml.tmpl
conda_smithy/templates/github-actions.tmpl
conda_smithy/templates/run_docker_build.sh.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
conda_smithy/templates/travis.yml.tmpl
news/is_pr_build.rst

Checklist
This PR adds explicit checks for whether or not a build is from a pull request. It then disables uploads from pull request builds.

ENH add checks if a build is a PR

---

conda_smithy/templates/run_osx_build.sh.tmpl
news/remove_miniforge_before_build_locally.rst

Remove installed miniforge on OSX before installing it

---

conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/github-actions.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
news/allow_mambabuild_uploads.rst

Checklist
As discussed at the last core meeting
cc @mariusvniekerk

Allow uploads from mambabuild

---

conda_smithy/feedstock_content/build-locally.py
news/SDK.rst

instead of to the system dir
Checklist
cc @183amir

Download SDK to local folder when build-locally.py

---

conda_smithy/templates/github-actions.tmpl
news/gha.rst

use python 3.9 on gha and use mambaforge

---

conda_smithy/lint_recipe.py
news/mpl.rst
tests/test_lint_recipe.py

ENH add hint for matplotlib-base vs matplotlib

---

conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
news/mamba-install.rst

Since we are already using mambaforge based images we may as well use mamba in a few more places.
Checklist

Use mamba to install/update conda-build and other tools

---

conda_smithy/lint_recipe.py
news/mplbugz.rst

Checklist
Fixes linting error in https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/59

BUG error in mpl-base linting for list requirements in outputs

---

conda_smithy/configure_feedstock.py
news/ppc64le.rst

change ppc64le default provider

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/appveyor.yml.tmpl
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/github-actions.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
news/remote_ci_setup.rst

Allow users to specify which packages should be installed during ci setup

---

conda_smithy/anaconda_token_rotation.py
conda_smithy/cli.py
conda_smithy/feedstock_tokens.py
news/GHA.rst
tests/test_anaconda_token_rotation.py
tests/test_feedstock_tokens.py

add tokens to gha

---

conda_smithy/github.py
conda_smithy/templates/run_osx_build.sh.tmpl
news/macos-conda-debug.rst

Support `BUILD_WITH_CONDA_DEBUG` on macOS

---

conda_smithy/feedstock_content/.gitattributes
news/readme-generated.rst

Add .ci_support/README to generated files list

---

conda_smithy/feedstock_content/build-locally.py
news/osx_sdk_dir.rst

Clarify license agreement when setting OSX_SDK_DIR

---

news/TEMPLATE.rst

Checklist
cc @beckermr, @mfansler

Bring back news/TEMPLATE.rst

---

conda_smithy/anaconda_token_rotation.py
news/gh_actions_token.rst

Fixes https://github.com/conda-forge/conda-smithy/issues/1595

Fix rotating tokens for gha

---

conda_smithy/configure_feedstock.py
news/mpi.rst

BUG make sure MPI variant pins show up properly

---

conda_smithy/templates/README.md.tmpl

Also adding some basic information on `mamba repoquery`.

Mention mamba as a means of installing package

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/travis.yml.tmpl
news/arch.rst

Make travis-ci the default provider for aarch64 and ppc64le

---

conda_smithy/templates/azure-pipelines-win.yml.tmpl
news/vs2008.rst

Remove vs2008 support

---

conda_smithy/templates/azure-pipelines-win.yml.tmpl
news/win-miniforge.rst

Switched to using Miniforge to setup CI environment in Azure

---

conda_smithy/templates/travis.yml.tmpl
news/fix_travis.rst

Fix https://github.com/conda-forge/conda-forge.github.io/issues/1761.
Checklist

Fix argument order for Travis

---

.github/workflows/tests.yml
news/mamba.rst

PROD use mamba in CI

---

conda_smithy/feedstock_content/LICENSE.txt
conda_smithy/feedstock_content/build-locally.py
conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/github-actions.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
news/copy-license.rst

Include the recipe scripts license in the conda package

---

conda_smithy/configure_feedstock.py
news/azure-macos-11.rst

Checklist
See https://github.com/conda-forge/conda-forge.github.io/issues/1798

Bump Azure's vmImage to macos-11

---

.github/workflows/tests.yml
news/1679-fix-ci

Debug CI problems with tags and versioneer

---

.github/workflows/tests.yml
conda_smithy/cli.py
news/1678-conda-calver.rst

Remove conda SemVer checks

---

.github/workflows/tests.yml
conda_smithy/templates/automerge.yml.tmpl
conda_smithy/templates/github-actions.tmpl
news/checkoutupgrade.rst

* .github/workflows/tests.yml:
* conda_smithy/templates/automerge.yml.tmpl:
* conda_smithy/templates/github-actions.tmpl:

Upgrade actions/checkout and actions/upload-artifact to v3

---

conda_smithy.recipe/meta.yaml
conda_smithy/configure_feedstock.py
news/cph.rst

REF use cph to extract the pinnings package and account for .conda

---

conda_smithy/configure_feedstock.py
news/m2m.rst

This PR moves the default branch from master to main.
Checklist

ENH move default branch from master to main

---

.github/workflows/pre-commit.yml
.github/workflows/tests.yml
news/ci.rst
pyproject.toml

PROD moved pre-commit to separate CI and no build isolation

---

conda_smithy/cli.py
conda_smithy/feedstock_tokens.py
news/tokens-expire.rst
tests/test_feedstock_tokens.py

ENH add and handle token expiration dates

---

conda_smithy/cli.py
conda_smithy/feedstock_tokens.py
news/tokens-expire.rst
tests/test_feedstock_tokens.py

Reverts conda-forge/conda-smithy#1717

Revert "ENH add and handle token expiration dates"

---

conda_smithy/templates/create_conda_build_artifacts.bat.tmpl
news/fix-azure-win-artifacts.rst

Checklist
Fixes #1723.
Forgot to add: I tested this over at https://github.com/conda-forge/adwaita-icon-theme-feedstock/pull/18, and it does indeed fix the syntax error.

Fix syntax error when preparing conda artifacts on Azure + Windows

---

conda_smithy/configure_feedstock.py
news/no_activate.rst

Avoid needing to activate environment to use conda-smithy

---

conda_smithy/configure_feedstock.py
news/service_feedstocks.rst

Checklist
This needs some testing live to make sure it works.

ENH add service feedstocks

---

news/use_python-build_sdist.rst
rever.xsh

Checklist
Comes from https://github.com/conda-forge/conda-smithy-feedstock/pull/259#discussion_r1312426400

Use `python-build` to create `sdist`

---

conda_smithy/variant_algebra.py
news/1764-migration-additional_zip_keys.rst

Add `additional_zip_keys` for migrations

---

conda_smithy/cirun_utils.py
news/cirun.rst

Fix team names for cirun

---

conda_smithy/cli.py
news/ci_register.rst

So that we can disable all and selectively enable with --with-<ci>
Checklist

Add an --without-all option to register-ci

---

conda_smithy/cirun_utils.py
news/cirun_id.rst

Fix get_cirun_installation_id

---

environment.yml
news/pygithub.rst

update pygithub constraint

---

conda_smithy/cli.py
news/ci_register.rst

without-all for rotate-feedstock-tokens

---

README.md
news/readme_xkcd_1319.rst

Change xkcd comic to 1319

---

README.md
news/readme_xkcd_1319.rst

Follow up to PR: https://github.com/conda-forge/conda-smithy/pull/1802
Checklist

Drop leftover comic caption in README

---

conda_smithy/cirun_utils.py
conda_smithy/cli.py
environment.yml
news/cirun.rst

Supporting setting teams, roles, and users_from_json for cirun

---

conda_smithy/ci_skeleton.py
conda_smithy/feedstock_content/.gitignore
news/gitignore.rst
tests/test_ci_skeleton.py

 Update `.gitignore` to exclude everything except `recipe/` and `conda-forge.yml`

---

conda_smithy/lint_recipe.py
news/fix-lint-cb-3.28.rest

Checklist
conda_build.metadata.FIELDS["extra"] is set to an empty dict in that version.

Fix linting with conda-build=3.28.2

---

conda_smithy/feedstock_content/.gitignore
news/gitignore.rst

Revert back to old gitignore for build_artifacts

---

conda_smithy/cirun_utils.py
conda_smithy/cli.py
news/cirun-resources.rst

Send all resources at once to cirun

---

conda_smithy/feedstock_content/.gitignore
news/gitignore2.rst

Fix a typo in gitignore

---

conda_smithy/feedstock_content/build-locally.py

Correct OSX_SDK_DIR

---

conda_smithy/lint_recipe.py
news/noarch-selectors.rst
tests/recipes/noarch_selector_variants/conda_build_config.yaml
tests/recipes/noarch_selector_variants/meta.yaml
tests/test_lint_recipe.py

allow selectors containing variants from cbc in noarch recipes

---

conda_smithy/data/conda-forge.json
conda_smithy/data/conda-forge.yml
conda_smithy/schema.py
news/1871-build-id-azure.rst

Add azure: build_id to schema

---

conda_smithy/data/conda-forge.json
conda_smithy/schema.py
news/1873-bot-config-skip-render.rst

add more BotConfigSkipRenderChoices

---

conda_smithy/configure_feedstock.py
news/1872-apple-silicon-gha.rst

Use a list for labels

---

conda_smithy/data/conda-forge.json
conda_smithy/schema.py
news/1877-union-lists.rst

Checklist
Closes https://github.com/conda-forge/conda-smithy/issues/1869

allow str or list of str in `noarch_platforms` and `remote_ci_setup`

---

conda_smithy/data/conda-forge.json
conda_smithy/schema.py
news/1878-skip-render.rst

Checklist
Fixes https://github.com/conda-forge/conda-smithy/issues/1875

allow any str in `skip_render`

---

conda_smithy/data/conda-forge.json
conda_smithy/data/conda-forge.yml
conda_smithy/schema.py
conda_smithy/templates/github-actions.yml.tmpl
news/update_gha_free_space.rst

* Update `github_actions.free_disk_space` to match `azure.free_disk_space`
* Add `github_actions.free_disk_space` to schema (was missing before)
* Run `python conda_smithy/schema.py` to update associated files
<hr>
Checklist
Fixes https://github.com/conda-forge/conda-smithy/issues/1880

Refresh `github_actions.free_disk_space` and add to schema

---

conda_smithy/ci_skeleton.py
conda_smithy/configure_feedstock.py
conda_smithy/utils.py
news/jinja2-sandbox.rst
tests/conftest.py

ENH use a sandboxed env for jinja2

---

conda_smithy/lint_recipe.py
news/1925-linter.rst
tests/test_lint_recipe.py

fix overzealous linter hint for __osx

---

conda_smithy/lint_recipe.py
news/1936-lint-whl.rst
tests/test_lint_recipe.py

Lint / hint about using Python wheels as sources

---

conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
conda_smithy/templates/run_win_build.bat.tmpl
news/1947-inspect.rst

Checklist
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/310 introduces a new command based on the new `cph list` subcommand added in `conda-package-handling 2.3.0`. This adds the relevant bits in the templates to use it safely.
- You can see it in action at https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/310. That PR needs to be merged before this one.

Call `inspect_artifacts` when available

---

.github/PULL_REQUEST_TEMPLATE.md
conda_smithy/data/conda-forge.json
conda_smithy/data/conda-forge.yml
conda_smithy/schema.py
news/schema_update.rst

Checklist
I believe this is the needed change to correspond with this one: https://github.com/regro/cf-scripts/pull/2646
Here's a feedstock I maintain which is failing lint due to leveraging this feature: https://github.com/conda-forge/quarto-feedstock/pull/50

Add version update skip field to schema

---

conda_smithy/data/conda-forge.json
conda_smithy/schema.py
news/1976-version-github-releases.rst

Checklist
Comes from https://github.com/regro/cf-scripts/pull/2837

Add GithubReleases as a valid version update provider

---

conda_smithy/lint_recipe.py
news/stdlib_hint_to_lint.rst
tests/recipes/cb3_jinja2_functions/recipe/meta.yaml
tests/test_lint_recipe.py

feat: move stdlib and osx sdk hints to lints

---

conda_smithy/lint_recipe.py
conda_smithy/linter/lints.py
conda_smithy/linter/utils.py

fix: move back needed families

---

conda_smithy/templates/azure-pipelines-win.yml.tmpl
conda_smithy/templates/github-actions.yml.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
news/1986-mambaforge.rst

Checklist
Comes from https://github.com/conda-forge/miniforge/issues/602#issuecomment-2248188930
We were mixing Mambaforge and Miniforge, and they should be equivalent.

Use Miniforge everywhere

---

conda_smithy/utils.py
news/lint_build_platform.rst

Define build_platform when linting

---

conda_smithy/lint_recipe.py
conda_smithy/linter/lints.py
conda_smithy/linter/rattler_linter.py
conda_smithy/linter/utils.py
environment.yml
tests/test_lint_recipe.py

feat: add lint for recipe tests

---

conda_smithy/lint_recipe.py
conda_smithy/linter/lints.py
environment.yml
tests/test_lint_recipe.py

feat: add linting of license file

---

news/recipe-linter.rst

doc: add news item for recipe v2 linting

---

conda_smithy/linter/lints.py
news/linting.rst
tests/test_lint_recipe.py

misc: add lint for single space

---

conda_smithy/lint_recipe.py
conda_smithy/linter/lints.py
conda_smithy/linter/rattler_linter.py
news/2017-lint-jinja.rst
news/linting.rst
tests/test_lint_recipe.py

feat: add lint for jinja ref

---

conda_smithy/lint_recipe.py
conda_smithy/linter/lints.py
conda_smithy/linter/rattler_linter.py
news/2001-lint-noarch-deps.rst
tests/test_lint_recipe.py

feat: wip on noarch and runtime deps

---

conda_smithy/lint_recipe.py
conda_smithy/linter/lints.py
news/2015-rust-license-lint.rst
tests/test_lint_recipe.py

Rust license lint (builds on top of Go license lint)

---

news/linting.rst

Checklist
We missed a news item in #2003

doc: missed news item

---

conda_smithy/configure_feedstock.py
news/service.rst

fix: reenable service feedstocks

---

conda_smithy/lint_recipe.py
news/2038-sr-example.rst

fix: remove lint for changes to staged-recipes example

---

conda_smithy/lint_recipe.py
conda_smithy/utils.py
news/cfyaml-duplicate-keys.rst
tests/test_lint_recipe.py

feat: add lint for duplicate keys in conda-forge.yml

---

conda_smithy/configure_feedstock.py
news/2041-service.rst

feat: add a few more service feedstocks

---

conda_smithy/linter/hints.py
news/2046-pip-hint-exclude.rst

fix: exclude some build backends from python build backend lint/hint

---

conda_smithy/configure_feedstock.py
conda_smithy/utils.py

We have to do a few renames to make sure things are rendered correctly in the README.
Fixes: https://github.com/conda-forge/conda-smithy/issues/2065

fix: about content in readme

---

conda_smithy/cli.py
news/bug-expiry.rst

fix: bug in new expiration cli

---

conda_smithy/templates/azure-pipelines.yml.tmpl
news/2077-azure-skips.rst

Checklist
Comes from https://github.com/conda-forge/conda-smithy/pull/2076#issuecomment-2391955751.
Credit to @wshank for discovering [numpy's approach](https://github.com/numpy/numpy/pull/21879) at https://github.com/conda-forge/conda-forge.github.io/pull/2297.

Implement manual skip stage for Azure PRs

---

conda_smithy/variant_algebra.py
news/gh2083.rst

Fix multiple additional_zip_keys

---

conda_smithy/templates/azure-pipelines.yml.tmpl
news/gh2084.rst

fix whitespace

---

conda_smithy/configure_feedstock.py
news/2106-more-service-feedstocks.rst

Checklist
This PR adds more service feedstocks.

feat: add more service feedstocks

---

conda_smithy/lint_recipe.py
news/2128-add-emojis.rst

Mirror the code from
https://github.com/conda-forge/conda-forge-webservices/pull/770
Checklist

Add emojis to visually distinguish between hints and lints

---

conda_smithy/linter/conda_recipe_v1_linter.py
news/2130-fix-lint-int-version-numbers.rst
tests/test_lint_recipe.py

Checklist
* ~Regenerated schema JSON if schema altered (`python conda_smithy/schema.py`)~

fix(linter): handle integer versions

---

conda_smithy/github.py
news/noarch_create_feedstocks.rst

fix: need the path for pinning file

---

conda_smithy/linter/lints.py
news/2141-recipe-parsing-lint-hint.rst
tests/test_lint_recipe.py

Checklist
This PR adds ruamel.yaml as a valid parser for v1 recipes since they should be pure yaml.

feat: add ruamel.yaml as parser for v1

---

conda_smithy/lint_recipe.py

Checklist
* ~[ ] Added a ``news`` entry~
* ~[ ] Regenerated schema JSON if schema altered (`python conda_smithy/schema.py`)~
Per CR comments on https://github.com/conda-forge/conda-smithy/pull/2171.

feat: faster check with head request

---

conda_smithy/linter/utils.py
news/pr-2175.rst

Add poetry to VALID_PYTHON_BUILD_BACKENDS

---

.pre-commit-config.yaml
conda_smithy/azure_ci_utils.py
conda_smithy/cirun_utils.py
conda_smithy/configure_feedstock.py
conda_smithy/github.py
conda_smithy/lint_recipe.py
conda_smithy/linter/conda_recipe_v1_linter.py
conda_smithy/linter/hints.py
conda_smithy/linter/lints.py
conda_smithy/linter/utils.py
conda_smithy/schema.py
conda_smithy/utils.py
conda_smithy/validate_schema.py
conda_smithy/variant_algebra.py
news/python3.9.rst
pyproject.toml

As a follow-up to the ruff lints from https://github.com/conda-forge/conda-smithy/pull/2176 where I silenced them by setting our minimal Python to 3.8
Checklist

Update to python>=3.9

---

.github/workflows/_proxy-file-for-dependabot-tests.yml
.github/workflows/tests.yml

Reverts conda-forge/conda-smithy#2200

Revert "build(deps): bump the github-actions group in /.github/workflows with 2 updates"

---

.github/workflows/_proxy-file-for-dependabot-tests.yml
.github/workflows/tests.yml
conda_smithy/templates/github-actions.yml.tmpl

Reverts conda-forge/conda-smithy#2202

build(deps): bump the github-actions group in /.github/workflows with 2 updates

---

conda_smithy/configure_feedstock.py
conda_smithy/schema.py
news/travis-not-default-anymore.rst

Due to persistent problems with Travis, don't use it by default.
Xref https://github.com/conda-forge/conda-forge.github.io/issues/1521

switch away from defaulting to Travis CI

---

.github/workflows/tests.yml
news/crm.rst
tests/test_lint_recipe.py

fix: CRM 0.4.1 passes some tests now

---

conda_smithy/configure_feedstock.py
tests/test_configure_feedstock.py

fix up indentation error causing reduced test coverage

---

conda_smithy/linter/lints.py
news/2241-noarch-again.rst
tests/test_lint_recipe.py

fix: clarify noarch: python lint

---

conda_smithy/feedstock_content/.gitignore
news/2246-pixi-gitignore.rst

Checklist
same reasoning as in https://github.com/conda-forge/conda-smithy/pull/2222#discussion_r1920121340

Add .pixi to gitignore

---

conda_smithy/templates/build_steps.sh.tmpl
conda_smithy/templates/run_osx_build.sh.tmpl
conda_smithy/templates/run_win_build.bat.tmpl
news/2254-no-test-rattler.rst

fix: correct no testing flag for rattler-build

---

conda_smithy/templates/pixi.toml.tmpl
news/2255-pixi-toml-deterministic.rst

Make pixi.toml.tmpl deterministic

---

conda_smithy/data/conda-forge.json
conda_smithy/data/conda-forge.yml
conda_smithy/schema.py
news/2253-bot-config.rst

doc: add new schema entry for the bot static lib updates

---

conda_smithy/linter/hints.py
news/2264-dostar-specs.rst

fix: advise to add `.*` for space-separate specs

---

conda_smithy/feedstock_content/build-locally.py
conda_smithy/templates/pixi.toml.tmpl
news/2280-pixi-port-staged-recipes.rst

Checklist
- Ability to filter build-locally choices via globs in `--filter`
- Run Windows builds locally
- Add descriptions to Pixi tasks
- Run conda-smithy lint with `--conda-forge`

Bring some features from Pixi.toml and build-locally.py in staged-recipes

---

conda_smithy/linter/hints.py
news/2282-matchspec-spaces.rst
tests/test_lint_recipe.py

Checklist
Closes https://github.com/conda-forge/conda-smithy/issues/2272

Refine hints for space-separated `MatchSpec` fields

---

conda_smithy/data/conda-forge.json
conda_smithy/schema.py
conda_smithy/validate_schema.py
news/2285-fix-schema-ref.rst
tests/test_schema.py

fix(schema): $ref and properties should not be combined

---

tests/test_feedstock_tokens.py

Fix tests for token file permission validation

---

conda_smithy/linter/utils.py
news/add-uv-build.rst

Currently in preview (https://github.com/astral-sh/uv/issues/8779), but has started being used, e.g. https://github.com/conda-forge/class-resolver-feedstock/pull/3.
Checklist

Add uv-build backend

---

conda_smithy/data/conda-forge.json
conda_smithy/lint_recipe.py
conda_smithy/schema.py
news/skip-lint_stdlib.rst

Allow skipping lint_stdlib

---

conda_smithy/configure_feedstock.py
news/bool-selector.rst
tests/conftest.py
tests/recipes/py_abi3_recipe/meta.yaml
tests/recipes/py_abi3_recipe/recipe.yaml
tests/test_configure_feedstock.py

Fix bool selector dumping

---

conda_smithy/lint_recipe.py
conda_smithy/linter/lints.py
news/lint-is_abi3-bool.rst
tests/test_lint_recipe.py

feat: lint on is_abi3 as string

---

conda_smithy/configure_feedstock.py
news/selector_false.rst
tests/conftest.py
tests/recipes/py_abi3_recipe/meta.yaml
tests/recipes/py_abi3_recipe/recipe.yaml
tests/test_configure_feedstock.py

Fix dumping false into .ci_support

---

conda_smithy/lint_recipe.py
conda_smithy/linter/conda_recipe_v1_linter.py
conda_smithy/linter/lints.py
news/cargo-bundle-licenses.rst
tests/test_lint_recipe.py

No longer raise lint on cargo-bundle-licenses itself

---

news/win-pathlength.rst

add news for pathlength threshold change

---

bootstrap-obvious-ci-and-miniconda.py
conda_smithy/anaconda_token_rotation.py
conda_smithy/azure_ci_utils.py
conda_smithy/ci_register.py
conda_smithy/ci_skeleton.py
conda_smithy/cli.py
conda_smithy/configure_feedstock.py
conda_smithy/feedstock_content/build-locally.py
conda_smithy/feedstock_io.py
conda_smithy/feedstock_tokens.py
conda_smithy/feedstocks.py
conda_smithy/github.py
conda_smithy/lint_recipe.py
conda_smithy/linter/conda_recipe_v1_linter.py
conda_smithy/linter/hints.py
conda_smithy/linter/lints.py
conda_smithy/linter/utils.py
conda_smithy/schema.py
conda_smithy/variant_algebra.py
pyproject.toml
tests/conftest.py
tests/test_anaconda_token_rotation.py
tests/test_cli.py
tests/test_configure_feedstock.py
tests/test_feedstock_io.py
tests/test_feedstock_tokens.py
tests/test_lint_recipe.py
tests/test_schema.py
tests/test_utils.py

One alternative for fixing #2332, using the default linelength by black.

Use black's native linelength (Option A)

---

conda_smithy/configure_feedstock.py
conda_smithy/templates/create_conda_build_artifacts.bat.tmpl
conda_smithy/templates/github-actions.yml.tmpl
news/artefacts-on-GHA-for-win.rst

Fixes #2345 
Fix developed and tested in https://github.com/conda-forge/pytorch-cpu-feedstock/pull/395; I kept the commit history (with references) where it made sense, to provide a logical progression.

Fix artefact generation on GHA for windows

---

conda_smithy/feedstock_content/.gitattributes
news/pixi-generated.rst

mark `pixi.toml` as generated

---

conda_smithy/templates/pixi.toml.tmpl
news/2360-pixi-shellcheck.rst

Checklist
Same as https://github.com/conda-forge/staged-recipes/pull/28374

add shellcheck to Pixi's smithy feature

---

conda_smithy/configure_feedstock.py
news/unactivated-rattler.rst

Checklist
Fixes a bug in https://github.com/conda-forge/conda-smithy/pull/2359
cc @jaimergp

Allow conda-smithy to run in an unactivated environment

---

conda_smithy/templates/build_steps.sh.tmpl
news/pixi_docker.rst

use pixi installed in docker-image
