conda-forge/conda-smithy

- conda_smithy/conda_smithy.py
Steps to make a feedstock:
```
$ conda smithy init conda_smithy.recipe --feedstock-directory=../conda-smithy-feedstock
Initialized empty Git repository in /Users/pelson/dev/conda-forge/conda-smithy-feedstock/.git/
[master (root-commit) dbd083f] Initial commit of the conda-smithy feedstock.
10 files changed, 329 insertions(+)
create mode 100644 .gitignore
create mode 100644 .travis.yml
create mode 100644 README
create mode 100644 appveyor.yml
create mode 100755 ci_support/run_docker_build.sh
create mode 100755 ci_support/upload_or_check_non_existence.py
create mode 100644 circle.yml
create mode 100644 conda-forge.yml
create mode 100644 recipe/build.sh
create mode 100644 recipe/meta.yaml
$ conda smithy github-create --organization conda-forge ../conda-smithy-feedstock
Created …
```
> Fixed gh repo creation to deal with relative paths.

- requirements.txt
Self-explanatory. I thought I'd save future users a step -- unless you have a reason to want this to be an optional dependency.
> BLD: Add pygithub to requirements.txt

- conda_smithy/ci_register.py
- conda_smithy/conda_smithy.py
- conda_smithy/configure_circle_ci.py
- conda_smithy/vendored/travis_encrypt.py
- requirements.txt
When using github-create, automatically add a remote to the repo.
This does depend on gitpython - which is excellent, but a bit of a pain to install currently (we need a feedstock for it :wink:)
> Added automatic addition of a remote when creating a git repo.

- requirements.txt
- setup.py
It is:
(a) redundant (the same list exists in the conda recipe)
(b) not that useful, as you need to install via conda really (since it depends on conda anyway)
(c) harmful: it is patently incorrect with regards to the dependency on ruamel.core. https://github.com/conda-forge/conda-smithy/pull/36#issuecomment-170365818
> Remove the use of requirements.txt.

- LICENSE
- README.md
- conda_smithy/cli.py
- conda_smithy/feedstocks.py
- conda_smithy/github.py
- setup.py
Adds a new ``feedstocks`` CLI.
With this:
```
feedstocks --help
usage: feedstocks [-h] {list,list-cloned,apply-cloned,fetch} ...
positional arguments:
{list,list-cloned,apply-cloned,fetch}
list                List all of the feedstocks available on the GitHub
organization.
clone               Clone all of the feedstocks available on the GitHub
organization.
list-cloned         List all of the feedstocks which have been cloned.
apply-cloned        Apply a subprocess to all of the all feedstocks which
have been cloned.
fetch               Run git fetch on all of the cloned feedstocks.
optional arguments:
-h, --help            show this help message and exit
```
```
$ feedstocks apply-cloned -- git remote -v
```
> Added a feedstocks CLI to simplify feedstock management.

- conda_smithy/cli.py
- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
Some arbitrary common issues. Note, the linter does not currently have the scope that conda does - it doesn't ever render the recipe with Jinja. If there are good enough reasons to do so, it wouldn't be hard to achieve, though it would mean that the recipe source needs to be downloaded before it can be linted.
Closes #21.
> Added a recipe linter for common problems with recipes.

- conda_smithy/templates/appveyor.yml.tmpl
This PR removes cywing from AppVeyor at install time.  Cygwin's git breaks conda-build. (See
https://github.com/conda-forge/conda-smithy-feedstock/pull/2#issuecomment-171215989.)
PS: @pelson do we need `Obvious-CI` for feedstocks?
> Delete cygwin git

- conda_smithy/ci_register.py
I just saw staged-recipes fail due to this time being exceeded. Let's be generous to TravisCI and allow it to synch.
> Extended the time for TravisCI to refresh.

- .travis.yml
- conda_smithy/ci_register.py
- conda_smithy/tests/test_encrypt.py
- setup.py
Fixes a couple issues I had with me first run through
- importing a vendored module failed
- travis encryption failed since the cryptographic routine expected bytes and got a unicode string (in py3)
I tried adding tests, but this is a bit tricky of a library to test since it's doing so much IO. Happy to adjust those as needed.
I'm not entirely sure I didn't break anything with this changes. For example, my [appveyor build](https://ci.appveyor.com/project/tomaugspurger/statsmodels-feedstock/build/job/scs99a28d0f78cld) failed to upload to my [Anaconda](https://anaconda.org/taugspurger/statsmodels/files) account since it didn't find a binstar token. That's likely unrelated though.
Thanks for the project btw. I'm hoping to setup statsmodels with it so they always have development versions …
> COMPAT: import and str vs bytes

- conda_smithy.recipe/meta.yaml
Basically borrowed from the `setup.py` file.
Sorry, I couldn't help myself. Mainly I was bothered by the undetermined license badge on Anaconda. :fearful:
[![Anaconda-Server Badge](https://anaconda.org/conda-forge/conda-smithy/badges/license.svg)](https://anaconda.org/conda-forge/conda-smithy)
> Add `about` section to the recipe

- conda_smithy/templates/run_docker_build.tmpl
Closes #72 
I need this for feedstocks that require the latest conda-build (like `hdfeos2` and `hdfeos5`).
> Update all on CircleCI tmpl

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
Raises an error when the license is 'unknown'. The motivation is to avoid pushing recipes with conda's skeleton default 'unknown' string.
> Check for unknown license.

- conda_smithy/configure_feedstock.py
In order to speed up CIs and avoid long queues, we decided to remove CI files if the package was not configured. While this is a great system and definitely helps, it increases the barrier (slightly) to adding back support. Namely, we need to add this file back. This could be intimidating to a new user or someone just trying to get something working quickly. For instance, they might worry that portions of these files are unique to each feedstock.
This proposal suggests that instead of deleting these files entirely, we just rename them. That way the file remains around and CI remains disabled. However, if we want to try quickly to re-enable this functionality we simply move the file back.
> Keep disabled CI (AppVeyor) configuration files around

- conda_smithy/ci_register.py
Hopefully this will solve https://github.com/conda-forge/staged-recipes/issues/221
Ping @jakirkham
> AppVeyor API URL

- conda_smithy/ci_register.py
Fixes the issue found by https://github.com/conda-forge/django-grappelli-feedstock/issues/1.
MNT PRs will have to go out to each of the affected feedstocks.
> Fixed writing of hex encoded AppVeyor secret on py3.

- conda_smithy/configure_feedstock.py
Slightly more controversial this PR. Ping @conda-forge/core as a heads up - this will impact the build matrix of every single feedstock. We will no longer be building py3.4, nor numpy 1.9.
Whilst I appreciate similar arguments can be made for legacy python (2.7), let's not go down that road here - we want conda-forge to be as useful as reasonably possible without the huge burden of carrying around unnecessary versions. :wink:
> Moved ahead with numpy and python versions.

- conda_smithy/templates/travis.yml.tmpl
Remove all homebrew Software that is pre-installed in the Travis-CI OS X image.
PS: I wonder what sort of issues we will find once we start re-building everything without the software from homebrew.
> Remove homebrew

- conda_smithy/ci_register.py
Closes https://github.com/conda-forge/staged-recipes/issues/267
> Fix AppVeyor project URL

- conda_smithy/templates/travis.yml.tmpl
Mac doesn't come with `wget`. This was supplied through `brew`. As we have uninstalled everything from `brew`, we can't use `wget` any more.
Fortunately, Mac does come with `curl`. The syntax is only slightly different, but we get exactly the same effect. Once Miniconda is installed we can install anything we are willing to build so it is smooth sailing from here on out. :sailboat:
> Use `curl` on Mac (Travis CI)

- conda_smithy/templates/README.md.tmpl
Even though the license file is right there, this felt a little unclear to me so I specified the BSD license version in the feedstock README. Also, felt a little bad having others specify this while we have this glaring omission. So, this should ease our collective conscience. :smile:
> Specify the type of BSD License as 3-Clause for feedstocks

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
Not sure we need the `__getattr__` too, but I thought it does not hurt. The test is a simple CLI with `environ` defined for tests like we have in some of the recipes.
Closes #142
> Fixes #142

- conda_smithy/templates/travis.yml.tmpl
It appears that conda-build 1.20.1 introduced a bug when trying to fix shebangs as explained in this issue ( https://github.com/conda/conda-build/issues/889 ). We are applying this change as part of the pinning fixes in this feedstock ( https://github.com/conda-forge/vigra-feedstock/pull/4 ).
> Pin conda-build to 1.20.0

- conda_smithy/templates/appveyor.yml.tmpl
Add workaround for this issue ( https://github.com/conda/conda-build/issues/895 ). Related change in staged-recipes ( https://github.com/conda-forge/staged-recipes/pull/452 ). Related issue ( https://github.com/conda-forge/staged-recipes/issues/448 ).
Applies this workaround only to Python 3.4 64-bit where the issues were seen. This way Python 2.7 64-bit on Windows still benefits from the nice fixes from @patricksnape and @msarahan.
> Workaround Python 3.4 64-bit failure on AppVeyor

- conda_smithy/templates/travis.yml.tmpl
Even after removing Homebrew packages, the tarballs remain afterwards. These use up memory on the CI, which could be used for other things like intensive compilation. Here we make sure all remnants of these are deleted. The whole process is pretty quick. Similar change is proposed for `staged-recipes` in this PR ( https://github.com/conda-forge/staged-recipes/pull/468 ).
> Clear Homebrew packages after removal

- conda_smithy/ci_register.py
I got sick of the unpredictable response, and wouldn't be surprised if it was because we have too many repos for the API to handle. This PR removes the check before asking to follow a repo, and just *always* follows the repo instead (same effect, less data transferred).
> Remove the check, and just always register with CircleCI.

- conda_smithy/templates/run_docker_build.tmpl
After some [discussion]( https://github.com/conda-forge/staged-recipes/pull/524/files/fb5563b6fd1c9b80b964200ea12b5bd6039b9a62#r61819818 ), we have decided we can drop the pinning to `conda-build` that was originally added in this PR ( https://github.com/conda-forge/conda-smithy/pull/100 ). So, that is what we are doing here.
> Unpin `conda-build` on Circle CI builds

- conda_smithy/configure_feedstock.py
- conda_smithy/feedstock_content/circle.yml
Switches from `pelson/obvious-ci:latest_x64` to `condaforge/obvious-ci`. The source for this image is now maintained in this repo ( https://github.com/conda-forge/docker-images ). It is exactly the same source from before it is just moving to the org. In fact, the source was moved over in this PR ( https://github.com/conda-forge/docker-images/pull/5 ). Similar change proposed to staged-recipes in this PR ( https://github.com/conda-forge/staged-recipes/pull/514 ).
> Switches to the org image

- conda_smithy/configure_feedstock.py
This PR enables the ```recipe/yum_requirements.txt``` capability. Crucially, unlike #135 it puts the yum requirements explicitly into the ```run_docker_build.sh``` at ```conda smithy rerender``` time, rather than inspecting the ```yum_requirements.txt``` at *build* time.
-----------
The following content is out of date:
With this change, one can add the following to a conda-forge.yml and expect their build script to add appropriate yum build dependencies:
```
+++ b/conda-forge.yml
@@ -4,3 +4,6 @@
+  extra-yum-pkgs:
+    - mesa-libGL-devel
```
There is no guarantee that this is a usable build unless the package is installed on a user's machine also,  so this capability should be used *exceptionally* scarcely.
> Added the ability to add extra yum deps to the feedstock.

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
Not planning to cut a release immediately after merging - we can live without this for a few days.
> BUG: Gave the jinja rendering in the linter the os namespace.

- conda_smithy/templates/appveyor.yml.tmpl
Up to now the conda-forge channel was hardcoded...
Fixes: https://github.com/conda-forge/conda-smithy/issues/178
> Honor channels -> sources in appveyor

- conda_smithy/ci_register.py
Fixes the problem noticed in https://github.com/conda-forge/conda-smithy/pull/177
> Fix missing newline in anaconda auth example

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/README.md.tmpl
before they hardcoded both the conda-forge github or and the name of the repo to *-feedstock. Now this is overwriteable
by setting a conda-forge.yml setting:
github:
user_or_org: github-username
repo_name: github-repo-name
closes: https://github.com/conda-forge/conda-smithy/issues/180
> Make the badge URLs configureable

- conda_smithy/templates/README.md.tmpl
Not something I want to do frequently, but in order to avoid PRs for each and every feedstock which fixes just one character, I will re-introduce this whitespace for the v0.10.4 release and revert for the v1.0.
> Reintroduce whitespace into README.

- conda_smithy/ci_register.py
So, the `User-Agent` was added to the Travis CI request header in this PR ( https://github.com/conda-forge/conda-smithy/pull/36 ). Not quite sure why this particular `User-Agent` was chosen. Maybe it was just copied from the example in the [Travis CI docs]( https://docs.travis-ci.com/api#with-a-github-token )? Unfortunately Travis CI's docs are mum on this AFAICT. Though they do drop the pearl of wisdom below. Maybe we have to login with the bot periodically? Yuck, but if that helps it should be pretty easy to do.
> Note that therefore the API cannot be used to create new user accounts. The user will have to log in at least once via the web interface before interfacing with the API by other means.
While this seemed to work fine for awhile, it now is causing us grief when trying to …
> Change "User-Agent" in Travis CI header

- conda_smithy/configure_feedstock.py
This is the second part of the resolution for issue ( https://github.com/conda-forge/conda-smithy/issues/205 ). Basically this does the same thing as PR ( https://github.com/conda-forge/conda-smithy/pull/94 ), which is rename `.travis.yml` to `.disabled_travis.yml` when there is no need to run Travis CI. As long as Travis CI is configured to not run when `.travis.yml` is missing, as is done by PR ( https://github.com/conda-forge/conda-smithy/pull/206 ), then this will disable running Travis CI.
> Disable Travis CI

- conda_smithy/templates/appveyor.yml.tmpl
- conda_smithy/templates/run_docker_build.tmpl
- conda_smithy/templates/travis.yml.tmpl
Related https://github.com/conda-forge/staged-recipes/pull/705
Installs `conda-forge-build-setup` and uses the script `run_conda_forge_build_setup` to configure the CIs appropriately for each VM. This is basically the same as what is being done in `staged-recipes` via this PR ( https://github.com/conda-forge/staged-recipes/pull/705 ).
This could use a good careful review.
cc @pelson @ocefpaf
> Start using `conda-forge-build-setup` to do CI configuration

- conda_smithy/configure_feedstock.py
This initially seemed like a good idea. Honestly though it feels a bit half-baked in retrospect and doesn't server a very useful purpose. So this reverts PR ( https://github.com/conda-forge/conda-smithy/pull/94 ) to clean out some unnecessary stuff.
> Drop `disabled_appveyor.yml`

- conda_smithy/ci_register.py
- conda_smithy/cli.py
Fixes https://github.com/conda-forge/conda-smithy/issues/205
This is the first (though last to be merged) part to address issue ( https://github.com/conda-forge/conda-smithy/issues/205 ). This provides a way to enable the button on Travis CI so that commits are not built if they don't have a `.travis.yml` file. The file removal portion was handled in PR ( https://github.com/conda-forge/conda-smithy/pull/207 ).
> Configure Travis CI

- conda_smithy/ci_register.py
Looks like this may help fix our Travis CI issues. Tested on a large scale locally. Let me explain some history first.
When this first started occurring, @isuruf noted this issue ( https://github.com/travis-ci/travis-ci/issues/5649 ). Based on the changes by others and the discussion in the issue itself, it seemed the takeaway message was that one had to specify a `User-Agent`. We already had one, but we thought we might need to change it. So, we tried PR ( https://github.com/conda-forge/conda-smithy/pull/204 ). While that was not yet put into production, we did test the `User-Agent` in PR ( https://github.com/conda-forge/conda-smithy/pull/206 ) and found it made no difference there. At the time there had been some serious Travis CI issues, so it made sense to @pelson and I to chalk it up …
> Specify Travis CI content type as JSON

- conda_smithy/templates/appveyor.yml.tmpl
This changes to running the activate script on AppVeyor to properly activate the conda `root` environment. Basically lifted from this PR ( https://github.com/bollwyvl/nb_conda_kernels-feedstock/pull/1 ) by @msarahan. Similar change proposed for `staged-recipes` in PR (https://github.com/conda-forge/staged-recipes/pull/982 ). @msarahan, could you please double check that this is done correctly?
> WIP: Activate conda environment on AppVeyor

- conda_smithy/templates/README.md.tmpl
Corrects `pacakge` -> `package`.
> Fixes a typo in the README template

- conda_smithy/ci_register.py
- conda_smithy/vendored/travis_encrypt.py
Tidies up some unnecessary std out, and uses appropriate headers when requesting the public key with the Travis API.
> Correctly set the headers for *all* Travis requests.

- conda_smithy/templates/README.md.tmpl
This follows-on from PR ( https://github.com/conda-forge/conda-smithy/pull/227 ). We were trying to pickup the `description` from `extra` previously. Though I believe we wanted to pick this up from `about`. Feel free to correct me if I'm misunderstanding something.
> Fix `description` addition to the README template

- conda_smithy/configure_feedstock.py
Follow-up on PR ( https://github.com/conda-forge/conda-smithy/pull/210 ). This deletes `disabled_appveyor.yml` if present. Tested locally.
> Delete `disabled_appveyor.yml` if present

- conda_smithy/templates/circle.yml.tmpl
If a recipe does not build on Linux, we made a changed to the `circle.yml` so that CircleCI does not build the feedstock. This was done in PR ( https://github.com/conda-forge/conda-smithy/pull/218 ). It was demonstrated to work correctly in some test cases. Also this has worked largely for CircleCI builds encountered thus far.
However, today I noticed a [build failure]( https://circleci.com/gh/conda-forge/anypytools-feedstock/1 ) for the [anypytools-feedstock]( https://github.com/conda-forge/anypytools-feedstock ) even though that feedstock should only build on AppVeyor. To see if something was systemically going wrong, I added PR ( https://github.com/conda-forge/anypytools-feedstock/pull/1 ), which appeared to do the right thing and generate a [skipped build]( …
> Fast finish fallback if CircleCI skip fails

- conda_smithy/templates/README.md.tmpl
Mostly to clarify the implications of pushing branches to the main feedstock repository, which immediately deploy built packages (in contrast to PRs from forks).
> try to improve README.md template a bit

- conda_smithy/templates/README.md.tmpl
Changes the CircleCI badge to look a bit more like the other CI badges by using the shield style.
For an example, re-rendered the [rank_filter feedstock]( https://github.com/conda-forge/rank_filter-feedstock ) in PR ( https://github.com/conda-forge/rank_filter-feedstock/pull/10 ). See an example of the new CircleCI badge in this [README]( https://github.com/conda-forge/rank_filter-feedstock/blob/00420a91da28f2435f3b8bfa17855c68789a4aa2/README.md#current-build-status ).
> Use shield style CircleCI badge

- conda_smithy/configure_feedstock.py
- conda_smithy/feedstock_content/ci_support/disabled.svg
- conda_smithy/templates/README.md.tmpl
Fixes https://github.com/conda-forge/conda-smithy/issues/119
This places a disabled CI badge in place of any CI that is not operational. It also removes any link to that CI. As soon as the `skip` condition in the `meta.yaml` changes and the recipe is re-rendered, the badge will change back to the CI status and properly link to it. This basically works and is ready to go. Here is an [example]( https://github.com/conda-forge/inkscape-feedstock/blob/fde93d04d76b09ae135314752ed82885ad1c54cd/README.md ).
cc @ocefpaf @pelson @janschulz
> Disabled CI badge

- conda_smithy/templates/circle.yml.tmpl
As per the discussion in https://github.com/conda-forge/conda-smithy/pull/242/files/8bdc89c7284fa19f6a8d71fc1674123bfff7e0a7#r73888812
> More info why circle ci could be skipped

- conda_smithy/templates/travis.yml.tmpl
Sets OS X on Travis CI explicitly. Uses a generic VM otherwise.
See PR ( https://github.com/conda-forge/libgfortran-feedstock/pull/5 ) for a test of this re-rendering.
> Set OS on Travis CI

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
As the title says - this simple PR makes sure the linter can parse files with unicode under Python 2.7 (it did already work before that on Python 3.5). I did not test the full chain up to sending the reports to Github - only that the linter no longer raises if it encounters a file with non-ASCII chars.
I've already hit this bug twice using conda-forge and I hope this alleviates it a bit.
> Unicode no longer raises within the linter + test

- conda_smithy/templates/README.md.tmpl
Broken out from PR ( https://github.com/conda-forge/conda-smithy/pull/250 ). Basically tries to make the disable badge link easier to update. Hoping this is an easy win no matter what we change the location to.
> Refactor disabled badge jinja

- conda_smithy/templates/README.md.tmpl
Another tweak to how we handle AppVeyor badges following PR ( https://github.com/conda-forge/conda-smithy/pull/195 ).
Appears that AppVeyor made a change to how they handle the badge icon (not the link). In particular, they now want to keep underscores ( `_` ) in the icon if they can. See PR ( https://github.com/conda-forge/line_profiler-feedstock/pull/2 ) for an example of this problem or any feedstock building on AppVeyor that has an underscore. So this is a tweak to handle that problem.
Examples of this re-rendering can be seen in the PRs below.
* https://github.com/conda-forge/line_profiler-feedstock/pull/4
* https://github.com/conda-forge/pyomo.extras-feedstock/pull/10 (no-op as expected)
* https://github.com/conda-forge/thredds_crawler-feedstock/pull/8
Used the commit immediately …
> Fix AppVeyor badge again

- conda_smithy.recipe/meta.yaml
- conda_smithy/configure_feedstock.py
- conda_smithy/tests/test_configure_feedstock.py
- requirements.txt
Fixes a bug with index fetching (https://github.com/SciTools/conda-build-all/issues/49).
> Updated dependency to >=1.21.12 for conda-build

- conda_smithy/tests/test_configure_feedstock.py
> Added a name for the Linux case in conda_smithy.tests.test_configure_feedstock.Test_fudge_subdir.

- conda_smithy/templates/travis.yml.tmpl
Fixes https://github.com/conda-forge/conda-smithy/issues/267
Previously if an upload failed on Travis CI, the build still passed. This is because [`after_success`]( https://github.com/conda-forge/conda-smithy/blob/3f49bcea082d55b638f36bef2435b30ff6259c67/conda_smithy/templates/travis.yml.tmpl#L57-L60 ) simply [ignores any exit code]( https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build ) (even non-zero ones). As a result, it wouldn't be obvious that an upload failed or that one should check at all. Moving the upload section into the `script` section should at least ensure that if the upload fails the exit status will be respected and thus fail the build. As a result, users should be able to see this failure clearly.
> Error out on Travis upload failure

- conda_smithy/configure_feedstock.py
- conda_smithy/tests/test_configure_feedstock.py
Same story here as conda-build-all.  Changes are pretty minor, and strictly to account for the non-global config.
I'm intentionally not setting up Travis here to use the canary channel, since it's hung on the conda-build-all PR.  This PR will be failing until we get that issue sorted out, or until conda-build sees a general release.
> adjust fudge_subdir for non-global config in conda-build 2

- .travis.yml
- conda_smithy/configure_feedstock.py
- conda_smithy/tests/test_configure_feedstock.py
> Updated conda-build 2 support so that we pass around configuration objects, rather than metas.

- conda_smithy/tests/test_configure_feedstock.py
We want the underscore before not after as the first argument is the [suffix]( https://docs.python.org/2/library/tempfile.html#tempfile.mkdtemp ).
> TST: Rename temporary recipe directory

- .travis.yml
We don't actually care what VM we get from Travis CI or what comes with it as we install Miniconda and use its Python and assorted packages for constructing a testing environment. As a result, it would be better if we use one of the "cheap" Travis VM images to start as we don't care what comes with it. Here we propose using the `generic` image, which we have used successfully in a lot of other cases. Also it has very fast boot times. This should be helpful for iterating quickly on proposed changes.
> Test with generic Travis VM

- .travis.yml
Workaround for issue ( https://github.com/conda-forge/conda-smithy/issues/289 ).
This temporarily pins `setuptools` to a known working version. The underlying problem is going to take a bit to get sorted out and resolved. In the meantime, this should at least ensure CI is working here again until it gets fixed.
cc @msarahan
> Pin `setuptools` as CI failure workaround

- conda_smithy/feedstocks.py
Listing available feedstocks on a given GitHub organisation was not working because the specified argument did not exist. I've corrected the specified argument so that it gets the requested organization from the incoming `args`. I've also updated the help string to make reference to the fact that you can specifiy a GitHub organization using the `--organization` flag.
> Correct arg used to list feedstocks

- README.md
Adds the long awaited simple directions for re-rendering a feedstock. This should hopefully make it easier to explain to people what is required if they need to do it themselves.
cc @conda-forge/core
> Re-render directions

- .travis.yml
- conda_smithy/templates/travis.yml.tmpl
Seems we are just monkeying with the path in our CI testing here and in the feedstocks when using Travis CI. This changes both to properly activate the `root` environment instead.
Example re-rendering on a feedstock: https://github.com/conda-forge/libgfortran-feedstock/pull/7
> Activate `conda`'s `root` environment on Travis

- conda_smithy/cli.py
copy/paste-able commit message for rerender, including conda-smithy version
If `commit -am` is undesirable, I still think it would be useful to report the conda-smithy version at the end of rerender.
> Include commit command in rerender output

- conda_smithy/templates/circle.yml.tmpl
Unlike other CIs, CircleCI does not test the merge commit of a PR with its base branch. Instead it tests the PR's head commit. The problem with this is the PR's status could differ when it is merged with the base branch. For instance, if one needs changes in the base branch to get their PR to pass, they must rebase/merge to get them into the history the PR. This normally isn't a problem, but sometimes things do go wrong when doing this merge/rebase, which adds a new unneeded difficulty. Alternatively, a passing PR could turn out to fail when merged into the base branch because some new content in the base branch was not tested against in the PR.
To solve these issues, we checkout the merge ref for a PR (if it is a PR) from GitHub. However, it should be noted that the merge ref can be …
> Test CircleCI PR merge commits

- conda_smithy/configure_feedstock.py
Partially a follow-up on PR ( https://github.com/conda-forge/conda-smithy/pull/301 ) to clean `upload_or_check_non_existence.py` from feedstocks. Based heavily on this [commit]( https://github.com/conda-forge/conda-smithy/pull/193/commits/3e46d10c195cc127b0698a2e8090cefacb2f37ac ).
* Standardize cleanup of old files since dropped from feedstocks.
* Handle `disabled_appveyor.yml` cleanup in the same fashion.
* Handle removal of `upload_or_check_non_existence.py`.
cc @pelson
> Handle dropping old files from feedstocks

- conda_smithy/cli.py
Tweaks the post-rerendering message added in PR ( https://github.com/conda-forge/conda-smithy/pull/307 ). Suggests running `git add -A` and then committing after. This way we pick up newly added untracked files.
cc @minrk @pelson
> Tweak re-render commit info

- conda_smithy/configure_feedstock.py
- conda_smithy/feedstock_content/ci_support/checkout_merge_commit.sh
- conda_smithy/templates/circle.yml.tmpl
This makes some improvements on PR ( https://github.com/conda-forge/conda-smithy/pull/293 ) w.r.t. how we get PR refs. The main tweak is to make sure there is one `git fetch` step for all the refs so that they won't be out of sync. Other than that there is some minor stylistic improvements by putting the code in one block.
Based on updates to PR ( https://github.com/conda-forge/staged-recipes/pull/1486 ).
Edit: Testing in PR ( https://github.com/conda-forge/freeglut-feedstock/pull/6 ).
> Update CircleCI merge PRs

- conda_smithy/feedstock_content/ci_support/checkout_merge_commit.sh
Apparently left in an extra checkout command. :facepalm: This drops it out.
> Drop extra PR merge ref checkout on CircleCI

- conda_smithy/configure_feedstock.py
Adds the `-feedstock` suffix if it is missing for re-rendering. This will make this work nicely on the feedstocks repo, but allows PR ( https://github.com/conda-forge/conda-smithy/pull/320 ) to do what it intended to do as well.
xref: https://github.com/conda-forge/conda-smithy/issues/319#issuecomment-250877367
> Handle missing `-feedstock` suffix during re-rendering

- conda_smithy/templates/travis.yml.tmpl
@conda-forge/core, this is **urgent**!
This sets the base Travis CI image so it requires OS X 10.9/XCode 6.1 explicitly as the Travis CI default changed appears to have changed to OS X 10.11/XCode 7.3. Please see [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/164921320#L4 ), which appears to be the last build on `master` using OS X 10.9/XCode 6.1. Note that the next [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/165091878#L4 ) and every subsequent build now appears to be using OS X 10.11/XCode 7.3 by default.
A similar change has been proposed to `staged-recipes` in PR ( https://github.com/conda-forge/staged-recipes/pull/1716 ). Once that change checks out this should be merged and released ASAP.
> Require OS X 10.9/XCode 6.1

- conda_smithy/templates/appveyor.yml.tmpl
Required to address issue ( https://github.com/conda-forge/conda-forge.github.io/issues/252 ).
Adds a hack to update `conda` on AppVeyor to a version that can handle a long path issue before activation. Please see PR ( https://github.com/conda/conda/pull/3349 ) for details about the fix.
Testing in PR ( https://github.com/conda-forge/conda-feedstock/pull/9 ).
cc @msarahan
> Update `conda` on AppVeyor before activation

- conda_smithy/cli.py
- conda_smithy/configure_feedstock.py
Adds executable permissions to `ci_support/checkout_merge_commit.sh` in a few places. It should have them anyways because the file already has executable permissions. However, there are some oddities on Windows that need to be addressed.
Also makes sure executable permissions are added for everyone, group, and user on both `ci_support/checkout_merge_commit.sh` and `ci_support/run_docker_build.sh`. We were just adding executable permissions for the user before however it seems `os.chmod` conferred them to group and everyone anyways. This appears to be inadvertent AFAICT. So we now do explicitly in this PR.
> Fix permissions

- conda_smithy/cli.py
- conda_smithy/configure_feedstock.py
- conda_smithy/feedstock_io.py
This automatically stages changes from a re-rendering run in the index if the feedstock is a git repo. If it is not a git repo, it proceeds exactly the same as it would otherwise. By putting things directly into the index, we should be able to avoid file permission getting lost like in issue ( https://github.com/conda-forge/conda-smithy/issues/330 ).
Also provides the option to commit either with the editor popped up or automatically with a default message. Note that committing is not default behavior unlike staging.
> Stage re-rendering changes

- conda_smithy/feedstock_io.py
Fix a subtle issue with handling a generator on Python 3. Namely `generators` do not have a `next` method.
xref: https://github.com/conda-forge/conda-smithy/pull/336
> Fix generator issue on Python 3

- conda_smithy/cli.py
A stray `'` snuck into PR ( https://github.com/conda-forge/conda-smithy/pull/336 ). This removes it.
> Remove a stray `'`

- conda_smithy/cli.py
Make some adjustments to the re-rendering output message spacing. In particular, try to make sure things don't get clumped in with the `git commit` output.
xref: https://github.com/conda-forge/conda-smithy/pull/336
> Adjust re-rendering message

- conda_smithy/templates/travis.yml.tmpl
and get miniconda via https
http fetch of miniconda now redirects to https. Without `-L`, this results in mac builds failing to fetch miniconda.
cf https://travis-ci.org/conda-forge/metis-feedstock/builds/171745621
> follow redirects with curl

- conda_smithy/feedstock_io.py
In some cases a file may already be removed from the file system. However, the corresponding change may not have been added to the index. We were not able to handle this case previously as GitPython is unable to remove the file from the index if it is not already on the file system.
So we had to check that the file was on the file system first before trying to remove it from the index. The result being a file removed from the file system and not removed from the index could linger in the subsequent commit even if it should have been removed. This issue could crop up if someone tried to re-render the feedstock (resulting in some files being removed). Then backed out the changes from the index with `git reset` for some reason.
To solve this issue, this change creates an empty file on the …
> Handle a subtle case involving file removal during re-rendering

- conda_smithy/templates/appveyor.yml.tmpl
Adjust the vendored bootstrap URL to be a permalink by including the commit sha ( e976c7e84bb3c4846e7562afd1a42c4b535b51f5 ). This way if we decide to move or remove it in the future, we don't have to worry about the impact on feedstocks that are using the current location.
> Permalink to vendored bootstrap URL

- conda_smithy.recipe/meta.yaml
Changes the included development recipe to use `conda-build` entry points.
> Use conda-build entry points

- conda_smithy/feedstock_io.py
Fixes https://github.com/conda-forge/conda-smithy/issues/314
Improves on https://github.com/conda-forge/conda-smithy/pull/345
This handles two cases. First it handles a case where one tries to write to a file when its parent directory does not exist. Second it handles the case where the last file in a directory is removed leaving empty directory/directories.
The first case is handled by making all directories up to the parent directory of the file recursively until they all exist. This is of particular importance for `remove_file`, which runs `touch_file` before removal to ensure the file exists. More details about why that is done can be found in PR ( https://github.com/conda-forge/conda-smithy/pull/345 ). As a result, we can be sure the file can be written to whether or not those …
> Handle empty directories

- conda_smithy/feedstock_io.py
Use `BlobFilter` in `get_file_blob` to match the filename. This seems more robust based on local testing than our previous attempts. It should also be easier to maintain.
> Use `BlobFilter` in `get_file_blob`

- conda_smithy/configure_feedstock.py
- conda_smithy/feedstock_io.py
Fixes https://github.com/conda-forge/conda-smithy/issues/364
This uses UTF-8 in all cases. Files are opened with UTF-8 encoding and unicode literals are used throughout. Fixes some issues on Python 2 in particular where metadata from the recipe included unicode characters. This should now correctly support them. Have tested against the [`pyemma` feedstock]( https://github.com/conda-forge/pyemma-feedstock ) with both Python 2 and Python 3 locally. Works fine in both cases. Should add that this ends up already being well covered in the existing test suite thanks to the use of the `touch_file` function, which had to receive a unicode literal to behave correctly.
> Use unicode on Python 2

- .coveragerc
- .gitignore
- .travis.yml
- README.md
Measure and report test coverage during CI builds. Also send the statistics to Coveralls for nicer reporting.
> Measure and report test coverage

- conda_smithy/tests/test_feedstock_io.py
This is a follow-up on PR ( https://github.com/conda-forge/conda-smithy/pull/336 ).
Adds a bunch of tests for the `feedstock_io` module. Tests exist for both the presence and absence of a git repo. The combination of these should help improve test coverage of `conda-smithy` particularly on these low level aspects.
cc @nicoddemus
> Tests for feedstock_io

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
Have the linter raise if the `license` includes the word "license" in it.
cc @goanpeca
> Lint Redundant License

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
conda-build actually checks for that. Relates to #88.
> Linter: check the license_family is valid

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
Changes the linter to use unicode always even on Python 2. Expect this should get rid of some occasional bad behavior with unicode characters not being handled correctly.
> Unicode linter

- conda_smithy.recipe/meta.yaml
- requirements.txt
Exclude `conda-build` version `2.0.9` as it breaks compatibility with `conda` version `4.1`.
> Exclude `conda-build` version `2.0.9`

- conda_smithy/feedstock_content/.gitattributes
Adds a `.gitattributes` file for specifying how to handle line endings with recipe content.
cc @goanpeca
xref: https://github.com/conda-forge/staged-recipes/pull/1920
> Add gitattributes

- conda_smithy/templates/appveyor.yml.tmpl
Closes https://github.com/conda-forge/conda-smithy/pull/349
Drops some defaults from `appveyor.yml` that should not be needed any more. In particular, `CONDA_PY` and `CONDA_INSTALL_LOCN`. These should already always be configured thanks to PR ( https://github.com/conda-forge/conda-smithy/pull/370 ).
> Cleanup redundant info in `appveyor.yml`

- conda_smithy/cli.py
So I pointed out in #374 that while re-rendered feedstock commits show the version number, the initial commit does not, but we should to help maintainers more easily determine if their feedstock is out of date when no other re-renderings have been done yet.
> Put conda-smithy version in first feedstock commit

- conda_smithy/templates/README.md.tmpl
When checking if packages are available in `conda-forge`, I often look in https://conda-forge.github.io/feedstocks.html and if positive, click on the link. That lands in the feedstock page, and often I also need to check the version, in which case I have to scroll all the way down to see the version badges.
Also I check the badges of feedstocks I maintain to see if all builds passed after merging a PR to update the version as sometimes CI might fail on `master` for flaky reasons even if the builds passed during the PR.
I was going to open an issue and propose to write a PR if the response was positive, figured out easier to just open the PR and discuss it here.
> Move build status and version info badges near the top of the README

- .travis.yml
Temporarily pins `conda` to version `4.1.x` in CIs. This should workaround the testing failure until we have a better solution.
> Pin `conda` to `4.1.x`

- conda_smithy/configure_feedstock.py
This is done as it is used by the Obvious-CI compiler activation script for AppVeyor ( `obvci_appveyor_python_build_env.cmd` ). That script expects to get `TARGET_ARCH` and `CONDA_PY`. We already do a good job of setting `TARGET_ARCH` in the environment matrix. However, there was one case where `CONDA_PY` was not set. Namely if `python` was not a build dependency. Here we fix that to restore the old behavior of using Python 2.7 as the default, but we do this in the matrix to make it a bit clearer what it is we are doing.
> Set CONDA_PY on AppVeyor (if undefined)

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/appveyor.yml.tmpl
- conda_smithy/templates/run_docker_build.tmpl
- conda_smithy/templates/travis.yml.tmpl
Fixes https://github.com/conda-forge/conda-smithy/issues/284
Provides a way to bootstrap `conda-forge-build-setup`. Also provides the ability for feedstocks to override their configurations manually at a local level if needed. This should hopefully give everyone a little bit of what they want while addressing a notable issue.
Testing of this can be seen in PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/30 ).
**TODO:**
> Provide setup overrides

- conda_smithy/templates/run_docker_build.tmpl
Wraps shell variables with double-quotes to accommodate paths with spaces. Follows up on the conversation [here](https://github.com/conda-forge/conda-forge.github.io/pull/288#issuecomment-267048286).
> Fix shell variable expansion: RECIPE_ROOT and FEEDSTOCK_ROOT

- conda_smithy/templates/appveyor.yml.tmpl
- conda_smithy/templates/run_docker_build.tmpl
- conda_smithy/templates/travis.yml.tmpl
Appears the source channel order in AppVeyor and Travis CI config files was backwards. This reverses them to get the channels in the right priority order. Namely channels showing up first in `channels/sources` have highest priority and those showing up last in `channels/sources` have lowest priority. Also the CircleCI docker build was sorting the channels instead of preserving the order. This also drops that sort.
> Fix source channel order in CIs

- conda_smithy/templates/appveyor.yml.tmpl
Closes https://github.com/conda-forge/setuptools-feedstock/pull/47
Some of the changes included in here install a very particular version of `conda`. This was needed to fix some path manipulation bugs. ( https://github.com/conda-forge/conda-smithy/pull/329 ) Since then newer version have been released that we use successfully. So it makes sense to remove the pinning. However, the update is still needed as AppVeyor's included `conda` is so old.
Also we found ourselves in a situation where Python 2.7 jobs where running out of memory with particular configurations of the root environment when running `conda-forge-build-setup`. ( https://github.com/conda-forge/conda-smithy/issues/351 ) Some hacks were added to adjust the `root` environment to fix this. ( …
> Tidy up AppVeyor conda update

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/appveyor.yml.tmpl
- conda_smithy/templates/run_docker_build.tmpl
- conda_smithy/templates/travis.yml.tmpl
This adds `defaults` to the default set of channel sources for the feedstock. Also it makes sure that `defaults` does not get included in the CI unless it is explicitly added to channel sources for the feedstock.
Note: The constraint of requiring `defaults` to be added to channel sources explicitly (if the default setting are not used) is very important to ensure a proper interpretation of `defaults` as will be discussed in a latter PR.
Requires https://github.com/conda-forge/conda-smithy/pull/402
> Handle defaults explicitly

- conda_smithy/templates/appveyor.yml.tmpl
I've been re-rendering without this `PATH` dance and everything works just fine in `AppVeyor`.
> There is no need for this change.

- conda_smithy/templates/appveyor.yml.tmpl
Reverts PR ( https://github.com/conda-forge/conda-smithy/pull/404 ).
As mentioned in this [comment]( https://github.com/conda-forge/conda-smithy/pull/404#issuecomment-270047550 ), this path hack was found necessary in PR ( https://github.com/conda-forge/staged-recipes/pull/982 ) to update `conda` to a recent enough working version so that activation would work.
While I'm open to discussing and exploring how to do this in a cleaner in better way, it still remains necessary AFAICT. Any clean up of this should come with a demonstration of how it worked so that it can be more fully discussed.
cc @pelson @ocefpaf
> Revert PR 404

- .travis.yml
Closes https://github.com/conda-forge/conda-smithy/pull/410
This is a workaround for `conda-build` 2.1.0 packages that are missing the requirement on `enum34` in their Python 2.7 packages. It can be reverted after that is fixed.
xref: https://github.com/conda/conda-build/issues/1623
> Install enum34 in Python 2.7 CI builds

- .travis.yml
Reverts https://github.com/conda-forge/conda-smithy/pull/414
Looks like the packages in `defaults` have just been updated to include `enum34` as a requirement. So it looks like we don't need this workaround after all.
> Drop enum34 conda-build workaround

- conda_smithy/cli.py
> Use shell quotes for the current platform on the commit hint after re-rendering

- .travis.yml
Please do **not** merge this. It exists for testing purposes only
This reverts PR ( https://github.com/conda-forge/conda-smithy/pull/294 ) to see what will happen if the `setuptools` pinning is dropped.
> Unpin setuptools

- conda_smithy/feedstock_io.py
- conda_smithy/tests/test_feedstock_io.py
This configures git to normalize more line endings to avoid differences caused by a user's development environment (e.g. Windows vs. Unix). By doing this, we can be sure to get LF in all the cases we were already accustomed to having them. With Windows specific files (e.g. Batch files), we use CRLF as Windows would expect. This extends it beyond simply `bld.bat` as was the case before.
> Fix EOL formatting on Windows

- conda_smithy/configure_feedstock.py
While technically re-rendering did work for Python 3.6, the Miniconda selected for Python 3.6 on AppVeyor was not the ideal choice. Namely it used the Python 2.7 one, which is built on VC9. Instead we change this so that Python 3.6 leverages the Python 3.5 Miniconda install, which uses the same VC14 runtime. Having the `root` Python version using the same VC as the one used in a build has tended to work well for us in the past and has generally been the strategy used. This returns us to that strategy for Python 3.6.
> Add support for Python 3.6

- .travis.yml
- conda_smithy/configure_feedstock.py
- conda_smithy/tests/test_configure_feedstock.py
Appears the tests are now failing. Likely a product of `conda` version `4.2.13`, which we have recently released into the ecosystem. This PR is currently empty, but should prove fertile testing ground for a workaround and/or a fix.
Remember to revert the following pins after fixing this.
> Support conda 4.2.x

- conda_smithy/configure_feedstock.py
- conda_smithy/tests/test_configure_feedstock.py
This explicitly sets the channels used for generating the index. Instead of letting the index use whatever it can find, it uses the channel sources specified in `conda-forge.yml`. If the channel sources are not specified (i.e. all feedstocks in conda-forge), then this becomes `conda-forge` and `defaults`. Otherwise it uses whatever channels are specified (note `defaults` must be explicitly included if wanted). From very brief testing this seems to have the desired effect. Also includes a nifty workaround that should unblock re-rendering on Windows (*hopefully*), but this part is untested.
A test of using this can be seen with PR ( https://github.com/conda-forge/postgresql-feedstock/pull/6 ). Note that ordinarily re-rendering with the latest `conda-smithy` will not proceed correctly even …
> Config channels

- conda_smithy/templates/travis.yml.tmpl
Implementation of https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/6 , sibling of https://github.com/conda-forge/staged-recipes/pull/1094 .
Presumably shouldn't be merged until the CFEP is finalized.
> bump macOS image to xcode6.4

- conda_smithy/configure_feedstock.py
Note: This does not need to be done right away. Just putting it up here for consideration.
As Python 3.6 is being included throughout feedstocks and Python 3.5 is still in use, it makes sense for us to drop our oldest Python 3 that still remains. The purpose of doing this is to cutdown on the CI burden from building so many things and maintenance burden associate with this and the older Python. So here we drop Python 3.4 from the matrix.
xref: https://github.com/conda-forge/staged-recipes/pull/2179
> Drop Python 3.4 support

- conda_smithy/templates/appveyor.yml.tmpl
This remnant was part of a hack to make sure AppVeyor's preincluded Miniconda for Python 3.4 had a new enough version of `conda`. The included version could not be activated properly so this was necessary to make it work. However, we have since dropped support for Python 3.4. Further the preincluded Python 3.5 Miniconda has a very recent version of `conda`. As a result, this hack is no longer necessary and can be dropped.
Edit: Please see these [builds]( https://ci.appveyor.com/project/jakirkham/setuptools-feedstock/build/1.0.57 ) for tests of this change.
xref: https://github.com/conda-forge/staged-recipes/pull/2203
> Drop Python 3.4 AppVeyor update hack remnant

- conda_smithy/configure_feedstock.py
We are not in a hurry to merge this.  I am leaving this PR here as a remainder that we agreed to drop `numpy 1.10.x` from the build matrix soon.
https://github.com/conda-forge/staged-recipes/pull/2177
> Drop NumPy 1.10.x

- conda_smithy/templates/travis.yml.tmpl
Apparently `--force` is no longer sufficient when telling Homebrew to uninstall packages. If it turns out the packages are require by other packages, then `brew` will balk and issue an error message suggesting one also use `--ignore-dependencies`. Please see this [build]( https://travis-ci.org/conda-forge/conda-smithy-feedstock/jobs/191571328#L47 ) as an example. So we add `--ignore-dependencies` here in the hopes that this will get Homebrew to comply with our uninstall request.
> Fix Homebrew uninstall step to ignore dependencies

- README.md
Appears there was one space missing from each indented line. This appears to have resulted in a weird rendering of the code block by GitHub, which misses any of the indentation. Adding one more space to each indented line as done here should fix that.
Thanks to @guyer for [spotting this]( https://github.com/conda-forge/conda-smithy/issues/431#issuecomment-272671303 ).
> DOC: Fix indentation in target channel example

- LICENSE
- conda_smithy/feedstock_content/LICENSE
Specify date ranges for `conda-smithy`'s license and the feedstocks' licenses. Make sure to include the current year.
> License 2017

- conda_smithy/templates/travis.yml.tmpl
Closes https://github.com/conda-forge/setuptools-feedstock/pull/53
Cleans up the Travis CI build. Highlights of the changes are listed below. More details can be found in the individual commits and their messages.
* Use Homebrew's uninstall script to quietly remove Homebrew in a standard way.
* Add some more info in the logs about what each step is doing.
Complimentary to PR ( https://github.com/conda-forge/staged-recipes/pull/2262 ).
> Travis Cleanup

- conda_smithy/ci_register.py
Seems that CircleCI was using a deploy key with forked PR builds. However, they were not exposing the secret environment variables before. Though now it appears that they are exposing secret environment variables too. This is a bit strange as the CircleCI defaults to having the setting for secret environment variables disabled by default. In other words, it appears this default is not respected by CircleCI currently.
As a workaround, we seem to be able to fix this by explicitly disabling secret environment variables as well. A little bit of testing verifies this works as intended. While it is a workaround, it is a good thing to keep should CircleCI ever change the default value of this setting. Thus we have added this change to the configuration of CircleCI on new feedstocks right after …
> Explicitly disable secrets in forked PRs

- conda_smithy/configure_feedstock.py
Previously the re-rendering of `ci_support/run_docker_build.sh` and `circle.yml` occurred in two different steps. This combines these two steps into one. Meaning one less retrieval from the index to determine the contents of the matrix. As a result, there are exactly as many calls to the index as there are target architectures. This should speed up re-rendering a little bit and simplify the codebase a bit as well.
> Combine CircleCI re-rendering steps

- conda_smithy/feedstocks.py
There as a mixup in the lines. This caused the `clone_feedstock` function to fail because the clone variable doesn't exist. This also caused a silent error in `clone_all`  in the multiprocessing. Now it should work. Btw if we replace the explicit multiprocessing code with joblib the exception will always be thrown for us in the main thread.
> fix typos in clone functions

- conda_smithy/cli.py
- conda_smithy/configure_feedstock.py
- conda_smithy/feedstock_content/ci_support/fast_finish_ci_pr_build.sh
- conda_smithy/templates/appveyor.yml.tmpl
- conda_smithy/templates/circle.yml.tmpl
- conda_smithy/templates/fast_finish_ci_pr_build.sh.tmpl
- conda_smithy/templates/travis.yml.tmpl
Closes https://github.com/conda-forge/setuptools-feedstock/pull/59
Closes https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/55
Same thing as PR ( https://github.com/conda-forge/staged-recipes/pull/2264 ) except for the feedstocks.
Downloads the same Python script to help fast finish old PR builds on the various CIs as is used at staged-recipes. Tweaked to use the included script for `conda-forge-build-setup`.
A test of this on an ordinary feedstock can be seen in PR ( https://github.com/conda-forge/setuptools-feedstock/pull/59 ). Similarly a test for `conda-forge-build-setup` can be seen in PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/55 ).
> Fast finish old PR builds on CIs

- conda_smithy/templates/run_docker_build.tmpl
protects against early termination appearing as success.
This is one small piece of #337, but might be reviewed and merged more easily because it doesn't change anything, just adds a check that the script finished executing.
This would at least turn the cases fixed by #337 into failures, rather than mysteriously missing packages.
> verify that docker script reached its end

- conda_smithy/templates/run_docker_build.tmpl
A terminal newline was dropped from `run_docker_build.sh` in PR ( https://github.com/conda-forge/conda-smithy/pull/454 ). This adds it back.
> Add a terminal newline to `run_docker_build.sh`

- bootstrap-obvious-ci-and-miniconda.py
The download URL for miniconda2 has changed slightly. In particular, it now expects the '2' (that is, the major python version) after 'Miniconda' in the download filename, e.g.:
`https://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86.exe` --> `https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86.exe`.
Note this only affects downloading miniconda2 as the download url for miniconda3 always expected the major python version to be specified in the filename.
> Update setting major_py_version

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/run_docker_build.tmpl
This is a minimal change that adds *docker.executable* to the configurable parameters of *run_docker_build*. The goal is to be able to change the command to *nvidia-docker*, so that gpus get exposed during build, and specially test, whenever needed.
> Allow to tweak docker executable in run_docker_build

- conda_smithy/configure_feedstock.py
- conda_smithy/tests/test_configure_feedstock.py
This test case is able to reproduce the problems discussed in PR #453 (see [here](https://github.com/conda-forge/conda-smithy/pull/453#issuecomment-280058833)).
Further, the PR also contains the resulting fix.
@ocefpaf @jakirkham please let me know what you think.
> Add test case for configuring r related feedstocks. Fix compute_build_matrix in combination with build->skip.

- .travis.yml
Run the test suite through `unittest`'s `discover` option instead of using `setup.py`, which seems to be having issues.
> Bypass setup.py when testing

- README.md
- conda_smithy/cli.py
- conda_smithy/github.py
The goal of this change is to handle team management at the level of `conda-smithy`. Particularly as part of GitHub registration. Currently team management is handled by two different scripts. One in staged-recipes, which populates the maintainer teams on feedstock creation. The other is part of the team and feedstocks update script. As we may need to replace the latter with something soon and there is already code duplication, it seems better to consolidate the working implementation in `conda-smithy` and have both scripts leverage it.
In addition to cutting down repeated code, this provides us the option going forward of handling team updates in a different way than we have thus far. In particular, we could use a web service to update teams as changes are made. This should provide us …
> Manage teams

- conda_smithy/configure_feedstock.py
Fixes https://github.com/conda-forge/conda-forge.github.io/issues/357
Fixes https://github.com/conda-forge/conda-smithy/issues/487
Closes https://github.com/conda-forge/conda-smithy/pull/486
Closes https://github.com/conda-forge/setuptools-feedstock/pull/62 (for testing)
It appears `curl` has moved off of the path on AppVeyor. ( https://github.com/appveyor/ci/issues/1426 ) While it is possible to move `curl` back onto the path, there are a couple of concerns. First this may result in including other things on the path that we don't intend to. Second those other things may get involved in builds corrupting packages we are trying to deploy. Third there was never any guarantee that `curl` would be included on Windows nor is there any guarantee it will still be there. So this changes the …
> Download fast finish script with PowerShell

- conda_smithy.recipe/meta.yaml
Fixes https://github.com/conda-forge/conda-smithy/issues/375
Fixes https://github.com/conda-forge/conda-smithy/issues/447
In order to correctly render R-based packages, `conda-build-all` 1.0.2 is required. Plus we need 1.0.0+ to get `conda-build` 2.x to work.
> Require conda-build-all 1.0.2+

- conda_smithy/configure_feedstock.py
- requirements.txt
Use new, fixed conda-build-all. Solves issue #488, replaces pull request #492.
> Depend on conda-build-all 1.0.3. Remove previous workaround.

- README.md
It seems to me that re-rendering an existing feedstock is also possible without CI service tokens set up (although the CLI will show some warnings about it).. see conda-forge/obspy-feedstock#13. I feel this should be mentioned in the README because that's probably the number one use case most people will come across..
Please correct me if I'm wrong and missing something..
> Mention that re-rendering does not need CI tokens set up

- conda_smithy/templates/appveyor.yml.tmpl
It has come up several times in different discussions whether this compiler activation is still needed. There have been a few that have that state we should be able to outright drop it. Other suggestions have included moving it into the `toolchain` where it is used selectively for compilation as needed. There was a push to get much of this integrated into `conda-build`. I'm not really sure where we stand, but hopefully this can gather the discussion in one place and come to some sort of resolution. Please share your thoughts.
cc @patricksnape @jjhelmus @mwcraig @msarahan @pelson
xref: https://github.com/conda-forge/staged-recipes/pull/1142#discussion-diff-72016209R4
xref: https://github.com/conda-forge/toolchain-feedstock/issues/1
xref: https://github.com/conda/conda-build/pull/861
xref: …
> Drop Obvious CI compiler activation on AppVeyor

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/run_docker_build.tmpl
These are the changes necessary to build using the docker image built by https://github.com/conda-forge/docker-images/pull/36
After https://github.com/conda-forge/docker-images/pull/39 is merged these changes should work just fine, even though the docker image still runs as root by default
> Supporting building as a non-root user

- conda_smithy/cli.py
as discussed in https://github.com/conda-forge/conda-smithy/issues/494
check for conda < 4.3, and if not found, print a message more informative than the exception which would otherwise arise (since currently we're incompatible with 4.3+)
> check for conda < 4.3

- conda_smithy/templates/run_docker_build_matrix.tmpl
From my reading of the logs, the intention is to disable command echoing just for the stanza that sets the environment variables. The actual code was doing the opposite, however, no doubt because the bash notation is entirely counterintuitive.
> Fix some Docker 'set [+-]x' flags

- .travis.yml
- conda_smithy/cli.py
* Adds `conda` 4.2 to the CI matrix.
* Unspecified case is now `conda` 4.3.
* Drop a `conda-build` 1.* case with `conda` 4.3 (won't work and `conda-build` 1 is old).
* Update `conda` upper bound to 4.4.
> Test conda 4.3

- conda_smithy/cli.py
- conda_smithy/feedstock_io.py
This should help with the binary file copy issue and any other file that fails the `utf-8` encoding.
> Fix feedstocking with binary files

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/circle.yml.tmpl
Fixes https://github.com/conda-forge/conda-smithy/issues/527
Closes https://github.com/conda-forge/pyelftools-feedstock/pull/14
Closes https://github.com/conda-forge/gnureadline-feedstock/pull/8
Upgrades to new [CircleCI 2.0]( https://circleci.com/docs/2.0/ ) by borrowing from this [migration guide]( https://circleci.com/docs/2.0/migrating-from-1-2/ ), the [reference spec]( https://circleci.com/docs/2.0/configuration-reference/ ), and a [bunch of examples]( https://github.com/CircleCI-Public ). This should make it easier to explore matrix builds in CircleCI and provide us access to all the other latest features.
Test cases for the [Linux build]( https://github.com/conda-forge/pyelftools-feedstock/pull/14 ) and [non-Linux build]( https://github.com/conda-forge/gnureadline-feedstock/pull/8 …
> Support CircleCI 2.0

- conda_smithy/templates/circle.yml.tmpl
Let's not hardcode the docker image we pull in CircleCI.
> Honor docker.image in .circle/config.yaml

- conda_smithy/github.py
This reduces the number of github calls from <number-of-teams-in-org>/30 to 1.
> Use repo.get_teams() instead of org.get_teams()

- conda_smithy/cli.py
- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
Fixes #520 
Fixes #469 
There are more lints when env variable, `CONDA_FORGE_LINTS` is set. It checks that the github usernames are valid and that there is no existing feedstock.
> Add more lints for conda recipes

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/README.md.tmpl
- conda_smithy/tests/test_configure_feedstock.py
noarch, including noarch: python recipe only need to be built on a single
platform. Rendering feedstocks with noarch recipes results in only the Circle CI
logic being created.
Closes https://github.com/conda-forge/imagesize-feedstock/pull/5
> Render noarch recipe to only build on Circle CI

- conda_smithy/cli.py
This stops an annoying warning about missing tokens when all you
want to do is rerender a recipe
> Import ci_register when needed

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
Currently, the linter only checks that there is a `test` section (or a `run_test.*` file), not that the test section actually contains any tests. If someone makes `test/import` instead of `test/imports` by accident (https://github.com/conda-forge/staged-recipes/pull/3708), then the linter doesn't complain and it's pretty easy to miss that no tests are actually run.
Looking at [the source](https://github.com/conda/conda-build/blob/87332a198599e78ae394006b8ee87277dacfa5fa/conda_build/create_test.py), the only keys that actually cause tests to be created are `imports` and `commands`, so this checks that one of them is present for a `tests` section to count.
> linter check that there are actually tests

- conda_smithy/ci_register.py
Part of issue ( https://github.com/conda-forge/conda-forge-webservices/issues/63 ).
Provides a hook to listen for push events on feedstocks. The intent being to capture these events and use them to update each feedstock in the `feedstocks` repo. The net result being that the `feedstocks` repo will stay more up-to-date with feedstock additions in the organization as well changes made to each feedstock. Since these events will only concern an individual feedstock at a time, this should cutdown on the number of calls made to the GitHub API for operations like this one.
> Add feedstock hook

- conda_smithy/templates/README.md.tmpl
This reverts commit 860d93ebb6edab02b1a74dd02ba7bec4f4f90c61.
Updating conda after adding the conda-forge channel is going to be problematic. (If it installs a conda-forge package that is noarch, then there's going to be problems)
> Revert "Add instructions to update conda"

- conda_smithy/lint_recipe.py
This fixes #576 by not allowing brackets inside the selector brackets, the fix of https://github.com/conda/conda-build/pull/957.
> update selector pattern to the current one in conda_build

- conda_smithy/ci_register.py
The repository event notifies when a repo has been deleted (amongst other things). This is important for the team and feedstocks services as they will also need to handle this event. The team service will need to remove the associated team and the feedstocks service will need to remove it from the feedstocks repo.
> Listen to repository events

- .travis.yml
This test has been failing for months. I'm removing this for now.
> Drop conda=4.2

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
Fixes https://github.com/conda-forge/conda-smithy/issues/578.
Since this has been happening more often now that the example recipe includes a `noarch: python` instruction, add a linter check that `noarch` packages don't have any selectors in them.
> add test that noarch packages don't have selectors

- conda_smithy/configure_feedstock.py
conda smithy has started including R 3.4.2 in the build matrix for R packages because it is available in defaults. This is causing problems for recipes added to staged-recipes and also for existing feedstocks when being rerendered.
The current plan as I understand it is for conda-forge to support only one version per minor release, i.e. 3.3.2 for the 3.3.* series and 3.4.1 for the 3.4.* series. When R 3.5 is released, this script can be updated by changing it to, e.g. `'r-base ==3.3.2|==3.4.1|==3.5.1'`.
> Only include r-base versions provided by conda-forge.

- conda_smithy/lint_recipe.py
See #2582 for an example use-case (split hundreds of header files from main library package as they aren't needed in most scenarios).
> Add `outputs:` to allowed meta.yaml sections

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
This is so that `tests` and `script` can be os specific for bash vs cmd differences.
cc @dougalsutherland, @conda-forge/staged-recipes
> In noarch only check for selectors in requirements

- conda_smithy/configure_feedstock.py
As AppVeyor recognizes `appveyor.yml` and `.appveyor.yml` by default, switch to `.appveyor.yml`. This matches how we handle other CI configuration files for Travis CI and CircleCI. Should also remove noise for anyone just looking at the feedstock locally.
Edit: Testing in PR ( https://github.com/conda-forge/click-feedstock/pull/8 ). Have also tested on a `noarch: python` recipe, but there is no visible change to the feedstock.
> Hide AppVeyor config file in feedstocks

- conda_smithy/templates/run_docker_build.tmpl
Fixes https://github.com/conda-forge/conda-smithy/issues/634
Makes sure to mount all directories in the `conda` user's home directory. Previously they were mounted at `/`, which meant they required `root` to modify the directories or their contents. Relocating them to the `conda` user's home directory should avoid these issues as the `conda` user has permissions on those locations.
Edit: Tested in PR ( https://github.com/conda-forge/webcolors-feedstock/pull/10 ).
> Mount directories in `conda` user's home

- conda_smithy/feedstock_content/.github/CONTRIBUTING.md
- conda_smithy/feedstock_content/.github/ISSUE_TEMPLATE.md
- conda_smithy/feedstock_content/.github/PULL_REQUEST_TEMPLATE.md
Fixes https://github.com/conda-forge/conda-smithy/issues/509
Provides GitHub templates for [issues]( https://help.github.com/articles/creating-an-issue-template-for-your-repository/ ) and [PRs]( https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ ) to each feedstock. Also provides some [contribution guidance]( https://help.github.com/articles/setting-guidelines-for-repository-contributors/ ) when either issues or PRs are opened. Should help streamline some common interactions on feedstocks and make it easier on maintainers trying to resolve users' problems and/or review proposed changes.
> Add feedstock PR/issue templates and contribution guidance

- conda_smithy/lint_recipe.py
- conda_smithy/tests/test_lint_recipe.py
I accidentally put a `skip` key in the `requirements` section, and got the dreaded "failed to even lint the recipe" message: https://github.com/conda-forge/staged-recipes/pull/3780#issuecomment-324723905.
This fixes the linter to not crash in this case, but instead complain about the unexpected key.
> lint instead of crashing when requirements has unexpected keys

- conda_smithy/cli.py
Fixes https://github.com/conda-forge/conda-smithy/issues/333
The `--no-git-repo` option is unused in `conda-forge`. Also it doesn't sound like it is being used outside of `conda-forge`. Most of the content that `conda-smithy` generates ends up being only useful for GitHub repos with CI configured anyways. In an effort to help simplify the codebase, this drops the `--no-git-repo` option. Hopefully things like `feedstock_io` can be simplified in the process.
> Drop the `--no-git-repo` option

- conda_smithy/templates/appveyor.yml.tmpl
- tests/recipes/click-test-feedstock/.appveyor.yml
Some of the paths in the AppVeyor configuration files were using forward slashes. This fixes them to use backslashes as is typical on Windows.
> Use backslashes on AppVeyor

- conda_smithy/feedstock_content/.github/PULL_REQUEST_TEMPLATE.md
As we no longer need to manually update pins in `conda-build` 3, drop the line suggesting we do.
cc @isuruf
> No need to manually update pins

- conda_smithy/feedstock_content/.gitignore
- conda_smithy/templates/run_docker_build.tmpl
Reverts conda-forge/conda-smithy#337
> Revert "use a script instead of piping to stdin in run_docker_build"

- conda_smithy/templates/appveyor.yml.tmpl
We need to tell `conda` it is ok to update. So this fixes that. The quiet portion merely deals with the fact that CIs are not the same as interactive terminals.
> Add `--yes --quiet` to conda update

- conda_smithy/configure_feedstock.py
since rerendering will be wrong if it proceeds ignoring the matrix.
point to new matrix location in recipe/conda_build_config.yaml and wiki for reference on migrating
This points to the release notes on the wiki, but in #700 @jakirkham mentioned that this will end up in the docs closer to release. The link should probably be updated if/when that happens.
closes #700
> fail rerender if matrix found in conda-forge.yml

- conda_smithy/configure_feedstock.py
- tests/conftest.py
- tests/test_configure_feedstock.py
fixes #711 
I tried to get the tests to break without the fix, but couldn't.  I don't know exactly what I'm missing.  I do know that line 127 in configure_feedstock here fixes it, but it would be nice to understand how the types were coming out differently.
They were coming in as a list of tuples, which made this code wrap the list in another list, which then caused zip_keys to be trimmed completely down the line, which caused us to lose our association between python version and vs version.
> fix zip_keys getting trimmed too much due to type check error

- conda_smithy/cli.py
Thus far `conda` version `4.5` works ok for `conda-smithy`. Maybe even all versions of `conda` now that we use `conda-build`'s API exclusively (given `conda-build` supports them). Though just bump to anything below `4.6` as a cautionary move.
> Bump conda upper bound to 4.5.x

- conda_smithy/lint_recipe.py
- tests/test_lint_recipe.py
This PR is to fix the issues raised by the recipes here:
- Terraform conda-forge/terraform-feedstock#11
- Terraform-Providers conda-forge/staged-recipes#5328
- Vault conda-forge/vault-feedstock#6
- Consul conda-forge/consul-feedstock#13
- Consul-template conda-forge/consul-template-feedstock#4
> Add load_file_regex as an allowed jinja2 command

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/README.md.tmpl
- conda_smithy/templates/circle.yml.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- conda_smithy/templates/run_osx_build.tmpl
- tests/conftest.py
- tests/test_configure_feedstock.py
```yaml
provider:
osx: circle
```
in `conda-forge.yml` changes the rerendering to skip travis and use circleci for osx.
> Optionally use CircleCI OSX builds

- conda_smithy/cli.py
Otherwise `staged-recipes` thinks it is successful.
Earlier this didn't matter because `init` did a render and when there is a failure in `register-ci`, there's no change in the following `rerender` call and `git commit` would fail.
`conda-smithy>=3` doesn't do a render after the `init` call. Therefore there's a change in the subsequent `rerender` call even if `register-ci` failed.
> Don't catch errors

- conda_smithy/templates/README.md.tmpl
To aid readability, format the badges in a Markdown table. This should make it clearer what they represent and easier to look at several split packages from one recipe build.
Side note: Making the text pretty would be pretty painful (and it is autogenerated). So skipped that. However the table it generates is still nice.
xref: https://github.com/conda-forge/conda-smithy/pull/744#issuecomment-382464743
cc @isuruf
> Place package badges in markdown table

- rever.xsh
Fixes https://github.com/conda-forge/conda-smithy/issues/752
As we need to generate the changelog before we tag.
@CJ-Wright, is this correct?
> Generate the changelog first

- conda_smithy/templates/run_docker_build.tmpl
- news/update-conda-build.rst
https://github.com/conda-forge/pdal-feedstock/issues/1#issuecomment-382729121
Currently `run_docker` doesn't update to the latest conda-build, because `conda-forge-ci-setup` only requires 3.*, and the Docker container already has 3.something. This <s>should (I think?)</s>will update it appropriately when it's out of date.
> Update conda-build for Linux builds

- conda_smithy/lint_recipe.py
- tests/test_lint_recipe.py
These can be used to provide suggestions such as package naming, compiler
usage etc.
> Add support for non-failing lints in the linter

- conda_smithy/configure_feedstock.py
Fixes https://github.com/conda-forge/conda-smithy/issues/775
Fixes https://github.com/conda-forge/conda-smithy/issues/776
Previously `yum_requirements.txt` was being ignored on Linux. As @isuruf correctly deduced, this was due to the unconditional inclusion of `build_steps.sh.tmpl`, which was also being done below. This corrects that issue by dropping `build_steps.sh.tmpl` from general inclusion in the template files when it is not needed. Also fixes a small typo in a comment about `yum_requirements.txt`.
cc @looooo
> Fix inclusion of yum requirements

- conda_smithy/configure_feedstock.py
- news/fix-trim-pinnings.rst
I noticed that rerendering was removing `json_c` from `pin_run_as_build`, after https://github.com/conda-forge/conda-forge-pinning-feedstock/commit/0098fad4493f5ecad1a0d90b8664dd19566c2170, but not adding the correct `json-c`. The current check for whether packages are used doesn't work for packages with `-` in their name.
Things I don't know, and haven't checked:
- Are there any other changes to the names that might be made?
- If so, is there a better way to make this check?
- Do we need to do a similar thing in `_trim_unused_zip_keys` or `_collapse_subpackage_variants`?
> fix pin_run_as_build trimming for packages with -

- conda_smithy/configure_feedstock.py
- news/merge-configs.rst
Even though the key of a variant in a zip_keys group is repeated,
key of another variant in the same zip_keys group may not be repeated
> Fix merging of list of dicts

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/README.md.tmpl
For a project of mine, I'm trying to stay close to the upstream conda-forge-feedstock, but would prefer to have the badges generated for my own branch.
Does this do what I want it to do?
Do I need to add something around these lines of code:
https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/github.py#L99
> Allow custom branch in repo for badges

- conda_smithy/lint_recipe.py
Addressees https://github.com/conda-forge/conda-smithy/pull/669#issuecomment-397668135
Instead of a lint fail if `noarch` is used let's suggest "use pip" globally whenever it is possible to use `pip`.
Ping @isuruf and @CJ-Wright
> suggest pip

- conda_smithy/ci_register.py
- news/fix_travis_error.rst
Travis sometimes knows about github repos, but doesn't know that the bot
has admin access to it. (Maybe because travis accounts of cf admins are
synced, travis knows about the repo)
In that case, sync account and wait till travis knows that the bot has
admin access
> Fix travis-ci API permission error

- conda_smithy/templates/appveyor.yml.tmpl
- news/appveyor_image.rst
I need this to get Visual Studio 2017 for nodejs 10.
Testing a build rendered from this branch now: https://github.com/conda-forge/nodejs-feedstock/pull/41
At some point, the default image may want to be bumped, but the VS 2017 image doesn't appear to have the old-timey Python 2.7 compilers, so I think it would have to be conditional for a while.
closes #605
> Allow setting appveyor.image in conda-forge.yml

- conda_smithy/configure_feedstock.py
- news/track_versions.rst
There's been discussion about this before, but not finding it right now.
Currently tracks `conda-smithy`, `conda-forge-pinning`, `conda-build`, and `python` versions in `.smithy-version.json`. Also adds `[skip ci]` to the commit message if only that file (and/or the README; any other files like that?) changed in a re-rendering.
> track conda-smithy, etc versions in the feedstock

- conda_smithy/cli.py
This makes specifying `--no-check-uptodate` without an argument sufficient for skipping the update check. Preserves the default behavior of erroring out.
> Adjust `--no-check-uptodate` to take no argument

- conda_smithy/lint_recipe.py
- news/subpackage_tests.rst
- tests/test_lint_recipe.py
Fixes #759.
I chose to not error as long as any subpackage has a test, but give hints if they don't all have tests; not sure if that's the best tradeoff. :man_shrugging:
> linter: recognize tests in subpackages

- conda_smithy/configure_feedstock.py
- news/fix_ordereddict_order.rst
Fixes https://github.com/conda-forge/conda-smithy/pull/820#issuecomment-408478535.
Avoids sorting of `OrderedDict` entries at https://bitbucket.org/ruamel/yaml/src/default/representer.py?at=0.15.46#representer.py-201.
cc @isuruf
> Fix OrderedDict order not being kept

- conda_smithy/lint_recipe.py
- news/check-abcs.rst
- tests/test_lint_recipe.py
`ruamel.yaml` version 0.15.52 [changed `CommentedMap` to no longer subclass from `dict`](https://bitbucket.org/ruamel/yaml/commits/ace40a6a40270b75320971d1c9ff7625fbf6e081#Lcomments.pyF594). This is breaking `get_section` / `get_list_section` and causing all kinds of spurious errors / breaking real checks: [example](https://github.com/conda-forge/conda-forge-webservices/pull/54#issuecomment-412106931). Checking based on ABCs instead should still work.
I also removed a few no-longer-used imports from the top of this file while I was at it.
> get_section: check ABCs instead of list/dict subclass

- conda_smithy/lint_recipe.py
- news/bioconda-no-name.rst
- tests/test_lint_recipe.py
Currently, if a recipe doesn't have a `name`, it'll ping `bioconda-recipes` ([example](https://github.com/conda-forge/conda-forge-webservices/pull/54#issuecomment-412106931)). That seems not ideal. :)
> don't complain about bioconda for packages with no name

- conda_smithy/templates/README.md.tmpl
Fixes https://github.com/conda-forge/conda-smithy/issues/777
There are some tweaks needed for the repo name for the AppVeyor/Windows badge. While these were included in the link, it seems they need to be included in the Shields.io badge as well for the badge to render. Should fix some issues with the rendering of AppVeyor/Windows badges on feedstocks that have `_`s or `.`s in their names.
cc @isuruf @epruesse
> Fix Windows badge in feedstocks' README

- conda_smithy/templates/run_docker_build.sh.tmpl
If you're running Docker builds on an SELinux-enabled Linux system, the mounted volumes need to have the appropriate SELinux flags set if they are to be used by their containers. Here we add the magic `z` option to make this happen. We also mount the recipe directory read-only since the container shouldn't need to write to it.
Full disclosure: not tested locally but it *should* work ...
> conda_smithy/templates/run_docker_build.sh.tmpl: add SELinux flags to Docker volumes

- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
This is removing Homebrew on Azure (instead of Travis CI previously).
cc @willsmythe
xref: https://github.com/conda-forge/conda-smithy/pull/901#discussion_r228593277
> Fix copy-paste issue in Azure script

- conda_smithy/github.py
Only iterate over the current maintainers of a feedstock listed on the GitHub team when the team exists. Otherwise we know there are no maintainers and this iteration is unneeded.
Also handle additions to the feedstock team and the all-members team in the same loop to avoid performing the same checks twice.
> Simplify collection of current maintainers

- conda_smithy/templates/build_steps.sh.tmpl
somehow the channel-priority doesn't work with this explicit specification of channels. Using the -c instead seems to solve this.
No idea why this has changed.
> install conda-forge deps from conda-forge

- conda_smithy/templates/run_docker_build.sh.tmpl
This is handy when building locally as it allows the user to quickly terminate a job use `^C`. Also has the nice added effect of showing color coded text as it was intended to appear.
xref: https://github.com/conda-forge/conda-smithy/pull/901#discussion_r229541251
> Readd the `-it` flags for `docker run`

- conda_smithy/templates/travis.yml.tmpl
and allow override via travis.osx_image
The current xcode6.4 has had a warning about its impending removal for a long time, and it's coming up pretty soon, in January 2019.
With the current state of tooling including [fetching the sdk](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/31) and [setting the sysroot](https://github.com/conda-forge/toolchain-feedstock/pull/46), we should be able to be less conservative about the base xcode version from now on. The few mac builds on CircleCI have been using xcode 9 since they started. Having [faced a build from Circle that didn't work](https://travis-ci.org/conda-forge/parmetis-feedstock/jobs/428047190#L945) (openmpi) and fixed it by [ensuring sysroot was properly set](https://github.com/conda-forge/toolchain-feedstock/pull/46) …
> bump default travis image to xcode9.4

- conda_smithy/templates/build_steps.sh.tmpl
conda-build 3.17 doesn’t show host and build envs when built with `--quiet` which are important for debugging. Mac builds are already not using --quiet.
> remove --quiet from conda-build on linux

- conda_smithy/utils.py
- tests/test_lint_recipe.py
Invoking `conda smithy recipe-lint` on the [conda-forge/go1.4-feedstock/meta.yaml](
https://github.com/conda-forge/go1.4-bootstrap-feedstock/blob/master/recipe/meta.yaml) file yields the following exception:
```
± conda smithy recipe-lint
Traceback (most recent call last):
File "/opt/conda/bin/conda-smithy", line 10, in <module>
sys.exit(main())
File "/opt/conda/lib/python3.6/site-packages/conda_smithy/cli.py", line 279, in main
args.subcommand_func(args)
File "/opt/conda/lib/python3.6/site-packages/conda_smithy/cli.py", line 203, in __call__
return_hints=True)
File "/opt/conda/lib/python3.6/site-packages/conda_smithy/lint_recipe.py", line 428, in main
content = render_meta_yaml(''.join(fh))
File "/opt/conda/lib/python3.6/site-packages/conda_smithy/utils.py", line 49, in render_meta_yaml …
```
> Fix linter error on missing target_platform

- conda_smithy/templates/README.md.tmpl
- news/relocate-numfocus-badge-readme.rst
Fixes https://github.com/conda-forge/conda-smithy/issues/972
As there was some concern raised that having the NumFOCUS badge where it was would confuse users as to what was NumFOCUS sponsored (i.e. that their library is NumFOCUS sponsored) as opposed to the fact that conda-forge is NumFOCUS sponsored, this relocates the NumFOCUS badge to the "About conda-forge" section where this should hopefully make it clear that conda-forge is NumFOCUS sponsored.
cc @moorepants @scopatz
Checklist
> Move the NumFOCUS badge to "About conda-forge"

- CHANGELOG.md
As we now use rever to cut releases and that makes a `CHANGELOG.rst` in the top-level directory, there is no need to point users to GitHub releases using this `CHANGELOG.md` as well. So go ahead and drop it for simplicity.
Checklist
> Drop old CHANGELOG file linking to GitHub releases

- conda_smithy/cli.py
- news/per_ci_disable_registration_options.rst
Checklist
you can use
````
$ conda-smithy register-ci --help                                                                                                                             
usage: a tool to help create, administer and manage feedstocks. register-ci
[-h] [--feedstock_directory FEEDSTOCK_DIRECTORY]
[--user USER | --organization ORGANIZATION] [--without-azure]
[--without-travis] [--without-circle] [--without-appveyor]
optional arguments:
-h, --help            show this help message and exit
--feedstock_directory FEEDSTOCK_DIRECTORY
The directory of the feedstock git repository.
--user USER           github username under which to register this repo
--organization ORGANIZATION
github organisation under which to register this repo
--without-azure       If set, Azure will be not …
```
> Add options to disable CIs

- conda_smithy/lint_recipe.py
- news/noarch_selectors_runtime.rst
- tests/test_lint_recipe.py
Checklist
PR #622 didn't include a news entry. Since this PR is similar in scope, I assume it also does not warrant a news entry. Please let me know otherwise.
This PR address https://github.com/conda-forge/conda-forge.github.io/issues/683, in which the linter is failing recipes that have selectors in the build requirements. staged-recipes builds noarch packages on all 3 platforms purposefully, in case others want to build the recipe on other platforms.
cc: @CJ-Wright @isuruf @bgruening
> Only fail noarch lint if selectors in runtime dependencies.

- README.md
rst headings don't do the same things in markdown, so the image was just a literal block
> README: Fix markdown for xkcd inclusion

- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/azure-secrets.rst
For azure secrets aren't added automatically to all stages, you have to ask to use them
See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azdevops&tabs=yaml%2Cbatch#systemaccesstoken
> Fixed missing secret for azure publishing

- conda_smithy/lint_recipe.py
- news/suggest_noarch.rst
- tests/test_lint_recipe.py
Checklist
@chrisburr and I noticed that it would be nice if conda-smithy could suggest to use noarch for packages which do not have operation system dependent requirements, are installed via pip and do not require a compiler.  
https://github.com/conda-forge/staged-recipes/pull/7780
I tired to implement a corresponding hint in the `lint_recipe.py`.
> Suggest Python noarch

- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
adding this to the conda build config file appears to only affect the build env, in which case compilation during the test phase can still fail. This *seems* like a conda-build bug, though because I'm using multiple outputs [where I ran into this](https://github.com/conda-forge/mpich-feedstock/pull/32) I'm ready to believe this is something peculiar in my recipe.
WIP, pending testing in https://github.com/conda-forge/mpich-feedstock/pull/32
This implementation relies on [this bit](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/276c13013f674fab262fc3e02bf2e90396334468/recipe/run_conda_forge_build_setup_osx#L33-L39) where conda-forge-ci-setup stores the CONDA_BUILD_SYSROOT in the current build config file. That level of coupling implementation details of the two repos …
> [WIP][azure,mac] set CONDA_BUILD_SYSROOT env during build

- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
Rework osx azure build to `conda activate base` at every step.
I've also updated how we get conda as the official approach outlined in the documentation works now.
Checklist
> Azure: osx forward env vars set by conda-forge-ci-setup

- conda_smithy/azure_ci_utils.py
- conda_smithy/ci_register.py
- conda_smithy/cli.py
- conda_smithy/configure_feedstock.py
- conda_smithy/templates/README.md.tmpl
- conda_smithy/utils.py
- news/azure-buildid.rst
This command will retrieve the build id from azure.  With this we can make badges and improve UX for azure.
This adds an additional subcommand that non-conda-forge users will want to use in order to get the correct azure metadata for making badges stores in the config file.
Checklist
> Added azure buildid and azure badges to readme

- conda_smithy/lint_recipe.py
- news/noarch_staged_recipes_only.rst
As discussed in https://github.com/conda-forge/conda-smithy/pull/1021#issuecomment-467253422 - this would resolve #1030, and the similar #1031, in a conservative way for existing recipes. Hopefully the staged-recipes PR's are getting enough manual review to identify when the linter should be listened to or ignored.
Checklist
> Only do noarch linting in staged-recipes, not feedstocks

- conda_smithy/azure_ci_utils.py
- news/fix-staged-recipes.rst
Feedstock conversion is currently broken in staged-recipes, see [here](https://travis-ci.org/conda-forge/staged-recipes/builds/508675401#L851-L862).
I think this PR fixes it, I might not have time to look at this again today so feel free to edit this PR or replace it with a new one if needed.
Checklist
> Fix bug preventing feedstock conversion in staged-recipes

- conda_smithy/templates/README.md.tmpl
- news/azure-table-whitespace.rst
This cleans out some extra whitespace that trigger a code block in the azure table:
I haven't _fully_ tested this... but ran into it while looking at other stuff...
> Clean up azure table whitespace in README

- conda_smithy/configure_feedstock.py
- news/pyc.rst
When conda_smithy is installed `feedstock_content/build-locally.py` is
compiled to python bytecode. When conda-smithy copies that folder
to the feedstock and git adds the content, the bytecode files are also
checked in the feedstock git repo.
This commit ignore .pyc files when copying the tree
Fixes https://github.com/conda-forge/conda-smithy/issues/1082
> Fix checking in pyc files

- conda_smithy/cli.py
- news/conda_version_bump.rst
Checklist
I did a successful rerender with conda 4.7.5.  I don't think this needs to be constrained so tightly.  We'll be much more conservative about semver under my watch, so the next major version should be appropriate here.
> bump conda version check (from 4.7 to 5.0)

- conda_smithy.recipe/meta.yaml
- conda_smithy/variant_algebra.py
- news/update-3.4.1-deps.rst
Checklist
Dependency update addresses:
- https://github.com/conda-forge/conda-smithy-feedstock/pull/156
- https://github.com/conda-forge/pingouin-feedstock/pull/7
Changed `VersionOrder` import to `conda.exports` as other `conda` modules are to be considered non-public.
> requirements: update to conda-build>=3.18.3

- conda_smithy/feedstock_content/.gitattributes
- news/mark-as-generated.rst
According to https://github.com/github/linguist#generated-code we can mark our generated portions and github will collapse them
in pull requests automatically.  This should reduce mouse wheel fatigue for conda-forge reviewers.
Checklist
> Mark generated files as such to github

- conda_smithy/configure_feedstock.py
- news/armv7l.rst
conda smithy will regenerate feedstocks with support for the linux-armv7l
platform if "linux_armv7l: azure" is added to the provider key in
conda-forge.yaml
Checklist
> add support for the linux-armv7l platform

- conda_smithy/ci_register.py
- conda_smithy/cli.py
- conda_smithy/feedstocks.py
- conda_smithy/lint_recipe.py
- conda_smithy/utils.py
- news/duplicate-yaml-keys.rst
- use simpler ruamel.yaml API
- explicitly allow duplicate keys, required for ruamel.yaml 0.16
This fixes recipe-lint failures caused by the recent [disallowing of duplicate keys in 0.16](https://yaml.readthedocs.io/en/latest/api.html#duplicate-keys)
Checklist
> consolidate yaml loader in utils.yaml

- conda_smithy/utils.py
- news/mock-py_ver.rst
PY_VER is provided for the recipe check. This variable is defined:
https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html
and a reasonable default based on sys.version_info is provided based on:
https://github.com/conda/conda-build/blob/dd74b17f4e7cb4286fe9a403895f9d34feb8e071/conda_build/environ.py#L49-L53
Fixes #1112
> Mock PY_VER for recipe check

- conda_smithy/configure_feedstock.py
- news/render_README.rst
Checklist
If `user_or_org` is set and no azure account is set up for the specified name, the request returns a 404 response, which leads to an uncaught `JSONDecodeError`.
This fix raises an `HTTPError` which is caught by the except clause's `IOError`.
> fix render_README crash when azure api returns 404

- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
This PR names the uploading step of the Azure Pipelines job for Windows.
Also, it corrects the name of the corresponding step for OSX as uploading happens for a built package, not a recipe.
Checklist
> CI: Add a missing displayName for Windows Azure template

- conda_smithy/configure_feedstock.py
- news/remove_github_codeowners.rst
This PR allows to remove the `.github/CODEOWNERS` file in case the recipe maintainers list is empty (pretty useful for our work https://github.com/nsls-ii-forge where the entire team is considered as maintainers, so no need to put it to the recipes).
Checklist
> ENH: remove .github/CODEOWNERS if recipe maintainers list is empty

- conda_smithy/configure_feedstock.py
This had confused me several times. Since `conda install -n base conda-forge-pinnings` did not fix this. For me the "root" env is the "base" env, the root of all environments. Here it's just the actual environment where we are running conda-smithy.
> Do not call it "root" env

- .travis.yml
- conda_smithy/azure_ci_utils.py
- conda_smithy/configure_feedstock.py
- conda_smithy/templates/drone.yml.tmpl
- news/drone-fixup.rst
Contains #1185 with black applied to fix formatting. Looks like they now add trailing commas in multiline tuples/function argument declarations.
Update: I've moved to using `$DRONE_WORKSPACE` instead of `$CI_WORKSPACE`. It's not documented but appears to be the official supported variable: https://discourse.drone.io/t/feature-request-drone-project-dir-env-variable/4804/2
Checklist
> Drone update and apply black to fix formatting

- .travis.yml
- conda_smithy/templates/drone.yml.tmpl
- news/drone-fixup.rst
`CI_WORKSPACE` does not seem to be set reliably on drone workers.  Falling back to `pwd` which works fine.
Checklist
> Drone update

- conda_smithy.recipe/meta.yaml
- conda_smithy/lint_recipe.py
- news/shellcheck_hints.rst
- requirements.txt
- tests/conda-forge.yml
- tests/recipes/build_script_with_findings/build.sh
- tests/recipes/build_script_with_findings/meta.yaml
- tests/test_lint_recipe.py
closes https://github.com/conda-forge/conda-smithy/issues/118
As the shell script syntax dates back to the 1970s, there are plenty of pitfalls and old types of syntax that won't get removed due to backward compatibility, which shellcheck can help to find for us.
This could be especially useful as it lints the build.sh, the important companion to the meta.yaml to
build complex recipes.
This is ready for comments.
Potential TODOs:
Outside this PR
> Extend linter to check shell scripts via shellcheck

- conda_smithy/configure_feedstock.py
- news/validate_feedstock_rerender.rst
Make sure that `conda-forge.yml` exists in the current working directory before re-rendering. If it does not exist, raise a `RuntimeError`.
Checklist
> Test re-rendering is run in a feedstock

- conda_smithy/configure_feedstock.py
message said "not rerendering inside the recipe" when rerender *was* called from inside the recipe.
> minor typo in rerender error message

- conda_smithy/lint_recipe.py
- news/fix_linter_bug.rst
- tests/test_lint_recipe.py
> Fix crash of linter when package in run section starts with python in nameing

- conda_smithy/configure_feedstock.py
- conda_smithy/variant_algebra.py
- news/migration_cfp.rst
- tests/conftest.py
- tests/test_configure_feedstock.py
instead of the ones from the feedstock if the
timestamp field match and remove if the migration yaml has a
timestamp and there's no corresponding one in conda-forge-pinning
which indicates that the migration is over.
Checklist
> If conda-forge-pinning package has migrations installed, use those

- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
- news/macos_10.14.rst
- news/macos_10.15.rst
This PR resolves the upcoming discontinuation of the macOS-10.13 image on Azure Pipelines (March 23, 2020). See https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/ for details. Thanks to @dmgav for pointing to the issue.
Checklist
> macOS-10.15 image for Azure Pipelines

- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/conda-bug.rst
conda doesn't like installing packages at the same time as it updates itself
Checklist
> Fix bug with conda 4.6.14 on Windows

- conda_smithy/configure_feedstock.py
- news/1254_rerender_missing_recipe_dir_from_config.rst
- pytest.ini
- tests/conftest.py
- tests/test_configure_feedstock.py
Fixes #1254
Checklist
I added a test for the case I ran into and confirmed that my changes fix it.  Going to let CI rerun the tests across all other platforms.
When making the fix, I did find other places where `conda_smithy/configure_feedstock.py` was hardcoding "recipe" and I changed them to use `forge_config["recipe_dir"]` instead (in one case, I had to add `forge_config` to a method signature).
I also registered `@pytest.mark.cli` in this to quiet down a pytest warning.  If you guys don't like code-gardening lumped in with PR's, I can break that out separately.
> Fix rerender using hardcoded 'recipe' instead of forge_config["recipe_dir"]

- conda_smithy/configure_feedstock.py
- news/azure_cleanup.rst
To make sure that stray contents are not left in `.azure-pipelines`, delete the directory and its contents before rendering. That way any files that are not generated by rendering will be removed. Ones that are generated by rendering will be added anyways, which will negate this behavior.
Checklist
> Clear `.azure-pipelines` directory before render

- CHANGELOG.rst
- conda_smithy/templates/run_docker_build.sh.tmpl
If you're running builds locally, there's no need to keep the individual containers around. Even moreso in a CI environment.
You could perhaps call this a "fix".
Checklist
> ENH Provide a mechanism to pass extra arguments to `docker run`

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
- conda_smithy/templates/circle.yml.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- conda_smithy/templates/travis.yml.tmpl
- news/osx_refactor.rst
- tests/test_configure_feedstock.py
This PR centralizes the OSX CI scripts to use a single build script with miniforge. 
closes #1292 
Checklist
> REF use one osx script with miniforge

- conda_smithy/templates/run_docker_build.sh.tmpl
- news/docker_rw.rst
This fixes a pip install issue @isuruf found when making a change to the conda-forge-ci-setup feedstock. 
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/87/files
Checklist
> ENH use read-write permissions for docker mounts

- conda_smithy/configure_feedstock.py
- conda_smithy/github.py
- conda_smithy/lint_recipe.py
- conda_smithy/utils.py
- news/feedstock_name.rst
- tests/conftest.py
- tests/test_configure_feedstock.py
Specify the generated feedstock name via:
```
extra:
feedstock_name: explicit_name
```
Checklist
> Allow to explicitly name the feedstock

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/self_hosted_azure_agent.rst
- news/self_hosted_azure_agent_linux.rst
Checklist
This PR supports self-hosted Azure agents, which we will use to help some facility-specific needs. The following example shows the newly accepted variables in `conda-forge.yml` for this capability:
```jinja
azure:
pool:
name: Our_Local_Pool
demands:
- tagA -equals 2
workspace:
clean: all
strategy:
maxParallel: 1
docker:
run_args: -t --rm
```
nsls-ii-forge/cupy-feedstock#1 is a real working PR with the Azure (Linux) agent backed by a local machine. The meanings and the hierarchy of variables follow directly the definition in the [Azure Pipelines documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#define-a-single-job). 
The addition of the `run_args` variable is a follow-up of #1279, which will be passed to …
> Support self-hosted Azure agents

- conda_smithy/configure_feedstock.py
- news/teams.rst
So github team names do not appear to be case sensitive. I have also seen errors when the team name has uppercase values when we are making codeowner files. See @xhochy's PR on the pinnings repo. Thus we always make team names lower case.
This link
https://github.com/orgs/conda-forge/teams/Core
and this one 
https://github.com/orgs/conda-forge/teams/core
go to the same spot for example.
Checklist
> BUG github team names are case-insensitive

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- conda_smithy/templates/build_steps.sh.tmpl
- conda_smithy/templates/drone.yml.tmpl
- conda_smithy/templates/run_docker_build.sh.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- news/secrets.rst
- tests/recipes/click-test-feedstock/.appveyor.yml
- tests/recipes/click-test-feedstock/.circleci/run_docker_build.sh
- tests/recipes/click-test-feedstock/.travis.yml
- tests/test_configure_feedstock.py
Additional secrets can be passed to the build by setting `secrets: ["BINSTAR_TOKEN", "ANOTHER_SECRET"]` in `conda-forge.yml`. These secrets are read from the CI configuration and then exposed as environment variables. To make them visible to build scripts, they need to be whitelisted in `build.script_env` of `meta.yaml`. This can, e.g., be used to collect coverage statistics during a build or test and upload them to sites such as coveralls.
Fixes #1162.
I tested this in actual CI runs for
* arb-feedstock which builds on [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/arb.svg)](https://anaconda.org/conda-forge/arb): https://github.com/conda-forge/arb-feedstock/pull/20
* and pyeantic which actually wants to set additional secrets: https://github.com/flatsurf/pyeantic/pull/41 …
> Make CI secrets configurable

- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
- news/rm_opt_ghc_linux_azure.rst
- tests/test_configure_feedstock.py
The content in `/opt/ghc` seems to take up a fair bit of space on the Linux images and we don't use it. As it limits the memory available for jobs that are more memory hungry and doesn't seem to take long to clear, go ahead and remove `/opt/ghc` at the start of the job.
cc @beckermr @isuruf @h-vetinari @pearu
Checklist
xref: https://github.com/conda-forge/faiss-split-feedstock/pull/10
xref: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/105
xref: https://github.com/conda-forge/omniscidb-feedstock/issues/5
xref: https://github.com/conda-forge/faiss-split-feedstock/pull/5
> Remove `/opt/ghc` on Linux

- conda_smithy/templates/run_docker_build.sh.tmpl
- news/pass-cpu-count-to-docker.rst
Many recipes use `make -j${CPU_COUNT}`.  When running `build-locally.py`, it's convenient to be able to specify the `CPU_COUNT` environment variable manually.  This PR passes that variable from the host environment to the docker container.
---
Checklist
> Pass CPU_COUNT to the docker container

- conda_smithy/feedstocks.py
- news/clone_all_return_repos.rst
Checklist
Changed return type of `feedstocks.clone_all()` from `None` to the list of repositories cloned.
I also changed `feedstocks_clone_all_handle_args` so it does not print the list of Repository objects when using the entry point.
> Clone all return

- conda_smithy/cli.py
- news/rotate-anaconda-token-update.rst
This PR adds more information in the printed log after the token is rotated. Useful when running it in a batch mode for many feedstocks.
Checklist
> More info regarding rotated anaconda token

- conda_smithy/ci_register.py
- news/prevent_travis_get_repo_info_keyerror.rst
Snippet modified from deprecated add_project_to_travis func
> ci_register.py: Guard against KeyError from empty travis_get_repo_info

- conda_smithy/templates/travis.yml.tmpl
- news/idle_timeout_minutes_travis.rst
This is for #1363 
As it's re-adding already claimed config then I'm not sure it deserves a NEWS entry?
> conda-forge.yml: Re-add idle_timeout_minutes support for Travis

- conda_smithy/ci_register.py
- news/empty_anaconda_token
Raise a RuntimeError, inline with rotate_anaconda_token()
Example pre this PR when there is no token in the env:
```
Traceback (most recent call last):
File "/home/tom/conda-project/miniforge3/envs/test/bin/conda-smithy", line 10, in <module>
sys.exit(main())
File "/home/tom/conda-project/miniforge3/envs/test/lib/python3.7/site-packages/conda_smithy/cli.py", line 592, in main
args.subcommand_func(args)
File "/home/tom/conda-project/miniforge3/envs/test/lib/python3.7/site-packages/conda_smithy/cli.py", line 243, in __call__
ci_register.add_token_to_travis(owner, repo)
File "/home/tom/conda-project/miniforge3/envs/test/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 515, in add_token_to_travis
"env_var.value": anaconda_token,
NameError: name 'anaconda_token' is not defined …
```
> ci_register.py: Handle NameError when anaconda_token isn't defined

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/azure_artifacts_conda_pkgs.rst
- tests/test_configure_feedstock.py
Checklist
This adds steps to the Azure pipeline templates that save the conda build output directory as an Azure pipeline artifact. This is useful for inspecting the build result and testing built packages before they are published. I think I've set it up so that the artifact publishing won't run if the directory doesn't exist, and also that it will still run even if the build fails (making the work directory available, for example). I tested this on one recipe, https://github.com/conda-forge/soapysdr-module-rtlsdr-feedstock/pull/1, and it works at least when the builds succeed. Wider testing would probably be wise.
This is an evolution of a similar feature that has already been implemented for conda-forge/staged-recipes (https://github.com/conda-forge/staged-recipes/pull/11827, …
> Publish conda build artifacts on Azure as pipeline artifacts.

- conda_smithy/lint_recipe.py
This adds a lint for staged recipes to warn when `recipes/example/meta.yaml` has been removed. I see this not infrequently when reviewing PRs there.
I'm not super familiar with the linting code, so I'm not 100% sure that I've done this correctly. Feedback appreciated.
> Add lint for deleting staged_recipes example meta.yaml

- conda_smithy/configure_feedstock.py
- news/upload_packages_config.rst
Re-enable upload_packages to be set to False on a per provider basis
to override default upload logic. Also remove the non parsed
default entry for Azure.
This will need an accompanying update to the docs website. I'm not sure if makes sense keeping the config option as `upload_packages` and requiring the user to set it `False` to opt-out,  maybe replacing it with `disable_upload` and requiring an explicit `True` is a better opt-in.
Also as this configurability was seemingly lost, maybe adding a test is worthwhile.
https://github.com/conda-forge/conda-smithy/issues/1371
> configure_feedstock.py: Re-add per provider parsing of upload_packages

- conda_smithy/lint_recipe.py
- news/fix_delete_example_recipe_lint.rst
I believe this will fix the incorrect linting that was merged in #1381 and is shown to not work in https://github.com/conda-forge/staged-recipes/pull/12364#issuecomment-672339382
This is not tested (as was the previous PR obviously), but looking at https://github.com/conda-forge/conda-smithy/blob/0baf80c2a3284ed91b3045591b0b1cea4cc10ed3/conda_smithy/lint_recipe.py#L570-L572
it seems like this will work. The originally hard-coded path assumed that the working directory was inside the repo, but I think it is probably above the repo (so `staged-recipes/recipes/example/meta.yaml` would have worked). 
Two questions:
- Is there are way to easily test this?
- Will the back ticks around the file path in the lint message render correctly? The parentheses in the original PR seem strange in …
> Fix lint for deleting staged_recipes example meta.yaml

- conda_smithy/configure_feedstock.py
- news/remove_upload_script.rst
'upload_or_check_non_existence' is no longer called directly in
templates and the config option is not evaluated.
> configure_feedstock.py: Remove unused forge_config["upload_script"]

- conda_smithy/cli.py
- news/remove_unneeded_default.rst
`action="store_false"` already defaults to True if not given
> cli.py: Remove unneeded set_default() for --without-$CI args

- README.md
- conda_smithy/ci_register.py
- conda_smithy/cli.py
- news/optional_anaconda_token.rst
The default behaviour of register-ci requires an Anaconda/Binstar
token to be provided. Allow this to be overridden & warn of the
consequences. update-anaconda-token & upload_package in
conda-forge-ci-setup already handle BINSTAR_TOKEN not being set
on the provider.
This is for issue https://github.com/conda-forge/conda-smithy/issues/1373
> cli.py: Add `--without-anaconda-token` option to register-ci command

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/appveyor.yml.tmpl
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- conda_smithy/templates/build_steps.sh.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- news/remote_ci_setup.rst
Default to `conda-forge-ci-setup=3` and expand string in CI
templates. Value can be overriden by user to install & resolve
dependencies of an alternative remote setup package. This should
not change the default behaviour of `local_ci_setup`
I'm happy to change the variable name or append `conda-forge::` to the default package if it's preferred to be explicit
This is part of https://github.com/conda-forge/conda-smithy/issues/1366
If this is merged then I'll also send a PR to the docs repo.
> configure_feedstock.py: Add remote_ci_setup field to default config

- conda_smithy/templates/README.md.tmpl
* conda_smithy/templates/README.md.tmpl:
> Only add new lines directly after new content

- .pre-commit-config.yaml
- conda_smithy/configure_feedstock.py
- news/concurrency.rst
Increase the number of concurrent builds on linux to account for emulated builds and the increased python matrix
> Up the maximum number of builds on linux

- conda_smithy/configure_feedstock.py
- news/TEMPLATE.rst
- news/comprend.rst
Checklist
This change appears to be needed to ensure that smithy generates a new CI job for each compiler variant. Normally, compilers appear in build so if you have more than one compiler variant in a single CI job, conda build will not make all of the outputs. 
This is happening in https://github.com/conda-forge/mpich-feedstock/pull/47
> ENH make sure each compiler version gets a CI job

- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/fix_too_long_azure_artifact_names.rst
The job ID is pretty long whereas the build ID is short, and if the artifact name is too long (~100 characters? I could not find docs) then it will not be downloadable. This helps, but does not prevent, that situation. I also like using the build ID better because it is the same for all of the artifacts of that build and I can move it to before the config string in the artifact name to aid in sorting and possible string truncation.
See the Linux and macOS artifacts at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=202223&view=artifacts&type=publishedArtifacts versus the same with this change at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=202325&view=artifacts&type=publishedArtifacts. The long names in the first instance lead to a …
> Use build ID instead of job ID to name Azure artifacts.

- conda_smithy/configure_feedstock.py
- news/windows-comments.rst
Checklist
[This harmless error in the logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235346&view=logs&j=a120d53e-9902-50f5-2ab9-d17061711ef5&t=921e1dd2-e1cc-500e-c406-a0376d4b804b&l=12) is due to this non-supported comment syntax on [this other line](https://github.com/jaimergp/conda-forge-ci-setup-feedstock/blob/cuda-windows/.azure-pipelines/azure-pipelines-win.yml#L132).
> # is not a comment symbol on Windows

- conda_smithy/templates/run_docker_build.sh.tmpl
- news/delegated-docker-volumes.rst
This saves some CPU cycles and can make a drastic performance difference on macOS.
Checklist
> Use delegated docker mounts

- .github/workflows/tests.yml
- news/setup-miniconda-v2.rst
`add-path` and `set-env` commands are deprecated and will be disabled on November 16th. More information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Checklist
> Update `setup-miniconda` to v2

- conda_smithy/templates/README.md.tmpl
- news/dead-link.rst
Checklist
This should fix the dead link in the feedstock readme. I tried to find the new docs equivalent to the old link but let me know if it should link to a different section of conda-build.
> Update feedstock readme template to new conda docs

- conda_smithy/templates/build_steps.sh.tmpl
- news/cross-debug.rst
Without this you get an error like:
```
+ conda debug /home/conda/recipe_root -m /home/conda/feedstock_root/.ci_support/linux_ppc64le_.yaml --no-test --clobber-file /home/conda/feedstock_root/.ci_support/clobber_linux_ppc64le_.yaml
usage: conda-debug [-h] [-V] [-n] [--python PYTHON] [--perl PERL] [--numpy NUMPY] [--R R_BASE] [--lua LUA] [--append-file APPEND_SECTIONS_FILE]
[--clobber-file CLOBBER_SECTIONS_FILE] [-m VARIANT_CONFIG_FILES] [-e EXCLUSIVE_CONFIG_FILES] [--use-channeldata] [--variants VARIANTS]
[-c CHANNEL] [--use-local] [--override-channels] [--repodata-fn REPODATA_FNS] [-p PATH] [-o OUTPUT_ID] [-a]
recipe_or_package_file_path
conda-debug: error: unrecognized arguments: --no-test
```
>  Fix running ./build-locally.py --debug with cross-compilation 

- conda_smithy/configure_feedstock.py
- news/ts.rst
- tests/conftest.py
- tests/test_configure_feedstock.py
migrator_ts and migration_ts were both used in conda-smithy
Checklist
> migrator_ts was removed in favour of migration_ts

- conda_smithy/configure_feedstock.py
- conda_smithy/variant_algebra.py
- news/key_add.rst
- tests/test_variant_algebra.py
Checklist
This PR does two things. First, it allows key_add migrators to add more than one key. Second, it fixes a bug where smithy is applying the recipe's CBC on top of the global pinning file + recipe CBC + migration. Sometimes this causes the changes from the migration to be removed when rerendering happens.
> ENH add multiple variants in key_add

- conda_smithy/configure_feedstock.py
- news/os_version.rst
- tests/test_configure_feedstock.py
Checklist
As per requested by @isuruf, this PR makes `os_version` in `conda-forge.yml` recognized by Conda-Smithy. Currently it is used to distinguish `cos6`/`cos7`:
```yaml
os_version:
linux_64: cos7
```
~~Currently tested with the cudnn-feedstock, with the cuda_111_112 migrator manually added. The rerendering is done without error, but it generates a ton of extra files on Windows, which shouldn't be there. Am I missing something here, or should I also copy over the cuda windows migrator?~~
**UPDATE**: fixed this silly mistake in 936cf8a. 
Another thing: where should the test go?
cc: @beckermr
> Support `os_version` in `conda-forge.yml`

- conda_smithy/configure_feedstock.py
- news/avoid-too-long-filenames.rst
- tests/conftest.py
- tests/test_cli.py
- tests/test_configure_feedstock.py
Replace config filenames by their short versions if filesystem limits
are approached.
Checklist
In https://github.com/conda-forge/rust-activation-feedstock/pull/8 we added additional keys to a `zip_keys` group which broke re-rendering since the config filenames grew to big.
> Fix "File name too long" error for many zip keys

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/github-actions.tmpl
- news/github_actions.rst
- tests/test_configure_feedstock.py
Checklist
Fixes https://github.com/conda-forge/conda-smithy/issues/1361
> support github actions as a CI provider

- conda_smithy/configure_feedstock.py
- news/shorter-config-name.rst
Checklist
Would fix issue in https://github.com/conda-forge/rust-activation-feedstock/pull/8.
`run_docker_build.sh`/`build_steps.sh` create `"$ARTIFACTS/conda-forge-build-done-${CONFIG}"` files. We checked for max filename length with `+ ".yaml"` before, but we also have to consider the longer `"conda-forge-build-done-"` prefix.
> Fix too long filenames for build done canary files

- conda_smithy/templates/README.md.tmpl
- news/mention-strict-channel-priority.rst
Checklist
Closes https://github.com/conda-forge/conda-smithy/issues/1348
Bring the README template for feedstocks in line with the [conda-forge
documentation][1] by mentioning how to configure 'strict' channel
priority after adding the `{{ channel_name }}` channel.
[1]: https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge
> Mention 'strict' channel priority in feedstock READMEs

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/azure__use_short_config_name_at_artifact_upload.rst
This resolves issue #1477 describing failing builds for feedstocks with long artifact names due to a lot of build variants for e.g. python, numpy and arrow like `snowflake-connector-python`. Failing build due to non unique artifact name at artifact upload: https://github.com/conda-forge/snowflake-connector-python-feedstock/runs/2476458561
Checklist
> Shorten artifact name length by using config_short_name in azure.store_build_artifacts

- conda_smithy/lint_recipe.py
- news/validate_noarch_value.rst
- tests/test_lint_recipe.py
Checklist
I don't see any documentation for ``news`` so I'm not sure what to do there...
In one of my recipes I accidentally put `noarch: true` instead of `noarch: python`, and I experienced strange behavior on WIndows where the package showed up in `conda list` but not `pip freeze`. I'm not sure whether or not the bad `noarch` value was to blame, but since the value was not being validated, I figured that it should be added to the linter.
In this commit, I refactored `build_section.get("noarch")` to have its own variable `noarch_value`. Then I verify that the value is either `"python"` or `"generic"`. I also add a test.
> Validate noarch value

- conda_smithy/configure_feedstock.py
- news/ubuntu_latest_in_azure_template.rst
We run the actual build anyways in the Docker container and thus the host operating system has a very minor influence on the whole build process.
Fixes #1481
Checklist
> Use ubuntu-latest in Azure Pipelines template

- conda_smithy/lint_recipe.py
- news/output_test_scripts.rst
- tests/test_lint_recipe.py
This PR fixes #1485 by adding support for finding `test/script` in outputs.
Checklist
> Add detection of output test scripts

- conda_smithy/anaconda_token_rotation.py
- conda_smithy/ci_register.py
- conda_smithy/cli.py
- conda_smithy/configure_feedstock.py
- conda_smithy/utils.py
- news/forge_yml_alternate.rst
- tests/test_anaconda_token_rotation.py
- tests/test_cli.py
- tests/test_configure_feedstock.py
This makes it possible to specify the feedstock configuration in a file that is named/located at something other than "conda-forge.yml". Feedstock init and ci-skeleton still use the default name, but if a user decides to manually move/rename the config file, there is now a "--feedstock_config" option for appropriate smithy subcommands so that they can point to the alternate path. Clearly this is not useful for conda-forge itself, but it could be used for personal feedstocks and I have a CI application (below).
One test has been added for configure_feedstock to ensure that the configuration can be loaded from an alternative path.
The reason I'd like to see this get merged (or something that accomplishes the same) is that I'm trying to set up some CI that uses conda-smithy (i.e. the …
> Add option to use different path for feedstock config yaml

- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/fix-win-suppress-variables.rst
Checklist
* [ x] Added a ``news`` entry
I am playing around with the `secrets` option in `conda-forge.yml` in a recipe and I noticed that the environment variable is displayed on the Windows builds but are `<hidden>` in the macOS and linux builds.
This adds the `--suppress-variables` flag to the `conda-build` command in the Windows script template.
I tested this by manually adding the flag to my `.azure-pipelines/azure-pipelines-win.yml` file.
I also added the flag for `mambabuild`, but I did not test that.
Let me know if any changes are necessary. Thanks!
> Add --suppress-variables flag to Windows template

- conda_smithy/configure_feedstock.py
- news/azure-max-parallel.rst
Checklist
As discussed in the last core call, and specially relevant to the CUDA matrix explosion, it would be beneficial to limit the amount of parallel jobs each feedstock adds to the queue (limited to 200 parallel jobs across conda-forge). For example, OpenMM adds 78 Azure jobs for every push 😬 
In this PR, I implemented a workaround based on the [`job.strategy.maxParallel` configuration key](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#define-a-single-job) (see the full example a bit later in that section). Smithy will add this key to the config if the number of configs exceeds the established threshold (50 by default), with a value proportional to the amount of configs found for that OS (Linux, MacOS, Windows).
This is the split …
> Limit the amount of parallel jobs running at the same time

- conda_smithy/templates/run_osx_build.sh.tmpl
- news/run_osx_build_arm64.rst
Checklist
Without this change, we would always cross-compile when doing a build using `./build-locally.py`. For `tensorflow` I actually need native compilation to get things working.
> Support using build-locally.py on osx-arm64

- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/new_py_win.rst
Not entirely sure why this is pinned to Python 3.6 (maybe someone can clarify that). Anyways seems like we could use a newer version of Python and 3.8 has been supported for a while in conda-forge. So seems like a good choice. Opening to other pinnings (or dropping the pinning though guessing this is done to protect against brand new unmigrated `python` versions).
Checklist
> Bumps the `python` version on Windows to 3.8

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
- conda_smithy/templates/azure-pipelines-osx.yml.tmpl
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- conda_smithy/templates/create_conda_build_artifacts.bat.tmpl
- conda_smithy/templates/create_conda_build_artifacts.sh.tmpl
- conda_smithy/templates/github-actions.tmpl
- news/build_artifacts.rst
This fixes some issues with the Azure artifacts and adds artifacts for the Github Actions provider.
1. It ensures artifact names are unique when a job needs to be restarted (#1430). This can happen because of infrastructure failures and so the artifacts may actually change despite the job being the exact same.
2. It fixes uploading artifacts for failed builds where currently the uploading step fails because of broken symbolic links.
3. When downloading an artifact, the zip file is generated by request; if the the artifact is large (such as currently when a build fails), then this can take a long time and, quite frequently, the download times out. Instead, this uses a zip file as the artifact in those cases, so that generation and download is much faster. The old behavior is maintained …
> Build artifacts fixes and improvements

- conda_smithy/templates/README.md.tmpl
Prefer to use secure https links for https://numfocus.org <s>and https://www.w3.org/2000/svg</s>
Not modified in this PR are files in `tests/recipes/click-test-feedstock`, as it's part of the test suite. Maybe someone wants to follow-up with that?
> Use https for NumFOCUS

- conda_smithy/configure_feedstock.py
- news/arm_azure.rst
> linux-aarch64 builds default is changed from native (drone) to emulated (azure)

- conda_smithy/templates/github-actions.tmpl
- news/fix-docker-image-typo.rst
Checklist
Fixed typo in GitHub Actions template, where `DOCKERIMAGE` was wrongly specified in the matrix configuration. The CI step and its corresponding script expect `DOCKER_IMAGE`.
> GitHub Actions: Fix `DOCKERIMAGE` env var typo

- conda_smithy/configure_feedstock.py
- news/add-CF_CUDA_ENABLED.rst
- tests/conftest.py
- tests/test_configure_feedstock.py
From the discussion in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1708, and particularly, this [description](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1708#issuecomment-943627914) of what to do.
I couldn't think of a way to detect `compiler('cuda')`, because - AFAICT - the ingestion of `meta.yaml` is done a couple lines above by `conda_build.api.render`, and after that, the jinja-functions will have already been filled in.
I think it's a feasible workaround though to just use `r"^nvcc.*"` (as a build requirement) as a stand-in for detecting that.
I haven't yet written a test for it, this is more to check whether I'm on the right path.
CC @isuruf @jakirkham
> set CF_CUDA_ENABLED=True if `compiler('cuda')` is detected in meta.yaml

- conda_smithy/cli.py
- conda_smithy/feedstock_io.py
- news/get_repo_root.rst
- tests/test_feedstock_io.py
This feature enables us to run `conda-smithy` commands from anywhere
inside a feedstock repo, instead of always `cd`-ing into the root dir or
specifying it explicitly via `--feedstock_directory`
Checklist
> Add utility function feedstock_io.get_repo_root(path)

- conda_smithy/templates/automerge.yml.tmpl
- conda_smithy/templates/webservices.yml.tmpl
- news/wbeservices.rst
Checklist
This PR adds a new token to the GHA template for rendering and the one for automerge. Eventually, the admin bot will add this token to the repos secrets as needed. For now, I have tested things and it does no harm being here. I have also used code from Isuru to adjust the rendering bot to not change girhub action workflow files unless the token it has allows it. Thus we can merge and release changes here without an issue.
> ENH add new token to GHA template

- conda_smithy/templates/run_docker_build.sh.tmpl
- news/cd_run_docker_build.rst
Redirects the output of `cd` to /dev/null for FEEDSTOCK_ROOT. This fixes
a bug where `cd` has an output to stdout that then gets included in
FEEDSTOCK_ROOT.
This change mirrors the command used for THISDIR.
Checklist
> run_docker_build.sh: discard output of cd command

- conda_smithy/configure_feedstock.py
- news/drop_defaults_channel_sources.rst
This is already effectively dropped in conda-forge-pinning ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1954 ). The value here is a fallback. Nevertheless it is good to be consistent here to avoid confusion. So this matches what is in conda-forge-pinning.
<hr>
Checklist
> Drop `defaults` from `channel_sources`

- conda_smithy/cli.py
- news/fix-cli-args.rst
Looks like argument is registered to `args['github-actions']` but checks for `args.github_actions`. Converting should do the trick.
Resolves #1587 
This is a draft - probably should also add a test first.
> [fix] feedstock token registration

- conda_smithy/configure_feedstock.py
- news/travis.rst
- tests/test_configure_feedstock.py
Checklist
due to how travis CI now counts CI minutes, we can no longer use it easily on windows, osx or linux-64. It can be used easily on pcc64le, aarch64 and s390x.
> DEP deprecate using Travis CI usage on win-*, osx-* or linux_64

- conda_smithy/configure_feedstock.py
- news/add-noarch-platform.rst
- tests/test_configure_feedstock.py
Checklist
References:
- fixes #1449  
- would enable _cleanly_ fixing https://github.com/conda-forge/pywin32-on-windows-feedstock/issues/1 
- [gitter thread](https://gitter.im/conda-forge/conda-forge.github.io?at=622904f3d1b64840db5b7542)
- docs: https://github.com/conda-forge/conda-forge.github.io/pull/1624
Changes:
> add noarch_platforms to conda-forge.yml

- conda_smithy/templates/README.md.tmpl
- news/travis.rst
- tests/recipes/click-test-feedstock/README.md
Travis now uses app.travis-ci.com and we only use linux on it.
Checklist
> ENH update travis url and badge image

- conda_smithy/templates/circle.yml.tmpl
- news/migrate_circle_linux_image.rst
'machine: true' in circleci will stop working on 5/31/22 per:
https://circleci.com/blog/ubuntu-14-16-image-deprecation/
Upgrade circle to using latest ubuntu ala azure. Refrained from
making the images configurable per feedstock like Azure because
I don't know if that's worth adding the extra code since most
feedstocks don't use circle
Checklist
> update circle away from deprecated default image

- .pre-commit-config.yaml
Checklist
This updates `black` to a stable version that doesn't fail to install.
References
- from #1619
> update pre-commit to black stable

- conda_smithy/templates/build_steps.sh.tmpl
- news/build_local_cache.rst
Adding this key to .condarc moves the conda package cache out of the container and into build_artifacts on the local disk. This means that repeated local builds of the same recipe won't have to redownload all of the dependency packages.
Addresses some of the concerns of https://github.com/conda-forge/conda-smithy/issues/1533
Related:
https://docs.anaconda.com/anaconda/user-guide/tasks/shared-pkg-cache/
Checklist
> NEW: Reuse package cache when building locally

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/README.md.tmpl
1. Avoid calling conda_build.api.render and use render_info
2. Do not send a ruamel.yaml object into jinja to avoid costly
serialization/deserialization.
Checklist
> Make render_README faster

- conda_smithy/lint_recipe.py
- news/fix-pin_compatible.rst
in #1624, `pin[-1]` was incorrect if build pattern is specified, picking up the build string instead of the package name. The message has the right index, but the test didn't match what the message was claiming. Fixing the test to match the message allows lint to pass.
Incorrect lint example: https://github.com/conda-forge/petsc-feedstock/pull/146#issuecomment-1169836525
Checklist
> fix index for pin_compatible lint

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- news/gh-1684-Add-py-lief-0.12-to-remote_ci_setup-for-now.rst
Checklist
Add `py-lief<0.12` to `remote_ci_setup` for now
due to current ` osx-*` segfault issues, ref:
https://github.com/conda-forge/conda-forge.github.io/issues/1823
Feedstocks which require LIEF 12+ can add
```yaml
remote_ci_setup:
- conda-forge-ci-setup=3
- py-lief>=12
```
to their `conda-forge.yml`
> Add py-lief<0.12 to remote_ci_setup for now

- conda_smithy/templates/README.md.tmpl
This updates the badge URLs in the README template for Azure when there are OS specific variants to display the proper badge per job. Currently, they say _"unknown"_ for each specific job. I tested this on my local machine using [`pandas-feedstock`](https://github.com/conda-forge/pandas-feedstock).
> Fix Azure urls in details

- conda_smithy/templates/circle.yml.tmpl
- news/circle-native-aarch64.rst
This allows for using CircleCI for some problem case builds that struggle on travisCI and under emulation.
Checklist
> CircleCI support aarch64 native runners

- conda_smithy/lint_recipe.py
- news/noarch_platforms.rst
- tests/recipes/noarch_platforms/conda-forge.yml
- tests/recipes/noarch_platforms/recipe/meta.yaml
- tests/test_lint_recipe.py
> allow selectors in noarch_platforms recipes

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/anaconda_upload_temp.rst
Checklist
See https://github.com/conda-forge/kubo-feedstock/issues/5#issuecomment-1335504503 :
> I didn't figure out the root cause regarding the temp file access/`anaconda upload` problems on Windows.
> Meaning, I still don't know what causes access right changes to the temp folder during `conda-build` runs.
> But at least I now know why we see the upload problems lately:
> For the `.conda` rollout we updated to `anaconda-client>=1.11` since it handles `.conda`.
> The previously used `anaconda-client=1.8` didn't use a temp folder, hence we didn't have the issue then.
> Now, `binstar_client.inspect_package.conda.inspect_conda_package` extracts the package's `info` component to a temporary directory.
> Since something during our build changes permissions in `%TEMP%`, uploading `.conda.` …
> Use a custom %TEMP% directory to avoid upload permission errors on Windows.

- conda_smithy/github.py
- news/teams.rst
The person on the token used to make the team gets added by default. This means our bots appear as team members. This PR fixes that so that the bots are not on the teams. This is a potential security risk since it escalates permissions. 
Checklist
> BUG always check team membership even when making the team

- conda_smithy/configure_feedstock.py
- news/skip_render_skips_github_services.tst
Checklist
[skip_render can skip github_actions_services](https://github.com/conda-forge/conda-smithy/commit/6fa380ce60f0fa388dc9e0866bb82df25dc888f3) 
Also enhanced it so that you can skip rendering anything
below a directory by specifying the directory name (without
For example, if '.github' is in the skip_render list, all
files inside .github/ will be skipped.
Logging now tells you when rendering was actually skipped
as opposed to just what was read from the config.
> Skip render tuneup

- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/gh-1711-use-python3.10-for-windows-on-azure.rst
This avoid downgrading the base environment from 3.9 to 3.10
Checklist
> Use python 3.10 on windows Azure CI to match miniforge

- conda_smithy/templates/create_conda_build_artifacts.bat.tmpl
- conda_smithy/templates/create_conda_build_artifacts.sh.tmpl
- news/gha-set-output.rst
Checklist
I noticed some warnings due to [a change in how variables are set for subsequent steps with GitHub Actions](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). This follows the recommendation given at that link to switch to the new behavior and prevent eventual job failures after May 31, 2023.
Tested by re-rendering locally with this change and confirming that the artifacts are saved on GitHub Actions:
https://github.com/ryanvolz/gr-fosphor/actions/runs/3633811395
> Replace ::set-output with redirect to $GITHUB_OUTPUT on GitHub Actions

- conda_smithy/configure_feedstock.py
- news/vs2022.rst
Came up during review of https://github.com/conda-forge/conda-forge.github.io/pull/1878
CC @wolfv @isuruf
> switch default image on windows to windows-2022

- conda_smithy/templates/README.md.tmpl
- news/readme_headers_multiple_outputs.rst
- tests/test_cli.py
Checklist
For recipes with multiple outputs, the feedstock README headers aren't formatted correctly because of a missing empty line. Thus the previous line is formatted as a header. As an example, see the [arrow-cpp-feedstock README](https://github.com/conda-forge/arrow-cpp-feedstock#readme), where the summary is incorporated into the header:
With this PR, a blank line is included before the header of each output. It has no effect on recipes with a single output.
> Fix README headers for recipes with multiple outputs

- conda_smithy/lint_recipe.py
- news/add_linting_for_obsoleted_outputs.rst
In the context of https://github.com/conda-forge/conda-forge.github.io/issues/1894 & https://github.com/conda-forge/conda-forge.github.io/issues/1073, I think it would be good to enforce (or at least nudge) that obsolete outputs aren't actually used anymore in the wild.
We already completed `abseil-cpp` -> `libabseil` & `grpc-cpp` -> `libgrpc`, while `arrow-cpp` -> `libarrow` is in flight (due to supporting 4 versions in conda-forge, it needs more time), and `boost-cpp` -> `libboost` is being planned.
But aside from larger libs, maintainers might individually obsolete output names on their feedstocks, with no real mechanism to enforce it. For example, it would be good to get rid of `pytorch-cpu` & `pytorch-gpu`, that exist solely for compatibility with packages that were published by the …
> add linter-rule for now-obsolete ouput names (e.g. after renaming)

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/github-actions.tmpl
- news/gha_max_par_opt.rst
Provide a `conda-forge.yml` option to configure the number of GHA jobs that can be used in parallel. Default is to leave this unspecified. When set to a non-zero value, this is added to the appropriate field in the GHA workflow YAML.
<hr>
Checklist
> Provide GHA option to set maximum parallel jobs

- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
- news/clean_disk.rst
- tests/test_configure_feedstock.py
Checklist
This frees up more disk space on the linux image. Items for deletion are taken from
https://github.com/easimon/maximize-build-space
https://github.com/choderalab/espaloma/pull/176/files#diff-17e3400d876978d12bbad517dcf82312b54fa62723408b1ce011b2755458bdafR36-R62
For reference, the linux image (`ubuntu-22.04`) contains software listed in https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
> Clean up more disk space

- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
Checklist
This changes #1747 so that `apt-get` is used instead of `aptitude`. `aptitude` is not in the default image.
> Change aptitude to apt-get

- conda_smithy/templates/github-actions.tmpl
- news/gha_free_disk_space.rst
Provide a similar option for GHA to cleanup images before builds as was done on Azure. As the same image is used in both cases, the same approach works in both cases.
Checklist
> Add option to cleanup GHA images

- conda_smithy/lint_recipe.py
- news/noarch-platforms-lint-selectors-operators.rst
- tests/recipes/noarch_platforms/recipe/meta.yaml
Checklist
Comes from https://github.com/conda-forge/conda-smithy/pull/1682#issuecomment-1306284590
> allow operators in noarch selector lint

- conda_smithy/configure_feedstock.py
- news/fix_swapfile_size.rst
Checklist
Should make sure that `swapfile_size` is not accidentally added to the Azure settings for the matrix.
> Ensure `swapfile_size` is not added to the Azure job settings

- conda_smithy/feedstock_content/.scripts/logging_utils.sh
- news/fix_travis_ci_fold_quoting.rst
It should be `"\\r"` or `'\r'`, but not `'\\r'`.
Checklist
> Correct escaping of \r in the Travis CI logging utilities

- conda_smithy/utils.py
- news/1726-undefined-null-str
> Add __str__ for NullUndefined

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/build_steps.sh.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- conda_smithy/templates/run_win_build.bat.tmpl
- news/1762-conda-install-tool
Checklist
Part of the conda-libmamba-solver deployment in https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/275. Documented at https://github.com/conda-forge/conda-forge.github.io/pull/2003.
> Implement `conda_install_tool` to let users choose `{conda,mamba} install`

- conda_smithy/templates/run_win_build.bat.tmpl
- news/1763-catch-negative-exit-code
Checklist
Supersedes #1704. The formula `if errorlevel 1` actually means "if the exit code is >=1", so it doesn't catch `-1` and other negative exit codes. This can happen in conda-build when it segfaults during the linkage analysis steps, for example.
Exit codes in CMD are tricky and there are many gotchas. Since we can afford to enable delayed expansion, this is relatively robust. See [this SO answer](https://stackoverflow.com/questions/34936240/batch-goto-loses-errorlevel/34937706#34937706) for (way ) more info if you are curious.
> Windows: Catch all non-zero exit codes (negative values too)

- .github/CODEOWNERS
This repository is maintained by @conda-forge/core and thus I would like to also list them automatically as a reviewer.
> Create CODEOWNERS with @conda-forge/core

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/build_steps.sh.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- conda_smithy/templates/run_win_build.bat.tmpl
- news/1762-conda-install-tool
Checklist
Round of fixes found while tesrting for: #1767
- `conda update` is receiving specs with version constraints (`conda update conda-forge-ci-setup=3` fails). `update` and `uninstall` expect name only specs.
- Checks for `conda_solver` didn't check for value, only presence
- Configure `solver` here instead of `conda-forge-ci-setup` so the first `conda` calls respect the configured value (conda-forge-ci-setup arrives "too late" for those initial calls). In Docker we use `conda config ...` because it's a Docker instance and it's disposable. In macOS and Windows we set an env var so the changes are only visible to that script and do not leak into local configurations when run outside CI.
- Ensure strict channel priority on Linux and macOS to prevent packages from `defaults` leaking in …
> Follow up for `conda_install_tool` and `conda_solver` settings

- conda_smithy/templates/run_win_build.bat.tmpl
- news/1770-feedstock-name
Checklist
A bug introduced in #1761, where `FEEDSTOCK_NAME` on Azure was being set to the whole thing (e.g. `conda-forge/package-feedstock`) instead of just `package-feedstock).
This is causing failing uploads on Windows.
> fix how `FEEDSTOCK_NAME` is set on Windows

- conda_smithy/templates/build_steps.sh.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- conda_smithy/templates/run_win_build.bat.tmpl
- news/1771-conda-uninstall
Checklist
Seen in https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/276. `mamba uninstall --force` ignores `--force` and removes more packages than intended.
xref https://github.com/mamba-org/mamba/issues/1523
> always use `conda` for uninstalls

- conda_smithy/configure_feedstock.py
- news/1775-quotes
- tests/test_configure_feedstock.py
> Fix `MatchSpec` parsing when `remote_ci_setup` specs are quoted

- conda_smithy/configure_feedstock.py
- news/no-warn-if-no-check.rst
Checklist
The average runtime of this warning is 7s for me. If I explicitly don't want to do this check, I also don't want to pay the time for it.
> Don't fetch the smithy version if we don't check

- conda_smithy/configure_feedstock.py
- news/cache-c-f-p.rst
Checklist
This brings down the rerender of `pydantic-core-feedstock` (simple Python matrix) from 22s to 10s in my case. As this shaves off a constant, this will have less of a noticeable impact on larger feedstocks but is already a good quality of life improvement for me.
> Cache conda-forge-pinning 

- conda_smithy/configure_feedstock.py
- news/xdg-cache-dir.rst
Checklist
When XDG_CACHE_HOME was set, a string was returned, but consumers of get_cache_dir assume it returns a Path object.
> ensure cache_dir is a Path when XDG_CACHE_HOME is set

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/README.md.tmpl
- news/1752-readme-channels.rst
Fixes some bugs from https://github.com/conda-forge/conda-smithy/pull/1752
> Fix rendering README

- conda_smithy/configure_feedstock.py
- news/libmamba.rst
- tests/test_configure_feedstock.py
> Switch to conda-build with libmamba solver

- conda_smithy/lint_recipe.py
- news/maint_staged.rst
- tests/test_lint_recipe.py
> Add linter check for willing maintainers

- conda_smithy/templates/README.md.tmpl
- news/fix-name.rst
This should prevent confusion compared to https://anaconda.cloud
Checklist
> Fix name of anaconda.org in README template.

- conda_smithy/configure_feedstock.py
- news/conda_build_tool-mambabuild.rst
- tests/test_configure_feedstock.py
until https://github.com/conda/conda-libmamba-solver/issues/393 is fixed
Checklist
closes gh-1805
> Set conda_build_tool: mambabuild as default again

- conda_smithy/templates/run_win_build.bat.tmpl
- news/emulator-win.bat
> Don't skip tests if there is an emulator

- conda_smithy/templates/build_steps.sh.tmpl
- conda_smithy/templates/run_docker_build.sh.tmpl
- news/fix_local_submodule_builds.rst
Fixes https://github.com/conda-forge/conda-smithy/issues/1825
In `conda-smithy` version `3.28.0` logic was added to store metadata about CI ( https://github.com/conda-forge/conda-smithy/pull/1577 ) like the `sha` of the feedstock that was used to build. As the `sha` variable may not be set when running locally, logic was added with the container to determine this by running `git rev-parse` to fill in this value
https://github.com/conda-forge/conda-smithy/blob/00fcb77e51b8d69d8acfbeaca2da5b02a8b0a34e/conda_smithy/templates/build_steps.sh.tmpl#L86-L90
While this works in the simple case of cloning a feedstock directly, it does not work in the case of building a feedstock from a submodule as is the case with [the `feedstocks` repo]( https://github.com/conda-forge/feedstocks ). This is due to …
> Fix local builds of feedstock submodules

- conda_smithy/configure_feedstock.py
- news/fix-squished-zip_key-ordering.rst
Checklist
Fixes gh-1459
Fixes the `conda-smithy` part affecting gh-1782 (that issue needs further adjustments to the recipe and/or `conda-build`).
gh-1459 is an old issue such that the initial discussion refers to old code.
A recent analysis regarding current code is at https://github.com/conda-forge/conda-smithy/issues/1459#issuecomment-1858846653 .
This PR adds the suggested change from https://github.com/conda-forge/conda-smithy/issues/1459#issuecomment-1858848004 .
With that change the issue from https://github.com/conda-forge/python-feedstock/pull/656#discussion_r1428500644 has not been reproducible for me (for a selection of `PYTHONHASHSEED` values).
Similarly the issue from https://github.com/conda-forge/pytensor-suite-feedstock/issues/54 reported here at gh-1782 does not reproduce …
> Fix squished zip key ordering

- conda_smithy/configure_feedstock.py
- news/rm_run_win_build_bat.rst
Make sure to cleanup `run_win_build.bat` when unneeded.
Checklist
> Cleanup `run_win_build.bat`

- conda_smithy/templates/github-actions.yml.tmpl
- news/1839-gha-checkout.rst
Checklist
Resolves [deprecation warnings in GHA workflows like this one](https://github.com/conda-forge/pytorch-cpu-feedstock/actions/runs/7727743331) (node 16 no longer supported).
> Update GHA workflow to checkout@v4

- conda_smithy/configure_feedstock.py
- news/1844-conda_build_tool-conda-build
- tests/test_configure_feedstock.py
Checklist
I'd like us to get the [fixes from `conda-build=24.1.2` in which also affect `conda-build=3.28.4`](https://github.com/conda/conda-build/blob/24.1.2/CHANGELOG.md#2412-2024-02-15) which we are currently limited to due to https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/657 / https://github.com/mamba-org/boa/issues/392 .
If we change to `conda-build` by default, we can avoid the constraint needed for `boa=0.16.0`.
(We should also put out a `boa=0.16.1` for feedstocks that have `conda-mambabuild` set explicitly, of course.)
> Change default build tool to conda-build again

- conda_smithy/utils.py
- news/1840-stdlib-jinja.rst
This is an absolutely minimal PR towards #1840 (smithy will fail to parse a recipe containing `{{ stdlib("c") }}` otherwise). Explicit testing will follow once we get support in conda-build fixed up.
> ENH: add handling for stdlib-jinja function

- conda_smithy/cli.py
- news/1854-use-azure-owner-in-url-for-missing-token-error-message.rst
Checklist
Today I ran `conda smithy register-ci` on a new computer which didn't yet have `~/.conda-smithy/azure.token`. It sent me to the URL https://dev.azure.com/conda-forge/_usersSettings/tokens, which I don't have access to. I need to use my Azure account name, ie https://dev.azure.com/jdblischak/_usersSettings/tokens
```sh
export AZURE_ORG_OR_USER="jdblischak"
conda smithy register-ci --user "jdblischak" --feedstock_directory . --without-all --with-azure
```
The `owner` is defined earlier in `cli.py`, so I inserted it into the error message
https://github.com/conda-forge/conda-smithy/blob/e296d0d3079f4fdc9be5d5d84f8816f94a55ff78/conda_smithy/cli.py#L317
Then I confirmed it works as expected
```sh
mamba env create --file environment.yml
conda activate conda-smithy
which conda-smithy …
```
> Use Azure owner in URL for missing token error message

- conda_smithy/templates/build_steps.sh.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- conda_smithy/templates/run_win_build.bat.tmpl
- news/1859-avoid-conda-subcommand-plugin.rst
Recent conda-build versions register itself as conda subcommands via conda's plugin mechanisms.
Since conda-build failures don't gracefully exit, but rather just by raising exceptions, conda's exception handling and error reporting mechanisms add additional verbose output on build failures.
Checklist
> Invoke conda-{build,mambabuild} directly, not as conda subcommand

- conda_smithy/configure_feedstock.py
- conda_smithy/lint_recipe.py
- news/1868-address-conda-build-deprecations
`conda_build.conda_interface` is going to be marked for deprecation.
refs:
- https://github.com/conda/conda-build/pull/5222
Checklist
> Address conda-build deprecations

- conda_smithy/configure_feedstock.py
- conda_smithy/validate_schema.py
- news/1885-do-not-raise-on-validation-errors.rst
- tests/test_configure_feedstock.py
Checklist
Closes #1879 
For now it doesn't offer any configuration options, and just replaces the previous errors with warnings formatted like this:
```
WARNING  conda_smithy.configure_feedstock:configure_feedstock.py:2002 conda-forge.yml: $.noarch_platforms = ['eniac', 'zx80'] -> ['eniac', 'zx80'] is not valid under any of the given schemas
```
Let me know if you want to have an option in the CLI, but for now users could just run `recipe-lint` before or after 🤷
> Rerenders: do not raise on validation errors

- conda_smithy/cli.py
- conda_smithy/lint_recipe.py
- news/1886-prettier-lints.rst
Checklist
A possible solution to closing #1860. This does not implement a table (conda-forge-webservices assumes a list of items), but at least makes it more readable. The key links to the help documentation in conda-forge.org.
I also added an alias to `conda-smithy recipe-lint` because _technically_ we are now linting for more things than _just_ the recipe.
Compared to the current format:
This PR would make it look like this, more or less (ignore the "For local-path" bits, that's just a local emulation):
> adjust linter output formatting for friendlier markdown rendering

- conda_smithy/configure_feedstock.py
- news/1888-ensure-stdlib-renders-correctly.rst
- tests/conftest.py
- tests/test_configure_feedstock.py
Closes #1840, ~needs conda-build 24.3; tested locally with artefacts from https://github.com/conda-forge/conda-build-feedstock/pull/220~
> add test for correctly resolving stdlib

- conda_smithy/configure_feedstock.py
- news/1889-merge-c_stdlib_version-and-MACOSX_DEPLOYMENT_TARGET-on-osx.rst
- tests/conftest.py
- tests/test_configure_feedstock.py
~Builds on #1888 (draft until that's merged)~
Closes #1884
> merge c_stdlib_version & MACOSX_DEPLOYMENT_TARGET on osx

- conda_smithy/data/conda-forge.json
- conda_smithy/schema.py
- news/1891-disabled-bot-inspection.rst
Checklist
https://github.com/regro/cf-scripts/pull/2274 added support for the `disabled` bot inspection choice for `conda-forge.yml`, which is added with this PR. Also, `True` was never supported as an inspection option.
> add "disabled" bot inspection to schema

- conda_smithy/data/conda-forge.json
- conda_smithy/schema.py
- news/1892-drop-support-inspection-false.rst
replaced by bot.inspection = disabled
See https://github.com/regro/cf-scripts/issues/2272#issuecomment-2004119968
According to my information, `false` is not used by any feedstock anymore. All feedstocks are migrated.
Checklist
@beckermr
> drop support for bot.inspection = false

- conda_smithy/cli.py
- conda_smithy/configure_feedstock.py
- conda_smithy/utils.py
- news/1897-small-fixes.rst
Checklist
* N/A
- Since Python 3, we no longer subclass `object`
- `logger.warn` is deprecated
- fix typo
> small fixes

- conda_smithy/configure_feedstock.py
- environment.yml
- news/1908-less-stdlib-spam.rst
Discussed in the core call today. As of conda-build 24.3, this isn't necessary anymore; update the minimum version to reflect this.
@beckermr wasn't in the call but [asked](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/691#discussion_r1543491834) the same thing a while back.
> remove `c_stdlib{,_version}` from `always_keep_keys` in configure_feedstock.py

- conda_smithy/lint_recipe.py
- news/1909-stdlib-linter.rst
- tests/test_lint_recipe.py
As discussed in core call today; I wanted to add this into `run_conda_forge_specific` originally (where the other hint logic from https://github.com/conda-forge/conda-smithy/pull/1772 lives[^1], but it's a pain to run that in testing because `run_conda_forge_specific` requires a `GH_TOKEN`. If desired, I can still move it there, especially now that the tests have been debugged (and assuming CI here has a valid token). 🤷  
[^1]: which we cannot reuse because it currently only works for plain package names, no patterns, versions etc.
Note: I'd also want to wait before ~merging~ releasing this until we have updated the stdlib docs in the knowledge base, to avoid people getting confused.
> provide linter hints about adding stdlib, removing outdated ways to do it

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/github-actions.yml.tmpl
- news/1913-macos-x64.rst
Checklist
See https://github.com/conda-incubator/setup-miniconda/issues/344 for more  context. `macos-latest` is slowly defaulting to `-14` which means ARM64, not Intel.
> Use macos-13 explicitly for osx-64 on Github Actions

- conda_smithy/data/conda-forge.yml
- conda_smithy/schema.py
- news/1914-macos-12-azure.rst
Checklist
Comes from https://github.com/conda-forge/conda-forge.github.io/issues/2067
> Bump to macos-12 on azure

- conda_smithy/templates/automerge.yml.tmpl
- news/1923-checkout.rst
Checklist
Comes from https://github.com/conda-forge/admin-migrations/pull/104#issuecomment-2101310476
> remove unnecessary git checkout in automerge

- conda_smithy/lint_recipe.py
- news/1929-lint-osx-misconfigurations-in-CBC.rst
- tests/test_lint_recipe.py
Linter portion of #1927, but also adding linter hints for warnings from #1889, which were so far only visible when running smithy locally.
> Add linter hints for issues with OSX configuration in CBC

- conda_smithy/configure_feedstock.py
- news/1928-fix-macos-sdk-merge.rst
- tests/conftest.py
- tests/test_configure_feedstock.py
Fixes #1927 (minus the linter)
> ensure MACOSX_SDK_VERSION is at least c_stdlib_version

- conda_smithy/lint_recipe.py
- news/lint_no_builds.rst
- tests/test_lint_recipe.py
Checklist
xref: https://github.com/regro/cf-scripts/issues/2627
> ENH lint for no `.ci_support` files and thus no package builds

- .github/dependabot.yml
- .github/workflows/_proxy-file-for-dependabot-tests.yml
- conda_smithy/templates/github-actions.yml.tmpl
- news/1930-dependabot.rst
- tests/test_configure_feedstock.py
Checklist
Trying this out. I'm expecting this config to do the following:
- Update the workflows under `.github/workflows` as usual
- ~Maaaaybe pick the `github-actions.yml.tmpl` file in the templates. If that's true, we should see a PR updating `upload-artifacts`.~ It won't.
- I added a dummy workflow with the same `uses` lines as the GHA template. This will act as a proxy that we reconcile via a test with the actual template.
> Add dependabot configuration and pin Github Actions actions

- conda_smithy/lint_recipe.py
- news/1939-lint-or.rst
- tests/test_lint_recipe.py
For https://github.com/conda-forge/conda-smithy/pull/1929, we needed to do some basic filtering in CBC to the platform we're looking at, in order to not produce spurious warnings. In order to keep things simple and not rewrite too much of conda-build, this was done with some simple-ish regex pattern, that however wasn't smart enough to deal with `or`-conjunctions.
I've recently hit a linter bug on the otherwise benign
```yaml
c_stdlib_version:  # [linux or (osx and x86_64)]
- 2.17           # [linux]
- 10.15          # [osx and x86_64]
```
and this is something we shouldn't fail on. I know how to [work around](https://github.com/conda-forge/pytorch-cpu-feedstock/pull/238/commits/bd282c8d22621ae0e639b8a6d47626499e4bbff7) it, but only because I wrote the linter rule 😅 
Fortunately, there is …
> BUG: robustify CBC linter w.r.t. `or`'d selectors

- conda_smithy/lint_recipe.py
Make sure that the lint from #1941 is understandable (i.e. necessary for all outputs). Also some small fix-ups to the messages from #1929
I don't think this needs a news item.
> improve linter warning messages a tad

- conda_smithy/templates/travis.yml.tmpl
- news/1942-travis-tmpl-update.rst
Travis CI **linux-ppc64le** jobs are currently failing (https://github.com/conda-forge/status/issues/178). Travis support recommended updating the config (#1940). This PR implements those changes.
Checklist
Closes #1940.
Should resolve https://github.com/conda-forge/status/issues/178.
These changes have been tested in https://github.com/conda-forge/r-backbone-feedstock/pull/15. Some relevant documentation of the *partial* success (and previous failure):
- [full recent build history](https://app.travis-ci.com/github/conda-forge/r-backbone-feedstock/pull_requests?serverType=git)
- pre-update [example failure](https://app.travis-ci.com/github/conda-forge/r-backbone-feedstock/builds/270410159)
- post-update [example ppc64le-only passing](https://app.travis-ci.com/github/conda-forge/r-backbone- …
> Update Travis CI template

- conda_smithy/lint_recipe.py
- news/1946-lint-cb2.rst
- tests/test_lint_recipe.py
The stdlib lints from #1909 that we expanded to #1941 don't work with old-style cb2 requirements. Fix it.
> BUG: fix linter failures on cb2 requirements

- tests/test_lint_recipe.py
https://github.com/conda-forge/conda-smithy/commit/22a8a1dabcf81811efcf16db77563f2aeb5e1355#diff-509ad066722190140fc233360c53d9cc0e274542fe73d5a74ac76cb4dd2cc9e1R1775 introduced a new test function that calls code that relies on `GH_TOKEN` to be set and valid. The test fails when not run in GitHub actions. This PR adds the appropriate `skipUnless()` decorator. This fixes local test runs.
This is part of the STF work for Conda.
> test: skip test that relies on GH_TOKEN if that is not set

- conda_smithy/templates/build_steps.sh.tmpl
- news/1958_yum_fix_ulimit.rst
Checklist
I am one of the maintainers of the ROOT project conda-forge feedstock at https://github.com/conda-forge/root-feedstock . We make use of the `yum_requirements.txt` feature which triggers a `yum install` step in our build with the necessary package. I always noticed that this takes a huge amount of time due to [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1537564) and I always manually set the number of file descriptors when developing locally. I thought it would be a good idea to upstream this to conda-smithy. Let me know if it makes sense and if I'm missing anything relevant in the changes. Thank you so much for the great project!
> Prevent slowdown in yum due to high file descriptor count

- conda_smithy/configure_feedstock.py
- conda_smithy/utils.py
- news/1967_conda-build-24.7.rst
HashableDict is [deprecated in conda-build 24.5.0](https://docs.conda.io/projects/conda-build/en/24.5.x/release-notes.html#id4) in favor of `frozendict.deepfreeze`, removed in 24.7.
ref: https://github.com/conda/conda-build/pull/5284
rerender's working for me with this change and conda-build 24.5.1.39_gc49182fe. Rerender time is reduced by about 90%  for me with 24.7.x, so I'm looking forward to this release.
> HashableDict is removed in conda_build 24.7

- conda_smithy/data/conda-forge.json
- conda_smithy/schema.py
- news/1968_rattler_build_support.rst
Checklist
Follow up to https://github.com/conda-forge/conda-smithy/pull/1876, which was missing the `rattler-build` entry in `schema.py`. The change was made directly in the JSON file, which means that it will get lost in following schema regenerations.
> Fix rattler build schema

- conda_smithy/data/conda-forge.json
- conda_smithy/data/conda-forge.yml
I ran `python conda_smithy/schema.py`.
> fix: regenerate schema

- conda_smithy/data/conda-forge.yml
- conda_smithy/schema.py
- tests/test_configure_feedstock.py
This fixes the issue I have described in #1993 and adds a regression test for it.
Checklist
> Fix: respect Pydantic aliases for default value parsing

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/README.md.tmpl
- news/maintainer-urls.rst
GitHub team pages have a different URL structure than regular users. Add a conditional to the template for README Feedstock Maintainers to check for "/" and use the team URL for maintainers which contain "/" because regular user names cannot contain "/".
Closes #1989 
Checklist
> BUG: Correctly render team urls in README Feedstock Maintainers

- conda_smithy/configure_feedstock.py
- news/2002-conda_interface.rst
Checklist
removed in conda-build 24.7 https://github.com/conda/conda-build/pull/5333
#1868 removed this import, but it seems to have been reintroduced in the merge of #1876
> remove deprecated, unused conda_interface import

- conda_smithy/variant_algebra.py
- news/2006-use-tlz.rst
Within `toolz`, it provides a `tlz` namespace. This namespace will optionally use the performant `cytoolz` package and fallback to the pure Python `toolz` package if not.
Edit: More [details in `tlz`'s docstring]( https://github.com/pytoolz/toolz/blob/7a0382e326eb2549e4dc7b833dc666a877feca38/tlz/__init__.py#L1-L7 )
Checklist
> Use `tlz` namespace from `toolz`

- conda_smithy/linter/lints.py
- news/2018-pin-subpackage-lint.rst
- tests/test_lint_recipe.py
This PR fixes how we lint `pin_subpackage` and `pin_compatible`.
> fix pin_subpackage / pin_compatible lints with v2 recipes

- conda_smithy/lint_recipe.py
- conda_smithy/linter/rattler_linter.py
- conda_smithy/linter/utils.py
- news/linting.rst
> feat: add lint for conda forge specific stuff

- conda_smithy/lint_recipe.py
- conda_smithy/linter/lints.py
- conda_smithy/linter/utils.py
- news/1992-lint-stdlib-v2.rst
- tests/test_lint_recipe.py
~Note: the addition of `recipe_dir` in the lint_stdlib function breaks API.~
No API breaks here.
> Add conda recipe format v2 stdlib lint support

- conda_smithy/linter/utils.py
I [noticed](https://github.com/conda-forge/conda-smithy/pull/2039#discussion_r1739942059) that the recently added `lru_cache` for getting the hints might lead to a very long time until new hints get pulled (also observed in the wild that more than 1h after merging https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6353, hints are not showing up).
Ensure we bust the cache every hour to keep things reasonably fresh.
> ensure we refresh the linter hints regularly

- conda_smithy/linter/lints.py
- news/2041-stdlib_corner_case.rst
- tests/test_lint_recipe.py
Hit by @jaimergp in https://github.com/conda-forge/staged-recipes/pull/27419
> Fix corner-case in stdlib linting

- .github/workflows/_proxy-file-for-dependabot-tests.yml
Reverts conda-forge/conda-smithy#2049
> Revert "build(deps): bump actions/upload-artifact from 4.3.4 to 4.4.0 in /.github/workflows in the github-actions group"

- .flake8
Checklist
We do not need this one anymore.
> chore: delete old flake8 config file

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/build_steps.sh.tmpl
> Fix spaces in yum requirements

- conda_smithy/templates/run_win_build.bat.tmpl
For https://github.com/conda-forge/google-cloud-cpp-feedstock, I need to use an older lief due to https://github.com/conda-forge/lief-feedstock/issues/45 causing the build to time out otherwise. This started failing recently, as our default python version in the image seems to have moved to 3.12, for which we have no `lief<0.14` builds. 
Once I add a `python=3.11` pin to `remote_ci_setup`, things work out again, except on windows. See the diff for https://github.com/conda-forge/google-cloud-cpp-feedstock/pull/183/commits/ae95a6d97d7e98e704b00d8a27cfa611a7a45371 in https://github.com/conda-forge/google-cloud-cpp-feedstock/pull/183
<details>
```diff
diff --git a/.scripts/build_steps.sh b/.scripts/build_steps.sh
index 4552b6d..e9a5f15 100755
--- a/.scripts/build_steps.sh
+++ …
```
> remove python 3.10 pin in `run_win_build.bat` template

- conda_smithy/lint_recipe.py
- news/gh-token-linting.rst
- tests/test_lint_recipe.py
Checklist
This PR 
- removes the need for a GitHub token in order to run the linter for conda-forge locally
- moves staged-recipes specific lints to staged-recipes (xref: https://github.com/conda-forge/staged-recipes/pull/27590)
The idea here is three-fold:
- separate staged-recipes code (which is more adhoc and moves quickly) from code for feedstocks (which moves at a slower pace) (see, e.g. the fix we had to push in PR #2038 due to a change in staged-recipes - we removed the lint there in favor of staged-recipes code and this PR follows that same logic to its conclusion.)
- enable staged-recipes maintainers to help maintain the linter in ways that help them review recipes more efficiently without having to make a smithy PR and release (see, e.g., the custom github actions added …
> fix: remove need for GH token when linting for conda-forge

- conda_smithy/lint_recipe.py
- news/use-token.rst
> fix: use gh token if we have one

- conda_smithy/templates/build_steps.sh.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- conda_smithy/templates/run_win_build.bat.tmpl
- news/rattler-build-cross-compile.rst
rattler-build does not read the `target_platform` from the variant config file. We need to explicitly pass it on the command line.
> fix: add `--target-platform` for rattler-build invocation

- conda_smithy/data/conda-forge.json
- conda_smithy/data/conda-forge.yml
- conda_smithy/schema.py
- news/2078-macos-13.rst
Checklist
macos-12 is starting its deprecation period next Monday, and will be removed by December, with brownouts in between. See details at https://github.com/actions/runner-images/issues/10721.
> Bump Azure to macOS 13

- conda_smithy/github.py
should avoid issues with the default branch not existing, which was required for the `edit_protection` API.
I _believe_ this is the equivalent ruleset. I've run it against scifem-feedstock, so you can see the resulting rule [here](https://github.com/conda-forge/scifem-feedstock/settings/rules/2140270).
closes #2080
> use ruleset to enable branch protections

- conda_smithy/data/conda-forge.json
- conda_smithy/data/conda-forge.yml
- conda_smithy/lint_recipe.py
- conda_smithy/schema.py
- tests/test_lint_recipe.py
When building python recipes that builds a python version specific extensions and noarch python variants, the lint can be wrong. This gives a way for maintainers to skip that lint.
Checklist
> Support skipping noarch selector lints

- conda_smithy/templates/run_win_build.bat.tmpl
- news/gh2091.rst
We were using `conda.exe run ...` to execute `rattler-build, but it does something undesirable to the current code page on Windows which leads to "Moji-bake".
When calling rattler-build directly, things seem to work much better for printing fancy tables.
Tested in https://github.com/conda-forge/jolt-physics-feedstock/pull/6
Before: 
After:
> fix moji-bake with rattler-build on Windows

- conda_smithy/lint_recipe.py
- news/team-exists.rst
- tests/test_lint_recipe.py
Checklist
This PR adds a check for team existence when linting.
closes #2089
> fix: add check for team existence

- conda_smithy/linter/utils.py
- news/gh2094.rst
Checklist
Follow up to #2039
I'm the maintainer of whey, and it's used by around 70 projects.
> Add whey to list of known build backends for the linter

- conda_smithy/data/conda-forge.json
- conda_smithy/schema.py
- conda_smithy/templates/build_steps.sh.tmpl
- news/gh2075-micromamba-install-tool.rst
Checklist
- Needs https://github.com/conda-forge/docker-images/pull/288
- Testing at https://github.com/conda-forge/dav1d-feedstock/pull/21 ([1b3689c](https://github.com/conda-forge/dav1d-feedstock/pull/21/commits/1b3689cfd0a5e5b17f86bfb2bb6bd266211f43f5) and following commits)
> Allow `micromamba` provisioning in Linux too

- conda_smithy/lint_recipe.py
- conda_smithy/linter/hints.py
- news/gh2104-lint-pypi-io.rst
- tests/recipes/click-test-feedstock/recipe/meta.yaml
- tests/recipes/noarch_platforms/recipe/meta.yaml
- tests/test_lint_recipe.py
See also https://github.com/conda-forge/staged-recipes/pull/27946
Techically pypi.org also has a permanent redict to
files.pythonhosted.org, so we could avoid oen more redirect by hinting
pypi.org -> files.pythonhosted.org
Checklist
> Try to add hints pypi.io -> pypi.org.

- conda_smithy/templates/run_win_build.bat.tmpl
- news/2107-micromamba-cache-windows.rst
Checklist
Patches symptom behind https://github.com/conda-forge/conda-smithy/issues/2101, but at the cost of not reusing the micromamba cache for conda-build on Windows. It should have a minor impact in the timings, given how fast the CI download is anyway. The mamba team has been notified of the issue and will be looking into it, so we can revert the workaround in the future, once fixed.
> Do not move micromamba cache to `%MINIFORGE_HOME%`

- conda_smithy/templates/azure-pipelines.yml.tmpl
- news/2110-azure-skip-only-pr.rst
Checklist
live tests:
- tested that PR commits are skipped: https://github.com/conda-forge/cf-autotick-bot-test-package-feedstock/pull/596/commits/ea56503a455d9a36409393ca5ac9bdde325d2e0d
- tested that commits on main after a skipped commit run: https://github.com/conda-forge/cf-autotick-bot-test-package-feedstock/commit/4f8106772b247f825ae9173c75c5758178ff8313 (previous commit was https://github.com/conda-forge/cf-autotick-bot-test-package-feedstock/commit/d2f8e0dd5810024e75ae1c8f082b0a654b14e5ff)
> fix: only skip azure on PRs

- conda_smithy/linter/hints.py
- news/2111-lint-src-url-pypi-bug.rst
The new linter rule (while great) doesn't take into account that a `source.url` can be a list of URLs (with fallback).
This is an issue for e.g. `selenium`, where the upstream git tag (bleargh) can be one of _either_:
- `4.26.0`
- `python-4.26.1`
Checklist
> handle source.url as list in pypi.org linter rule

- conda_smithy/lint_recipe.py
- conda_smithy/linter/hints.py
- news/2119-fix-lint-noarch-python-v1.rst
- tests/test_lint_recipe.py
Checklist
xref: https://github.com/conda-forge/staged-recipes/pull/28091
> fix: ensure noarch python hint is correct for v1 recipes

- conda_smithy/linter/hints.py
- news/2119-fix-lint-noarch-python-v1.rst
- tests/test_lint_recipe.py
Checklist
This PR moves the `noarch: python` syntax to a form that does not break older versions of conda-build. I have put in a [fix to conda-build](https://github.com/conda/conda-build/pull/5528), but we might as well use something more compatible and equivalent.
> fix: use syntax for `noarch: python` min version that does not break conda-build

- conda_smithy/linter/hints.py
- conda_smithy/utils.py
- news/2123-more-noarch-python-fixes.rst
- tests/test_lint_recipe.py
> fix: lint for noarch: python happens after render

- conda_smithy/templates/run_win_build.bat.tmpl
This causes >20k lines of logs on windows that are completely pointless, e.g.
```
Removing D:\Miniforge-micromamba-1766
Deleted file - D:\Miniforge-micromamba-1766\condabin\activate.bat
Deleted file - D:\Miniforge-micromamba-1766\condabin\mamba_hook.bat
Deleted file - D:\Miniforge-micromamba-1766\condabin\micromamba.bat
Deleted file - D:\Miniforge-micromamba-1766\condabin\_mamba_activate.bat
Deleted file - D:\Miniforge-micromamba-1766\pkgs\anaconda-client-1.12.3-pyhd8ed1ab_1.conda
Deleted file - D:\Miniforge-micromamba-1766\pkgs\archspec-0.2.3-pyhd8ed1ab_0.conda
[goes on forever]
```
> don't log extremely verbose deletion of MAMBA_ROOT_PREFIX/MICROMAMBA_TMPDIR

- conda_smithy/linter/hints.py
- news/2126-adjust-noarch-py-hint.rst
- tests/test_lint_recipe.py
Checklist
Trying to address this [comment](https://github.com/conda-forge/conda-forge.github.io/issues/2351#issuecomment-2464374140) from @maresb.
> fix: soften language for the `noarch: python` hint, add override note, and fix a bug for v1

- conda_smithy/configure_feedstock.py
- news/make-GHA-services-removal-relative.rst
This removes the assumption that user is always
invoking conda-smithy from the repo root.
Checklist
This resolves the following issue:
```
WARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding in variants from internal_defaults
Adding in variants from /path/to/.cache/conda-smithy/conda_build_config.yaml
Adding in variants from …
```
> Make old GH action file removal relative to forge_dir

- conda_smithy/utils.py
- news/2132-more-noarch-bugs.rst
- tests/test_lint_recipe.py
Checklist
Fixing more bugz. Sigh.
> fix: ensure linter works when python_min is set via jinja2

- conda_smithy/github.py
- conda_smithy/utils.py
- news/noarch_create_feedstocks.rst
- tests/conftest.py
- tests/test_utils.py
Checklist
This PR ensures we use the pinnings file when parsing recipe names for conda-forge. It helps avoid undefined jinja2 errors and badly formatted spec errors.
> fix: ensure we use CBC to parse recipe names for conda-forge

- .github/workflows/tests.yml
- conda_smithy/lint_recipe.py
- conda_smithy/linter/lints.py
- news/2141-recipe-parsing-lint-hint.rst
- tests/test_lint_recipe.py
Checklist
This PR is a good step for moving towards v1 recipes. We'll need recipes to be able to be parsed by CRM in order to try automatic conversion. I also included the bot's parser and the one used by grayskull.
closes #2140
> feat: add lint+hint for recipe parsing

- conda_smithy/templates/run_osx_build.sh.tmpl
- news/pixi_osx.rst
Checklist
I noticed this issue when using pixi as conda install tool. The `mkdir` command is outside the pixi condition but I can also move it inside it if you prefer. Let me know.
> Make sure $MINIFORGE_HOME exists during osx build

- conda_smithy/templates/run_osx_build.sh.tmpl
- news/pixi_osx.rst
Creating `MINIFORGE_HOME` up top breaks the Miniforge install step. As this appears this is only needed for `pixi` move to that block to limit the effect.
cc @hadim @beckermr
xref: https://github.com/conda-forge/conda-smithy/pull/2142#discussion_r1849286289
Checklist
> Move `MINIFORGE_HOME` fix to `pixi` block

- conda_smithy/cli.py
- news/2144-noarch-py-min.rst
Checklist
This PR fixes a bug that is blocking staged-recipes. The value of `python_min` is needed in order to get the recipe name in conda-build. I fixed a similar bug before, but missed this version of it.
> fix: need pinnings for register ci too

- conda_smithy/configure_feedstock.py
- conda_smithy/schema.py
- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- news/2062-atl.rst
Fixes #2062
This breaks on only a handful of feedstocks, but where it does happen it's very annoying to fix for every rerender (and non-obvious for those who don't know). Initially my hope was that MSFT would solve https://github.com/actions/runner-images/issues/9873, but after many months, it's time to admit that that won't happen.
> add option to install ATL components

- conda_smithy/linter/hints.py
- news/2151-hint-less-spaces.rst
- tests/test_lint_recipe.py
> allow multiple spaces in python_min syntax

- conda_smithy/lint_recipe.py
- conda_smithy/linter/lints.py
- news/2157-bugfix-ignore_run_exports-for-v1-recipes.rst
- tests/recipes/v1_recipes/recipe-ignore_run_exports-no-lint.yaml
- tests/test_lint_recipe.py
The ignore_run_exports directive for v1 recipes has a different format, attempt to support it for the lint_single_space_in_pinned_requirements.
I only run the lint for the `from_package` section, should we also run it over the `from_name` section if that exists?
Should I also add a test-case with the recipe which failed?
Closes #2153 
Checklist
> Bugfix ignore_run_exports for v1 recipes

- conda_smithy/linter/lints.py
- conda_smithy/linter/utils.py
- news/2166-v1-recipe-fixes.rst
- tests/recipes/v1_recipes/ada-url.yaml
- tests/recipes/v1_recipes/torchaudio.yaml
- tests/test_lint_recipe.py
There were a few places were requirements weren't properly flattened wrt to conditional statements in requirements. This fixes that.
> fix: add more lint tests and fix flattening of requirements

- conda_smithy/data/conda-forge.json
- conda_smithy/data/conda-forge.yml
- conda_smithy/schema.py
- news/2155-distro-lint.rst
- tests/test_lint_recipe.py
This is for linting wrong distro values used in `os_version` (which becomes more important after https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6626, as it might lead to zipping problems and thus rerender errors).
With this PR, a `conda-forge.yml` of
```yaml
os_version:
linux_64: wrong
```
would lead to
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for ConfigModel
os_version.linux_64
Input should be 'cos7', 'ubi8', 'alma8' or 'alma9' [type=literal_error, input_value='wrong', input_type=str]
For further information visit https://errors.pydantic.dev/2.10/v/literal_error
```
We'll certainly want to polish this further (e.g. into a concrete hint/lint), hence this is a draft. It's also a draft because by themselves, the changes in …
> ENH: lint incorrect distro names in `os_version`

- conda_smithy/templates/azure-pipelines-win.yml.tmpl
- conda_smithy/templates/build_steps.sh.tmpl
- conda_smithy/templates/pixi.toml.tmpl
- conda_smithy/templates/run_osx_build.sh.tmpl
- conda_smithy/templates/run_win_build.bat.tmpl
- news/pixi_osx_conda_bld_path.rst
Checklist
This is an attempt to fix https://github.com/conda-forge/conda-smithy/issues/2145. You can see it in action at https://github.com/conda-forge/docling-parse-feedstock/pull/3
Note the fix is a simple and naive patch but looks fragile to me. Please let me know if you can think of another solution.
> Set CONDA_BLD_PATH when using pixi during osx build

- conda_smithy/lint_recipe.py
- news/2171-fix-maintainer_exists.rst
- tests/test_lint_recipe.py
Checklist
This PR fixes #2164 by using two public URLs to check if the maintainer exists instead of using the github API anonymously. Hopefully it is more robust since the anonymous API has pretty restructive rate limits.
> fix: try two public urls for maintainer exists lint

- conda_smithy/linter/hints.py
- news/2184-noarch-py-v1-regex.rst
- tests/test_lint_recipe.py
> fix: need to escape $ in regex for noarch python hint

- conda_smithy/linter/utils.py
- news/add-flit.rst
It's confusing that `flit-core` is valid, but `flit` is not.
Checklist
> Add flit to list of valid build backends

- conda_smithy/feedstock_io.py
- conda_smithy/feedstock_tokens.py
- news/2185-fix-pygit2-windows.rst
Checklist
libgit2 expects internal git paths to be passed in git convention, that is using forward slashes.  Use pathlib.Path.as_posix() to ensure that the correct conversion is used when passing paths to index operations.
Fixes #2185
> Always pass POSIX paths to pygit2 index (#2185)

- conda_smithy/linter/lints.py
- conda_smithy/linter/utils.py
- news/fix-if-else-in-run.rst
- tests/recipes/v1_recipes/torchvision.yaml
- tests/test_lint_recipe.py
Checklist
Flatten if/else conditions in run requirements and constraints, in v1 recipes, in addition to build requirements.  This prevents the subsequent code from crashing on them:
```
File "/home/mgorny/miniforge3/lib/python3.12/site-packages/conda_smithy/linter/lints.py", line 854, in <genexpr>
if any(req.startswith("__osx >") for req in to_check):
^^^^^^^^^^^^^^
AttributeError: 'CommentedMap' object has no attribute 'startswith'
```
Fixes #2196
Probably fixes #2165 as well
> fix: Flatten if/else conditions in run requirements and constraints

- conda_smithy/feedstock_io.py
- news/fix-feedstock_io-dir-remove.rst
- tests/test_feedstock_io.py
Checklist
Fix `remove_file_or_dir()` to correctly remove directories from index, and add a test case to cover it.
> fix: Fix removing dir in feedstock_io, and add a test case

- .github/workflows/tests.yml
- conda_smithy/linter/utils.py
- news/pr-2204-sphinx-build-backend.rst
See [here](https://sphinx-theme-builder.readthedocs.io/en/latest/filesystem-layout/#how-to-get-this-right) in the documentation, for example, for confirmation that sphinx-theme-builder is a Python build backend.
Checklist
> Add sphinx-theme-builder as valid Python build backend

- conda_smithy/data/conda-forge.json
- conda_smithy/lint_recipe.py
- conda_smithy/schema.py
- news/skip-python-hints.rst
- tests/test_lint_recipe.py
Checklist
Fixes #2170 
Add options to skip linter checks for `python_min` and missing build backend, both requested in #2170. While at it, fix a `TypeError` that occurs when `conda-forge.yml` contains empty `linter:` or `skip:` keys.
> Support skipping `python_min` and `pip_no_build_backend` hints

- conda_smithy/lint_recipe.py
- conda_smithy/linter/conda_recipe_v1_linter.py
- news/schema_version.rst
- tests/recipes/v1_recipes/torchvision.yaml
- tests/test_lint_recipe.py
Checklist
Allow the `schema_version` key in v1 recipes, and validate that it has a value of 1.
For testing:
- lack of `schema_version` is covered by most of the existing tests
- for `schema_version: 1`, I've modified our `torchvision.recipe`
- for invalid `schema_version`, I've added an explicit test
> Allow and validate `schema_version` key in v1 recipes

- conda_smithy/lint_recipe.py
- news/v1_cfep25_test.rst
- tests/test_lint_recipe.py
> Consider `tests[].python.python_version` when linting for cfep25 on v1

- conda_smithy/linter/lints.py
- news/v1-flatten-pins.rst
- tests/recipes/v1_recipes/recipe-fenics-dolfinx.yaml
- tests/test_lint_recipe.py
Checklist
prior to this, `recipe-lint` failed on a recipe with:
```
File "/Users/minrk/dev/conda-forge/conda-smithy/conda_smithy/lint_recipe.py", line 749, in main
results, hints = lintify_meta_yaml(
^^^^^^^^^^^^^^^^^^
File "/Users/minrk/dev/conda-forge/conda-smithy/conda_smithy/lint_recipe.py", line 343, in lintify_meta_yaml
lint_pin_subpackages(
File "/Users/minrk/dev/conda-forge/conda-smithy/conda_smithy/linter/lints.py", line 661, in lint_pin_subpackages
check_pins_build_and_requirements(meta)
File "/Users/minrk/dev/conda-forge/conda-smithy/conda_smithy/linter/lints.py", line 659, in check_pins_build_and_requirements
check_pins(run_export_section)
File "/Users/minrk/dev/conda-forge/conda-smithy/conda_smithy/linter/lints.py", line 610, in check_pins
for pin in (
File …
```
> fix lint error for v1 recipes with conditionals in run_exports

- conda_smithy/lint_recipe.py
- conda_smithy/linter/lints.py
- news/v1-flatten-pins-more.rst
- tests/test_lint_recipe.py
and test a recipe with full conda_forge lint to make sure they are covered
Checklist
follow-up to #2211 which covered `recipe-lint` but missed cases covered by `recipe-lint --conda-forge`
I'm not sure how to get the test run to lose the `.ci_support` hint.
> more calls to flatten_v1_if_else

- conda_smithy/linter/conda_recipe_v1_linter.py
- conda_smithy/linter/lints.py
- conda_smithy/linter/utils.py
- news/fix-version-0.rst
- tests/test_lint_recipe.py
Checklist
Fix the boolean logic that caused version of 0 (that is a valid package version) to be incorrectly interpreted as missing, and emit linter errors.  While at it, deduplicate the recipe v0 linter to reuse the utility code added along with v1 lints, and refactor the v1 linter to reduce the number of redundant conditions and make the logic easier to follow.
Fixes #2215
> Fix handling package version 0, refactor and deduplicate

- conda_smithy/lint_recipe.py
- conda_smithy/linter/hints.py
- conda_smithy/linter/utils.py
- news/python-min-multi-output.rst
- tests/test_lint_recipe.py
Checklist
Add support for checking `python_min` use in multi-output recipes (#2188). This involves some minimal refactoring to move shared code into common functions.
While at it, accidentally discovered a bug that the following dependency:
```yaml
- if: foo
then: bar
else: baz
```
would be incorrectly flattened (`bar` would be iterated over as a list).
> Support outputs in `hint_noarch_python_use_python_min`, also fix if/then/else flattening for non-list clauses

- news/fix-macos-path-comparison.rst
- tests/test_feedstock_io.py
Checklist
Resolves macOS test failures uncovered in conda-feedstock & conda-build-feedstock downstream tests:
- https://github.com/conda-forge/conda-feedstock/pull/248#issuecomment-2555819613
- https://github.com/conda-forge/conda-feedstock/pull/248/commits/d28a86ffd666f1b11854ac87d733827a4ed14936
- https://github.com/conda-forge/conda-build-feedstock/pull/238/commits/f316c88dfa193ce03198e27994b09c1144880150
Since the CI doesn't test macOS I'm including screenshots showing I replicated the test failure on my local macOS and confirmed the fix:
> `get_repo_root` returns `os.path.realpath`

- conda_smithy/configure_feedstock.py
- news/python_min.rst
- tests/conftest.py
- tests/test_configure_feedstock.py
For recipes that have noarch-outputs as well as non-noarch outputs, the use of `{{ python_min }}` causes the recipe to fail for all platforms that don't build the noarch output, because smithy doesn't populate `python_min` for them, and then conda-build cannot parse something like
```yaml
- name: lit
build:
noarch: python
script: python -m pip install llvm/utils/lit --no-deps -vv
skip: true  # [not linux64]
requirements:
host:
- python {{ python_min }}
```
despite the fact that that output would be skipped on other platforms. It's possible to [work around](https://github.com/conda-forge/brial-feedstock/pull/37) this with something like
```yaml
{% if python_min is undefined %}
{% set python_min = "3.9" %}
{% endif %}
```
but that's ugly. To avoid these shenanigans, just always populate …
> always keep python_min as used variable (if it's present in the recipe)

- conda_smithy/lint_recipe.py
- conda_smithy/linter/hints.py
- news/2232-matchspecs-equal
- tests/test_lint_recipe.py
Checklist
@h-vetinari raised this issue in conda-build (https://github.com/conda/conda-build/issues/5571), which led us to realizing that conda-build assumes all specs in a `meta.yaml` are space separated. However, this is not checked and `=`-separated specs are happily accepted. The problem is that they bypass some checks like [this one about incompatible hashes](https://github.com/conda/conda-build/issues/5571#issuecomment-2604505922) because they are not a "three field matchspec".
I don't think we can forbid this and error out in conda-build, but at least we should hint against it to inform folks about this possible footgun. The repodata.json entries should only contain three-field matchspecs anyway (for backwards compat).
> Hint against `=`-separated match specs

- conda_smithy/ci_skeleton.py
- conda_smithy/cli.py
- conda_smithy/configure_feedstock.py
- conda_smithy/feedstocks.py
- conda_smithy/lint_recipe.py
- conda_smithy/linter/hints.py
- conda_smithy/linter/lints.py
- conda_smithy/schema.py
- conda_smithy/utils.py
- conda_smithy/validate_schema.py
I haven't had issues with running the linter on windows, but today I ran into encoding errors while linting a multi-output rattler recipe (no idea what triggered it exactly). Since python won't default to utf-8 until 3.15(!), it's better to be explicit about the encoding where we're interacting with files. I only needed the changes in `lints.py`, but while I was at it, I also looked for other uses of bare `open()` (with the exception of some obviously unix-only files, e.g. those using paths like `~/...`)
> consistently set `encoding=utf-8` for opening files

- conda_smithy/configure_feedstock.py
Fix an oversight from applying changes mechanically in #2244; files opened in binary mode don't take an encoding, and this causes
```
with open(dest, "wb", encoding="utf-8") as f:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: binary mode doesn't take an encoding argument
```
Surprising that this wasn't caught by our tests... 🤔
> fix superfluous encoding kwarg for reading in binary mode

- conda_smithy/linter/conda_recipe_v1_linter.py
- news/2248-v1-recipe-name-var.rst
- tests/test_lint_recipe.py
Checklist
Fixes #2224
Skip checking v1 recipe name if it contains unresolved variables, in order to fix false positives when a variable
from `conda_build_config.yaml` is used.
Iterating over all possible variants and verifying the resulting package names is unlikely to be worth the extra complexity.  This also roughly matches the linter behavior for v0 recipes, where `{{ var_name }}` is converted into `var_name`, and therefore is never properly linted anyway.
> Fix false positive when v1 recipe name is non-context variable

- conda_smithy/lint_recipe.py
- news/2250-recipe-dir-param.rst
- tests/test_lint_recipe.py
Checklist
Fixes #2225
Extend the default behavior of `conda-smithy lint` to detect if a feedstock directory has been passed in place of the recipe directory (e.g. by running it with no paths specified), and handle the paths appropriately.
The new logic covers three possible scenarios:
1. If `--feedstock-directory` is passed, everything works as before.
2. If not, the specified directory is checked for `meta.yaml` and `recipe.yaml`, also as before.
3. If neither exists, the specified directory is checked for `conda-forge.yml`.  If it exists, it set to be the feedstock directory, and the file is parsed to determine the correct recipe subdirectory.
This is primarily meant to address my common mistake of running:
conda smithy lint
in the feedstock directory, which can lead to pretty confusing …
> Support running `conda-smithy lint` in feedstock directory

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/pixi.toml.tmpl
- news/2256-double-quotes-and-newline.rst
I just converted a couple of recipes to v1 :tada: and noticed a couple of things with the generated `pixi.toml`.
In this PR I fix:
- Ensure newline at the end of `pixi.toml`
- Use double quotes in `platforms` list, like in the rest of the file.
Checklist
> Ensure a newline at the end of pixi.toml and use double quotes for platforms

- conda_smithy/linter/lints.py
- news/2268-lint-error.rst
- tests/recipes/v1_recipes/recipe-fenics-dolfinx.yaml
closes #2267 by skipping the failing lint for run_exports, which is consistent with v0 recipes, since they don't include run_exports in the `requirements` section.
> fix lint_single_space_in_pinned_requirements on run_exports for v1 recipes

- conda_smithy/linter/lints.py
- news/2269-line-no-for-noarch-and-runtime-dependencies.rst
- tests/test_lint_recipe.py
I wanted to get feedback on this PR, in particularly I would find it useful if the linter would tell you which line the linting issue occurs on. While this PR only address a single lint I'm interested in (since I had trouble locating where the selector was in the recipe), I want feedback if a larger PR would be welcome that would describe the line number various lint issues occur on?
Checklist
> feat: add line number to lint for noarch and runtime dependencies

- conda_smithy/templates/run_docker_build.sh.tmpl
- news/2276-fix-quotes.rst
Checklist
POSIX shell scripts are horrible and humanity should have moved past them 30 years ago
> fix: properly quote variable in POSIX

- conda_smithy/linter/hints.py
- news/2281-v1-pythonmin-hint.rst
- tests/conftest.py
- tests/test_lint_recipe.py
- tests/test_utils.py
Closes conda-forge/staged-recipes#29468
tl;dr The hint suggests using `python ${{ python_min }}` in the host and `test.requires` sections; however, rattler-build no longer accepts that as a valid matchspec because it's ambiguous.
Instead, users should use `python ${{ python_min }}.*` in these sections.
Tested against a recipe using the ambiguous matchspec and also verified it doesn't trigger if `python ${{ python_min }}.*` is used.
Checklist
> Update matchspec hint for `noarch: python` for v1 recipes

- conda_smithy/templates/build_steps.sh.tmpl
- conda_smithy/templates/pixi.toml.tmpl
- news/2279-pixi-docker-env.rst
Checklist
Comes from report at [#general > &#96;pixi r build-locally&#96; fails, &#96;pixi r build&#96; succeeds](https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/.60pixi.20r.20build-locally.60.20fails.2C.20.60pixi.20r.20build.60.20succeeds)
> Use a platform-specific env if Pixi is used to provision the environment on Docker builds

- .gitattributes
- news/2278-linguist.rst
Checklist
Define some linguist entries to enable better syntax highlighting in our templates. Browse in [branch](https://github.com/jaimergp/conda-smithy/tree/linguist/conda_smithy/templates) to see effects before merge. Compare to [current main](https://github.com/conda-forge/conda-smithy/tree/main/conda_smithy/templates) if needed.
Examples:
* Batch: [main](https://github.com/conda-forge/conda-smithy/blob/main/conda_smithy/templates/create_conda_build_artifacts.bat.tmpl) vs [PR](https://github.com/jaimergp/conda-smithy/blob/linguist/conda_smithy/templates/create_conda_build_artifacts.bat.tmpl)
* Shell: [main](https://github.com/conda-forge/conda-smithy/blob/main/conda_smithy/templates/build_steps.sh.tmpl) vs [PR](https://github.com/jaimergp/conda-smithy/blob/linguist/conda_smithy/templat …
> Customize Github highlighting in `*.tmpl` files

- conda_smithy/linter/hints.py
- news/2283-ubi8.rst
This is a minor fix-up of #2270. Since #2155, we're limiting the possible values of `os_version` through schema validation to 
https://github.com/conda-forge/conda-smithy/blob/22169a89bc72614918bdba42a6fbe7c7feec0e52/conda_smithy/schema.py#L49
but #2270 did not add a hint for that. The ubi8 images are still in use for CUDA 11.8, which is also the only place that needs them. They can continue to be used for that purpose (and any feedstock building for CUDA 11.8 will pull them in automatically), but users shouldn't set `os_version: [linux_64: ubi8]` in `conda-forge.yml` anymore.
CC @mgorny
> add ubi8 to image versions being linted on

- conda_smithy/data/conda-forge.json
- environment.yml
- news/2289-schema.rst
pydantic 2.11 adds `additionalProperties: true` to empty `type: object` fields
> regen schema with pydantic 2.11.1

- .github/workflows/_proxy-file-for-dependabot-tests.yml
Reverts conda-forge/conda-smithy#2290
I forgot we need to update the template files too.
> Revert "build(deps): bump actions/upload-artifact from 4.6.1 to 4.6.2 in /.github/workflows in the github-actions group"

- .github/workflows/_proxy-file-for-dependabot-tests.yml
- conda_smithy/templates/github-actions.yml.tmpl
Reverts conda-forge/conda-smithy#2292
Needs to have the template files updated too.
> build(deps): bump actions/upload-artifact from 4.6.1 to 4.6.2 in /.github/workflows in the github-actions group

- conda_smithy/configure_feedstock.py
- news/2300-min-ci-support-job.rst
Checklist
This PR fixes an issue where rerenders got different numbers of CI jobs depending on which output appeared first in the list of metadata objects for each output (but only when there is not an output corresponding to the top-level package name.) The first element depends on the python hash seed, hence things not being stable.
Per the code comment, we resolve this ambiguity by producing CI jobs for all combinations of the intersection of top-level loop vars over all outputs.
Another possibility would be to let people add or exclude variables to be expanded over in the CI support jobs by hand. I'd rather not do that yet, so let's try this first.
I tested this version of smithy against the ctng-compiler-activation-feedstock locally and it rendered the expected set of CI jobs.
This …
> fix: resolve non-stable rerenders by producing CI jobs for the intersection of loop vars over all outputs

- conda_smithy/linter/hints.py
- news/2302-noarch-python-min-hint-tests.rst
- tests/test_lint_recipe.py
Checklist
This PR adds a better description of the `noarch: python` min version hints/lints for the `tests` section for v1 recipes.
closes #2286
> fix: use better hints for v1 noarch python tests section

- conda_smithy/linter/hints.py
- news/2301-linter-spec-fixes.rst
- tests/test_lint_recipe.py
Checklist
This PR fixes the linter error formatting and ensures that evaled jinja2 stuff is excluded.
closes #2272
> fix: ensure bad specs hint is formatted properly and exclude some jinja2 as evaled

- conda_smithy/linter/lints.py
- news/go-no-cgo.rst
- tests/test_lint_recipe.py
> Only show stdlib lint for go-cgo compilers, not go-nocgo

- conda_smithy/templates/run_win_build.bat.tmpl
- news/news_win_fix_blocked_downloads.rst
Checklist
Closes https://github.com/conda-forge/staged-recipes/issues/28990.
certutil (which is a Certificate Authority admin tool) is being blocked by Windows Defender and other virus scanners. This PR uses powershell to directly download the files instead of certutil.
> Windows: Fix virus scanners blocking downloads

- conda_smithy/templates/run_win_build.bat.tmpl
- news/pixi-git-ssl.rst
We ran into issues because `m2-git` requires post-link scripts to be run.
This should fix: https://github.com/conda-forge/conda-smithy/issues/2239
> fix: run post-link scripts on Windows

- conda_smithy/linter/utils.py
- news/v1-python-version-matrix.rst
- tests/test_lint_recipe.py
Checklist
Thanks for the tireless effort on maintaining `conda-smithy`!
While CFEP-25 specifies packages SHOULD be validated against the ecosystem (or feedstock) `python_min`, validating against _some other python_ can find _interesting_ upstream issues.
This PR updates `hint_noarch_python_use_python_min` to allow [v1 recipes](https://github.com/prefix-dev/recipe-format/blob/fa2df/schema.json#L3320-L3337) to specify testing against `python_min` **and** some other python, at the maintainer cost of a single line, and a single, generally very fast, solve.
> don't hint on v1 python_version list with python_min

- conda_smithy/configure_feedstock.py
- conda_smithy/templates/github-actions.yml.tmpl
- news/linux-aarch64-native-gha.rst
Checklist
Fix #2243
-------
We are using conda-smithy outside of conda-forge to maintain some feedstocks that are not yet in conda-forge (either because there is an open PR to staged-recipe, or because the code we want to build is not merged in the upstream project). This is working very well for us, allowing us to create our own conda channel that is 100% compatible with the rest of conda-forge.
We are using github action as a CI provider, and we would like to take advantage of the native linux-arm runners there to build for linux-aarch64, hence the change in this PR. Let me know if such a change is OK for you!
> Use native runner to build for linux-aarch64 on github actions

- conda_smithy/variant_algebra.py
- tests/test_variant_algebra.py
Another fix-up that's necessary for correctly handling the CUDA 11.8 migrator.
News still falls under
https://github.com/conda-forge/conda-smithy/blob/ed2dc248c5cbe7e23c56cb051b9b9ad36c6471df/news/tail-ordering.rst?plain=1#L19
> fix case where non-primary, non-zipped key has an ordering

- conda_smithy/variant_algebra.py
- news/additional-keys.rst
adding a dict to the variant file is invalid for v1, which enforces lists of scalars, resulting in:
```
Error:
× an unspecified error occurred.
╭─[897:10]
896 │     __additional_zip_keys_default_values:
897 │ ╭─▶   is_abi3: 'true'
898 │ │     is_freethreading: 'false'
· ╰──── expected scalar or sequence for __additional_zip_keys_default_values
```
seen while trying to update a recipe to v1 that has had the python313t migration applied.
Since this appears to be a temporary variable only used within the scope of a single function, I removed it from the variant state to a regular variable.
added in #1764
> avoid storing __additional_zip_keys_default_values in variant config

- conda_smithy/templates/create_conda_build_artifacts.bat.tmpl
Noticed that the following is fully redundant, and actually undoes the `%SHORT_CONFIG%` logic, see
https://github.com/conda-forge/conda-smithy/blob/c9a3fbb05d892329327c64d8e52bcecf408d10a5/conda_smithy/templates/create_conda_build_artifacts.bat.tmpl#L33-L40
> remove redundant setting of ARCHIVE_UNIQUE_ID in win artefact script

- conda_smithy/configure_feedstock.py
- news/2359-commit-msg.rst
Checklist
In feedstocks with `recipe.yaml`, the commit message still shows `conda-build` versions for rerenders. Extend this to also show rattler-build and rattler-build-conda-compat if present.
I also reformatted it so the extra info is under the fold. This is how they look now:
```
MNT: Re-rendered with conda-smithy 3.51.1 and conda-forge-pinning 2025.07.15.13.41.12
Other tools:
- conda-build 25.5.0
- rattler-build 0.44.0
- rattler-build-conda-compat 1.4.3
```
> Reformat commit message to show more info about rattler-* versions

- conda_smithy/configure_feedstock.py
- news/2366-remove-slashes-from-variant-names.rst
- tests/test_lint_recipe.py
Fix issues discovered by py3.14 migration. Currently, the fact that we have values like
```yaml
channel_sources:
- conda-forge,conda-forge/label/python_rc
```
in a zip-key, which ends up in the variant file names as
```
.ci_support/linux_aarch64_channel_sourcesconda-forge,conda-forge/label/python_rcpython3.14.____cp314.yaml
^     ^
!!!!!!!
```
This causes obvious issues because these slashes cause folders where there shouldn't be any (c.f. #2366). Just removing slashes from the filenames fixes this.
Fixes #2366
> Remove slashes and commas from variant names

- conda_smithy/configure_feedstock.py
- conda_smithy/data/conda-forge.yml
- conda_smithy/schema.py
- news/macos_image.rst
This is a bit confusing, given that GHA will [drop](https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/#macos-13-is-closing-down) `macOS-13`, and the [overview page](https://github.com/actions/runner-images/#available-images) for the images makes it seem like `macOS-{14,15}` only exist for `osx-arm64` or in the paid `-large` variant.
However, @jaimergp [pointed out](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=macos-images%2Cyaml) that things are different on Azure Pipelines. I've tested this in https://github.com/conda-forge/scipy-feedstock/pull/250, and indeed, `macOS-14` & `-15` work fine for our `osx-64` workflows.
So I'm not 100% sure if the given …
> switch osx runners to macOS-15; macOS-13 will be removed soon

- conda_smithy/templates/azure-pipelines-linux.yml.tmpl
- news/2384-swap-handling.rst
Fixes #2384; tested in https://github.com/conda-forge/mlir-feedstock/pull/107, which went from ~1-in-4 success rate to create the swap file with the template from smithy 3.52.0, to 100% success rate with the changes from this PR.
> try harder to create swap file; fail early if does not succeed

- conda_smithy/configure_feedstock.py
Fixup for #2381, because rattler-build [packages](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fwin-64%2Frattler-build-0.46.0-h18a1a76_0.conda) the exe in a non-standard location (but matching the relative unix path).
CC @isuruf
> fix rattler-build invocation

- conda_smithy/lint_recipe.py
- news/cfyaml_lint.rst
- tests/test_schema.py
Checklist
closes #2284
See https://github.com/prefix-dev/rattler-build-conda-compat/issues/88 for details on bug in `rattler-build-conda-compat`.
> fix: work around global yaml parsing changes from rattler-build-conda-compat

- conda_smithy/templates/README.md.tmpl
Some obvious punctuation corrections in the README template. Most importantly, the missing comma in "based on branches in forks and branches in the main repository" (where in fact "on branches in forks" is the predicative complement of one clause, and "branches in the main repository" is the subject of another clause).
> Punctuation corrections in README.md.tmpl

- conda_smithy/configure_feedstock.py
- conda_smithy/linter/lints.py
- conda_smithy/utils.py
- news/pyt_str_var.rst
- tests/test_configure_feedstock.py
This PR ensures we only use standard python strings when processing variants loaded via `rattler_build_conda_compat`. 
See this [ci job](https://github.com/conda-forge/admin-requests/actions/runs/18045130153/job/51353901331) for the traceback where we got
```
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/new:ruamel.yaml.scalarstring.DoubleQuotedScalarString'
in "/tmp/tmp22yiw7br__feedstocks/mg5amcnlo-pythia8-interface-feedstock/.ci_support/linux_64_pythia88.312.yaml", line 18, column 3
```
Checklist
> fix: ensure we always use python standard strings when processing variants

- conda_smithy/linter/utils.py
- news/version_template.rst
> linter: ignore package version when it is templated for v1
